// apps/web/src/session-vcs-summary.tsx
import { css } from '@ai-usage/design-system/css';
import { ghostButton } from '@ai-usage/design-system/report';
import {
  parseSessionVcsContext,
  parseSessionVcsResolveResponse,
  type SessionVcsBranchSpan,
  type SessionVcsContext,
  type SessionVcsPullRequest,
  type SessionVcsResolveResponse,
} from '@ai-usage/report-core/session-vcs';
import ExternalLink from 'lucide-solid/icons/external-link';
import { createMemo, For, Show } from 'solid-js';

export interface SessionVcsSummaryProps {
  context: unknown;
  onResolve?: () => void;
  resolution: SessionVcsResolveResponse | null;
  resolving: boolean;
}

const summary = css({
  display: 'grid',
  gap: '10px',
  minW: 0,
  pt: '14px',
  borderTop: '1px solid token(colors.line)',
});
const heading = css({ color: 'ink', fontSize: '13px', fontWeight: 700, lineHeight: 1.3, m: 0 });
const rows = css({ display: 'grid', gap: '7px', minW: 0 });
const row = css({
  display: 'grid',
  gridTemplateColumns: '80px minmax(0, 1fr)',
  gap: '10px',
  alignItems: 'baseline',
  minW: 0,
});
const label = css({ color: 'muted', fontSize: '11px', fontWeight: 650 });
const value = css({ color: 'ink', fontSize: '12px', minW: 0 });
const truncate = css({ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
const link = css({
  display: 'inline-flex',
  gap: '4px',
  alignItems: 'center',
  maxW: 'full',
  color: 'ink',
  textDecoration: 'underline',
  textUnderlineOffset: '2px',
  _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
});
const linkText = css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
const details = css({ minW: 0, mt: '4px' });
const detailsSummary = css({ color: 'muted', cursor: 'pointer', fontSize: '11px' });
const branchList = css({ display: 'grid', gap: '4px', listStyle: 'none', m: 0, mt: '6px', p: 0, minW: 0 });
const note = css({ color: 'muted', fontSize: '11px', lineHeight: 1.45, m: 0 });
const actions = css({ display: 'flex', flexWrap: 'wrap', gap: '8px', alignItems: 'center' });

const parseContext = (context: unknown): SessionVcsContext | null => {
  try {
    return parseSessionVcsContext(context);
  } catch {
    return null;
  }
};

const parseResolution = (resolution: SessionVcsResolveResponse | null): SessionVcsResolveResponse | null => {
  if (!resolution) {
    return null;
  }
  try {
    return parseSessionVcsResolveResponse(resolution);
  } catch {
    return null;
  }
};

const SafeExternalLink = (props: { ariaLabel: string; children: string; title?: string; url: string }) => (
  <a aria-label={props.ariaLabel} class={link} href={props.url} rel="noopener" target="_blank" title={props.title}>
    <span class={linkText}>{props.children}</span>
    <ExternalLink aria-hidden="true" size={13} />
  </a>
);

const BranchValue = (props: { branch: SessionVcsBranchSpan }) => (
  <Show fallback={<span class={truncate}>{props.branch.name}</span>} when={props.branch.webUrl}>
    {(url) => (
      <SafeExternalLink ariaLabel={`Open branch ${props.branch.name} in a new tab`} url={url()}>
        {props.branch.name}
      </SafeExternalLink>
    )}
  </Show>
);

const PullRequestValue = (props: { pullRequest: SessionVcsPullRequest }) => {
  const text = () => (props.pullRequest.number === null ? 'Pull request' : `#${props.pullRequest.number}`);
  return (
    <SafeExternalLink ariaLabel={`Open ${text()} in a new tab`} url={props.pullRequest.url}>
      {text()}
    </SafeExternalLink>
  );
};

const unavailableMessage = (response: Extract<SessionVcsResolveResponse, { status: 'unavailable' }>): string => {
  switch (response.reason) {
    case 'timed-out':
      return 'GitHub lookup timed out.';
    case 'not-local':
      return 'GitHub lookup requires the source machine.';
    case 'provenance-unavailable':
      return 'Recorded repository provenance is unavailable.';
    case 'repository-unsupported':
      return 'The recorded repository provider is not supported.';
    case 'not-found':
      return 'No matching GitHub pull request was found.';
    case 'resolver-unavailable':
      return 'GitHub lookup is unavailable.';
    default:
      return 'GitHub lookup is unavailable.';
  }
};

export const SessionVcsSummary = (props: SessionVcsSummaryProps) => {
  const context = createMemo(() => parseContext(props.context));
  const resolution = createMemo(() => parseResolution(props.resolution));
  const resolved = () => {
    const response = resolution();
    return response?.status === 'available' ? response : null;
  };
  const unavailable = () => {
    const response = resolution();
    return response?.status === 'unavailable' ? response : null;
  };
  const pullRequests = createMemo(() => {
    const recorded = context()?.pullRequests ?? [];
    const ephemeral = resolved()?.pullRequests ?? [];
    const byUrl = new Map(recorded.map((pullRequest) => [pullRequest.url, pullRequest]));
    for (const pullRequest of ephemeral) {
      if (!byUrl.has(pullRequest.url)) {
        byUrl.set(pullRequest.url, pullRequest);
      }
    }
    return [...byUrl.values()];
  });
  const repositoryUrl = () => context()?.repository?.webUrl ?? resolved()?.repositoryUrl ?? null;
  const canResolve = () =>
    Boolean(
      props.onResolve &&
        context()?.repository &&
        context()!.branches.length > 0 &&
        pullRequests().length === 0 &&
        !resolved(),
    );
  const resolveLabel = (): string => {
    if (props.resolving) {
      return 'Resolving GitHub links…';
    }
    return unavailable() ? 'Retry GitHub lookup' : 'Resolve GitHub links';
  };

  return (
    <Show when={context()}>
      {(vcs) => (
        <section aria-label="Session source control" class={summary}>
          <h3 class={heading}>Session source control</h3>
          <div class={rows}>
            <Show when={vcs().repository}>
              {(repository) => (
                <div class={row}>
                  <span class={label}>Repository</span>
                  <div class={value}>
                    <Show fallback={<span class={truncate}>{repository().ownerPath}</span>} when={repositoryUrl()}>
                      {(url) => (
                        <SafeExternalLink
                          ariaLabel={`Open repository ${repository().ownerPath} in a new tab`}
                          url={url()}
                        >
                          {repository().ownerPath}
                        </SafeExternalLink>
                      )}
                    </Show>
                  </div>
                </div>
              )}
            </Show>
            <Show when={vcs().branches.length === 1}>
              <div class={row}>
                <span class={label}>Branch</span>
                <div class={value}>
                  <BranchValue branch={vcs().branches[0]!} />
                </div>
              </div>
            </Show>
            <Show when={vcs().branches.length > 1}>
              <div class={row}>
                <span class={label}>Branches</span>
                <div class={value}>
                  <span
                    class={truncate}
                    title={vcs()
                      .branches.map((branch) => branch.name)
                      .join(' → ')}
                  >
                    {vcs().branches[0]!.name} → {vcs().branches.at(-1)!.name}
                  </span>
                  <details class={details}>
                    <summary class={detailsSummary}>{vcs().branches.length} recorded branch spans</summary>
                    <ul class={branchList}>
                      <For each={vcs().branches}>
                        {(branch) => (
                          <li>
                            <BranchValue branch={branch} />
                          </li>
                        )}
                      </For>
                    </ul>
                  </details>
                </div>
              </div>
            </Show>
            <Show when={vcs().headCommit}>
              {(commit) => (
                <div class={row}>
                  <span class={label}>Commit</span>
                  <div class={value} title={commit().hash}>
                    <Show fallback={<span>{commit().hash.slice(0, 8)}</span>} when={commit().webUrl}>
                      {(url) => (
                        <SafeExternalLink
                          ariaLabel={`Open commit ${commit().hash} in a new tab`}
                          title={commit().hash}
                          url={url()}
                        >
                          {commit().hash.slice(0, 8)}
                        </SafeExternalLink>
                      )}
                    </Show>
                  </div>
                </div>
              )}
            </Show>
            <Show when={pullRequests().length > 0}>
              <div class={row}>
                <span class={label}>Pull request{pullRequests().length === 1 ? '' : 's'}</span>
                <div class={actions}>
                  <For each={pullRequests()}>{(pullRequest) => <PullRequestValue pullRequest={pullRequest} />}</For>
                </div>
              </div>
            </Show>
          </div>
          <Show when={vcs().repository?.provenance === 'local-derived'}>
            <p class={note}>Repository derived from the recorded local checkout.</p>
          </Show>
          <Show when={vcs().partial}>
            <p class={note}>Some recorded source-control context could not be represented safely.</p>
          </Show>
          <Show when={props.resolving}>
            <p aria-live="polite" class={note}>
              Resolving GitHub links…
            </p>
          </Show>
          <Show when={unavailable()}>{(response) => <p class={note}>{unavailableMessage(response())}</p>}</Show>
          <Show when={canResolve()}>
            <button
              aria-label={
                props.resolving
                  ? 'Resolving GitHub repository and pull request links'
                  : 'Resolve GitHub repository and pull request links'
              }
              class={ghostButton}
              disabled={props.resolving}
              onClick={() => props.onResolve?.()}
              type="button"
            >
              {resolveLabel()}
            </button>
          </Show>
        </section>
      )}
    </Show>
  );
};

// apps/web/src/lib/features/sessions/detail/session-vcs-summary.svelte
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const summaryClass = css({
    display: 'grid',
    gap: '10px',
    minW: 0,
    pt: '14px',
    borderTop: '1px solid token(colors.line)',
  });
  const heading = css({ color: 'ink', fontSize: '13px', fontWeight: 700, lineHeight: 1.3, m: 0 });
  const rowsClass = css({ display: 'grid', gap: '7px', minW: 0 });
  const rowClass = css({
    display: 'grid',
    gridTemplateColumns: '80px minmax(0, 1fr)',
    gap: '10px',
    alignItems: 'baseline',
    minW: 0,
  });
  const labelClass = css({ color: 'muted', fontSize: '11px', fontWeight: 650 });
  const valueClass = css({ color: 'ink', fontSize: '12px', minW: 0 });
  const truncate = css({ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
  const link = css({
    display: 'inline-flex',
    gap: '4px',
    alignItems: 'center',
    maxW: 'full',
    color: 'ink',
    textDecoration: 'underline',
    textUnderlineOffset: '2px',
    _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
  });
  const details = css({ minW: 0, mt: '4px' });
  const detailsSummary = css({ color: 'muted', cursor: 'pointer', fontSize: '11px' });
  const branchList = css({ display: 'grid', gap: '4px', listStyle: 'none', m: 0, mt: '6px', p: 0, minW: 0 });
  const note = css({ color: 'muted', fontSize: '11px', lineHeight: 1.45, m: 0 });
  const actions = css({ display: 'flex', flexWrap: 'wrap', gap: '8px', alignItems: 'center' });
  const ghostButton = css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid token(colors.line)',
    borderRadius: 'sm',
    bg: 'surface',
    color: 'muted',
    px: '12px',
    py: '5px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    _hover: { borderColor: 'accent', color: 'accent' },
    _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
  });
</script>

<script lang="ts">
  import {
    parseSessionVcsContext,
    parseSessionVcsResolveResponse,
    type SessionVcsBranchSpan,
    type SessionVcsResolveResponse,
  } from '@ai-usage/report-core/session-vcs';

  let {
    context: rawContext,
    onResolve,
    resolution: rawResolution,
    resolving,
  }: {
    context: unknown;
    onResolve?: () => void;
    resolution: SessionVcsResolveResponse | null;
    resolving: boolean;
  } = $props();

  const context = $derived.by(() => {
    try {
      return parseSessionVcsContext(rawContext);
    } catch {
      return null;
    }
  });
  const resolution = $derived.by(() => {
    if (!rawResolution) {
      return null;
    }
    try {
      return parseSessionVcsResolveResponse(rawResolution);
    } catch {
      return null;
    }
  });
  const available = $derived(resolution?.status === 'available' ? resolution : null);
  const unavailable = $derived(resolution?.status === 'unavailable' ? resolution : null);
  const pullRequests = $derived.by(() => {
    const byUrl = new Map((context?.pullRequests ?? []).map((pullRequest) => [pullRequest.url, pullRequest]));
    for (const pullRequest of available?.pullRequests ?? []) {
      if (!byUrl.has(pullRequest.url)) {
        byUrl.set(pullRequest.url, pullRequest);
      }
    }
    return [...byUrl.values()];
  });
  const repositoryUrl = $derived(context?.repository?.webUrl ?? available?.repositoryUrl ?? null);
  const canResolve = $derived(
    Boolean(onResolve && context?.repository && context.branches.length > 0 && pullRequests.length === 0 && !available),
  );

  const branchUrl = (branch: SessionVcsBranchSpan): string | null => branch.webUrl ?? null;
  const unavailableMessage = (): string => {
    switch (unavailable?.reason) {
      case 'timed-out':
        return 'GitHub lookup timed out.';
      case 'not-local':
        return 'GitHub lookup requires the source machine.';
      case 'provenance-unavailable':
        return 'Recorded repository provenance is unavailable.';
      case 'repository-unsupported':
        return 'The recorded repository provider is not supported.';
      case 'not-found':
        return 'No matching GitHub pull request was found.';
      default:
        return 'GitHub lookup is unavailable.';
    }
  };
  const resolveLabel = (): string => {
    if (resolving) {
      return 'Resolving GitHub links…';
    }
    return unavailable ? 'Retry GitHub lookup' : 'Resolve GitHub links';
  };
</script>

{#if context}
  <section aria-label="Session source control" class={summaryClass}>
    <h3 class={heading}>Session source control</h3>
    <div class={rowsClass}>
      {#if context.repository}
        <div class={rowClass}>
          <span class={labelClass}>Repository</span>
          <div class={valueClass}>
            {#if repositoryUrl}
              <a
                aria-label={`Open repository ${context.repository.ownerPath} in a new tab`}
                class={link}
                href={repositoryUrl}
                rel="noopener"
                target="_blank"
              >
                <span class={truncate}>{context.repository.ownerPath}</span><span aria-hidden="true">↗</span>
              </a>
            {:else}
              <span class={truncate}>{context.repository.ownerPath}</span>
            {/if}
          </div>
        </div>
      {/if}
      {#if context.branches.length === 1}
        {@const branch = context.branches[0]}
        {#if branch}
          <div class={rowClass}>
            <span class={labelClass}>Branch</span>
            <div class={valueClass}>
              {#if branchUrl(branch)}
                <a
                  aria-label={`Open branch ${branch.name} in a new tab`}
                  class={link}
                  href={branchUrl(branch) ?? undefined}
                  rel="noopener"
                  target="_blank"
                  >{branch.name}<span aria-hidden="true">↗</span></a
                >
              {:else}
                <span class={truncate}>{branch.name}</span>
              {/if}
            </div>
          </div>
        {/if}
      {:else if context.branches.length > 1}
        <div class={rowClass}>
          <span class={labelClass}>Branches</span>
          <div class={valueClass}>
            <span class={truncate} title={context.branches.map((branch) => branch.name).join(' → ')}>
              {context.branches[0]?.name}
              → {context.branches.at(-1)?.name}
            </span>
            <details class={details}>
              <summary class={detailsSummary}>{context.branches.length} recorded branch spans</summary>
              <ul class={branchList}>
                {#each context.branches as branch (`${branch.name}:${branch.firstObservedAt}`)}
                  <li>
                    {#if branchUrl(branch)}
                      <a
                        aria-label={`Open branch ${branch.name} in a new tab`}
                        class={link}
                        href={branchUrl(branch) ?? undefined}
                        rel="noopener"
                        target="_blank"
                        >{branch.name}<span aria-hidden="true">↗</span></a
                      >
                    {:else}
                      {branch.name}
                    {/if}
                  </li>
                {/each}
              </ul>
            </details>
          </div>
        </div>
      {/if}
      {#if context.headCommit}
        <div class={rowClass}>
          <span class={labelClass}>Commit</span>
          <div class={valueClass} title={context.headCommit.hash}>
            {#if context.headCommit.webUrl}
              <a
                aria-label={`Open commit ${context.headCommit.hash} in a new tab`}
                class={link}
                href={context.headCommit.webUrl}
                rel="noopener"
                target="_blank"
                >{context.headCommit.hash.slice(0, 8)}<span aria-hidden="true">↗</span></a
              >
            {:else}
              {context.headCommit.hash.slice(0, 8)}
            {/if}
          </div>
        </div>
      {/if}
      {#if pullRequests.length > 0}
        <div class={rowClass}>
          <span class={labelClass}>Pull request{pullRequests.length === 1 ? '' : 's'}</span>
          <div class={actions}>
            {#each pullRequests as pullRequest (pullRequest.url)}
              {@const text = pullRequest.number === null ? 'Pull request' : `#${pullRequest.number}`}
              <a
                aria-label={`Open ${text} in a new tab`}
                class={link}
                href={pullRequest.url}
                rel="noopener"
                target="_blank"
                >{text}<span aria-hidden="true">↗</span></a
              >
            {/each}
          </div>
        </div>
      {/if}
    </div>
    {#if context.repository?.provenance === 'local-derived'}
      <p class={note}>Repository derived from the recorded local checkout.</p>
    {/if}
    {#if context.partial}
      <p class={note}>Some recorded source-control context could not be represented safely.</p>
    {/if}
    {#if resolving}
      <p aria-live="polite" class={note}>Resolving GitHub links…</p>
    {/if}
    {#if unavailable}
      <p class={note}>{unavailableMessage()}</p>
    {/if}
    {#if canResolve}
      <button
        aria-label={resolving
          ? 'Resolving GitHub repository and pull request links'
          : 'Resolve GitHub repository and pull request links'}
        class={ghostButton}
        disabled={resolving}
        onclick={() => onResolve?.()}
        type="button"
      >
        {resolveLabel()}
      </button>
    {/if}
  </section>
{/if}
