// apps/web/src/skill-diagnostics.tsx
import { css, cx } from '@ai-usage/design-system/css';
import {
  meta,
  panelHeader,
  panelTitle,
  skillsDiagnosticRow,
  statusPill,
  statusPillDanger,
  statusPillInfo,
  statusPillWarn,
  strongCell,
} from '@ai-usage/design-system/report';
import type { SkillDiagnostic } from '@ai-usage/skills';
import { For, Show } from 'solid-js';
import { fmtNum } from './shared';
import { skillDiagnosticLabel } from './skills-page-model';

const section = css({
  display: 'grid',
  gap: '10px',
});

const diagnosticPillClass = (diagnostic: SkillDiagnostic): string => {
  if (diagnostic.severity === 'error') {
    return statusPillDanger;
  }
  if (diagnostic.severity === 'warning') {
    return statusPillWarn;
  }
  return statusPillInfo;
};

export const SkillDiagnostics = (props: { diagnostics: readonly SkillDiagnostic[] }) => (
  <Show when={props.diagnostics.length > 0}>
    <section class={section}>
      <div class={panelHeader}>
        <h3 class={panelTitle}>Diagnostics</h3>
      </div>
      <For each={props.diagnostics}>
        {(diagnostic) => (
          <div class={skillsDiagnosticRow}>
            <span class={cx(statusPill, diagnosticPillClass(diagnostic))}>{diagnostic.severity}</span>
            <div class={strongCell}>{skillDiagnosticLabel(diagnostic.code)}</div>
            <div class={meta}>{diagnostic.message}</div>
            <Show when={diagnostic.tokenMeasurement}>
              {(measurement) => (
                <div class={meta} data-token-measurement>
                  {fmtNum(measurement().observed)} / {fmtNum(measurement().threshold)} tokens
                </div>
              )}
            </Show>
          </div>
        )}
      </For>
    </section>
  </Show>
);

// apps/web/src/lib/features/skills/management/skill-diagnostics.svelte
<script lang="ts">
  import { cx } from '@ai-usage/design-system/css';
  import type { SkillDiagnostic } from '@ai-usage/skills';
  import { skillDiagnosticLabel } from '../../../../skills-page-model';
  import { fmtNum } from '../../../foundation/presentation/format';
  import { dangerPill, diagnosticRow, heading, infoPill, muted, pill, stack, warningPill } from './styles';

  let { diagnostics }: { diagnostics: readonly SkillDiagnostic[] } = $props();
  const tone = (severity: SkillDiagnostic['severity']): string => {
    if (severity === 'error') {
      return dangerPill;
    }
    if (severity === 'warning') {
      return warningPill;
    }
    return infoPill;
  };
</script>

{#if diagnostics.length > 0}
  <section class={stack}>
    <h3 class={heading}>Diagnostics</h3>
    {#each diagnostics as diagnostic}
      <div class={diagnosticRow}>
        <span class={cx(pill, tone(diagnostic.severity))}>{diagnostic.severity}</span>
        <strong>{skillDiagnosticLabel(diagnostic.code)}</strong>
        <div class={muted}>{diagnostic.message}</div>
        {#if diagnostic.tokenMeasurement}
          <div class={muted} data-token-measurement>
            {fmtNum(diagnostic.tokenMeasurement.observed)}
            / {fmtNum(diagnostic.tokenMeasurement.threshold)} tokens
          </div>
        {/if}
      </div>
    {/each}
  </section>
{/if}
