// apps/web/src/skills-tree.tsx
import { css, cx } from '@ai-usage/design-system/css';
import {
  panel,
  panelHeader,
  panelSub,
  panelTitle,
  searchInput,
  statusPill,
  statusPillDanger,
  statusPillWarn,
  strongCell,
} from '@ai-usage/design-system/report';
import { createMemo, For, Show } from 'solid-js';
import { type KnownProjectScope, type SkillSelection, type SkillTreeModel, selectionKey } from './skills-page-model';
import { SkillSelectionLink } from './skills-selection-link';

const treePanel = css({
  alignSelf: 'start',
  position: { base: 'static', lg: 'sticky' },
  top: '16px',
  maxH: { base: 'none', lg: 'calc(100vh - 32px)' },
  overflow: 'auto',
});

const treeStack = css({
  display: 'grid',
  gap: '12px',
});

const scopeGroup = css({
  display: 'grid',
  gap: '6px',
});

const scopeRow = css({
  display: 'grid',
  gridTemplateColumns: '32px minmax(0, 1fr)',
  gap: '4px',
  alignItems: 'stretch',
});

const treeButton = css({
  appearance: 'none',
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 1fr) auto',
  gap: '8px',
  alignItems: 'center',
  w: '100%',
  minW: 0,
  p: '8px 10px',
  border: '1px solid transparent',
  borderRadius: 'sm',
  bg: 'transparent',
  color: 'ink',
  textAlign: 'left',
  cursor: 'pointer',
  _hover: {
    bg: 'surfaceMuted',
    borderColor: 'line',
  },
  _focusVisible: {
    outline: '2px solid token(colors.accent)',
    outlineOffset: '2px',
  },
  '&[data-selected="true"]': {
    bg: 'accentTint',
    borderColor: 'accent',
  },
});

const toggleButton = css({
  appearance: 'none',
  display: 'grid',
  placeItems: 'center',
  minW: 0,
  border: '1px solid transparent',
  borderRadius: 'sm',
  bg: 'transparent',
  color: 'muted',
  cursor: 'pointer',
  _hover: {
    bg: 'surfaceMuted',
    borderColor: 'line',
  },
  _focusVisible: {
    outline: '2px solid token(colors.accent)',
    outlineOffset: '2px',
  },
});

const skillButton = css({
  pl: '36px',
});

const nodeLabel = css({
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
});

const scopeLabel = css({
  display: 'flex',
  minW: 0,
  gap: '6px',
  alignItems: 'baseline',
  overflow: 'hidden',
  whiteSpace: 'nowrap',
});

const scopeName = css({
  display: 'block',
  minW: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
});

const scopePath = css({
  minW: 0,
  color: 'muted',
  fontSize: '12px',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
});

const subtleCount = css({
  color: 'muted',
  fontSize: '11px',
  fontWeight: 650,
});

const attentionPill = css({
  minW: '22px',
  justifyContent: 'center',
});

const emptyFold = css({
  display: 'grid',
  gap: '6px',
});

const emptySummary = css({
  color: 'muted',
  cursor: 'pointer',
  fontSize: '13px',
  fontWeight: 650,
  listStyle: 'none',
  _marker: {
    display: 'none',
  },
});

const filterInfo = css({
  color: 'muted',
  fontSize: '12px',
  lineHeight: 1.5,
});

const statusClass = (validationStatus?: string) => (validationStatus === 'invalid' ? statusPillDanger : statusPillWarn);

export const SkillsTree = (props: {
  ariaLabel?: string;
  expandedKeys: ReadonlySet<string>;
  idPrefix?: string;
  knownProjects: readonly KnownProjectScope[];
  model: SkillTreeModel;
  onQueryChange: (value: string) => void;
  onToggleScope: (scopeKey: string) => void;
  query: string;
  selection: SkillSelection;
}) => {
  const activeKey = createMemo(() => selectionKey(props.selection));
  const normalizedQuery = createMemo(() => props.query.trim().toLowerCase());
  const scopes = createMemo(() => {
    const query = normalizedQuery();
    if (!query) {
      return props.model.scopes;
    }
    return props.model.scopes
      .map((scope) => {
        const scopeMatches =
          scope.label.toLowerCase().includes(query) || (scope.path?.toLowerCase().includes(query) ?? false);
        const skills = scope.skills.filter(
          (skill) =>
            scopeMatches || skill.name.toLowerCase().includes(query) || skill.description.toLowerCase().includes(query),
        );
        return scopeMatches || skills.length > 0 ? { ...scope, skills } : undefined;
      })
      .filter((scope) => scope !== undefined);
  });
  const emptyScopes = createMemo(() => {
    const query = normalizedQuery();
    if (!query) {
      return props.model.emptyScopes;
    }
    return props.model.emptyScopes.filter(
      (scope) => scope.label.toLowerCase().includes(query) || (scope.path?.toLowerCase().includes(query) ?? false),
    );
  });
  const hasVisibleScopes = createMemo(() => scopes().length + emptyScopes().length > 0);

  return (
    <aside aria-label={props.ariaLabel ?? 'Skill scopes'} class={cx(panel, treePanel)}>
      <div class={panelHeader}>
        <h2 class={panelTitle}>Skills</h2>
        <p class={panelSub}>Global and project scopes</p>
      </div>
      <input
        aria-label="Filter scopes and skills"
        class={searchInput}
        onInput={(event) => props.onQueryChange(event.currentTarget.value)}
        placeholder="Filter scopes or skills..."
        value={props.query}
      />
      <div class={treeStack}>
        <Show fallback={<p class={filterInfo}>No scopes or skills match this filter.</p>} when={hasVisibleScopes()}>
          <For each={scopes()}>
            {(scope) => (
              <section class={scopeGroup}>
                {(() => {
                  const listId = `${props.idPrefix ?? 'skill'}-scope-${scope.key.replaceAll(/[^a-zA-Z0-9_-]/g, '-')}`;
                  const expanded = () => normalizedQuery().length > 0 || props.expandedKeys.has(scope.key);
                  return (
                    <>
                      <div class={scopeRow}>
                        <button
                          aria-controls={listId}
                          aria-expanded={expanded()}
                          aria-label={`${expanded() ? 'Collapse' : 'Expand'} ${scope.label}`}
                          class={toggleButton}
                          onClick={() => props.onToggleScope(scope.key)}
                          type="button"
                        >
                          {expanded() ? '▾' : '▸'}
                        </button>
                        <SkillSelectionLink
                          class={treeButton}
                          knownProjects={props.knownProjects}
                          selected={activeKey() === scope.key}
                          selection={scope.selection}
                          title={scope.path}
                        >
                          <span class={scopeLabel}>
                            <span class={cx(strongCell, scopeName)} data-skill-scope-name title={scope.label}>
                              {scope.label}
                            </span>
                            <Show when={scope.shortPath}>
                              {(shortPath) => <span class={scopePath}>{shortPath()}</span>}
                            </Show>
                          </span>
                          <span class={subtleCount}>{scope.skills.length}</span>
                        </SkillSelectionLink>
                      </div>
                      <Show when={expanded()}>
                        <div id={listId}>
                          <For each={scope.skills}>
                            {(skill) => (
                              <SkillSelectionLink
                                class={cx(treeButton, skillButton)}
                                knownProjects={props.knownProjects}
                                selected={activeKey() === skill.key}
                                selection={skill.selection}
                                title={skill.description || skill.name}
                              >
                                <span class={nodeLabel}>{skill.name}</span>
                                <Show when={skill.issueCount > 0 || skill.validationStatus === 'invalid'}>
                                  <span
                                    class={cx(statusPill, statusClass(skill.validationStatus), attentionPill)}
                                    title={skill.attentionSummary || undefined}
                                  >
                                    {skill.validationStatus === 'invalid' ? '!' : skill.issueCount}
                                  </span>
                                </Show>
                              </SkillSelectionLink>
                            )}
                          </For>
                        </div>
                      </Show>
                    </>
                  );
                })()}
              </section>
            )}
          </For>
          <Show when={emptyScopes().length > 0}>
            <details class={emptyFold}>
              <summary class={emptySummary}>Projects without skills ({emptyScopes().length})</summary>
              <For each={emptyScopes()}>
                {(scope) => (
                  <SkillSelectionLink
                    class={treeButton}
                    knownProjects={props.knownProjects}
                    selected={activeKey() === scope.key}
                    selection={scope.selection}
                    title={scope.path}
                  >
                    <span class={scopeLabel}>
                      <span class={cx(strongCell, scopeName)} data-skill-scope-name title={scope.label}>
                        {scope.label}
                      </span>
                      <Show when={scope.shortPath}>{(shortPath) => <span class={scopePath}>{shortPath()}</span>}</Show>
                    </span>
                    <span class={subtleCount}>0</span>
                  </SkillSelectionLink>
                )}
              </For>
            </details>
          </Show>
        </Show>
      </div>
    </aside>
  );
};

// apps/web/src/lib/features/skills/shell/skills-tree.svelte
<script lang="ts">
  import { css, cx } from '@ai-usage/design-system/css';
  import { panel, panelSub, panelTitle, strongCell } from '@ai-usage/design-system/svelte';
  import type { KnownProjectScope, SkillSelection, SkillTreeModel } from '../../../../skills-page-model';
  import { selectionKey } from '../../../../skills-page-model';
  import SelectionLink from './selection-link.svelte';

  let {
    ariaLabel = 'Skill scopes',
    collapsedKeys,
    expandedKeys,
    filterQuery,
    idPrefix = 'skill',
    knownProjects,
    model,
    onFilterChange,
    onScopeToggle,
    selection,
  }: {
    ariaLabel?: string;
    collapsedKeys: ReadonlySet<string>;
    expandedKeys: ReadonlySet<string>;
    filterQuery: string;
    idPrefix?: string;
    knownProjects: readonly KnownProjectScope[];
    model: SkillTreeModel;
    onFilterChange: (value: string) => void;
    onScopeToggle: (scopeKey: string, expanded: boolean) => void;
    selection: SkillSelection;
  } = $props();

  const normalizedQuery = $derived(filterQuery.trim().toLowerCase());
  const visibleScopes = $derived(
    model.scopes
      .map((scope) => {
        if (!normalizedQuery) {
          return scope;
        }
        const scopeMatches =
          scope.label.toLowerCase().includes(normalizedQuery) ||
          (scope.path?.toLowerCase().includes(normalizedQuery) ?? false);
        const skills = scope.skills.filter(
          (skill) =>
            scopeMatches ||
            skill.name.toLowerCase().includes(normalizedQuery) ||
            skill.description.toLowerCase().includes(normalizedQuery),
        );
        return scopeMatches || skills.length > 0 ? { ...scope, skills } : undefined;
      })
      .filter((scope) => scope !== undefined),
  );
  const emptyScopes = $derived(
    normalizedQuery
      ? model.emptyScopes.filter(
          (scope) =>
            scope.label.toLowerCase().includes(normalizedQuery) ||
            (scope.path?.toLowerCase().includes(normalizedQuery) ?? false),
        )
      : model.emptyScopes,
  );
  const activeKey = $derived(selectionKey(selection));
  const activeScopeKey = $derived(
    selection.type === 'global-scope' || selection.type === 'global-skill'
      ? 'global'
      : selectionKey({ projectPath: selection.projectPath, type: 'project-scope' }),
  );

  const treePanel = css({
    alignSelf: 'start',
    position: { base: 'static', lg: 'sticky' },
    top: '16px',
    maxH: { base: 'none', lg: 'calc(100vh - 32px)' },
    overflow: 'auto',
  });
  const panelHeader = css({ display: 'grid', gap: '2px' });
  const treeStack = css({ display: 'grid', gap: '12px' });
  const scopeGroup = css({ display: 'grid', gap: '6px' });
  const scopeRow = css({
    display: 'grid',
    gridTemplateColumns: '32px minmax(0, 1fr)',
    gap: '4px',
    alignItems: 'stretch',
  });
  const searchInput = css({
    flex: '1 1 240px',
    minW: '180px',
    w: '100%',
    h: '36px',
    px: '12px',
    border: '1px solid token(colors.lineStrong)',
    borderRadius: 'sm',
    bg: 'surface',
    color: 'ink',
    fontSize: '13px',
    outline: 'none',
  });
  const treeButton = css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
    minW: 0,
    p: '8px 10px',
    border: '1px solid transparent',
    borderRadius: 'sm',
    color: 'ink',
    textDecoration: 'none',
    _hover: { bg: 'surfaceMuted', borderColor: 'line' },
    _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
    '&[data-selected="true"]': { bg: 'accentTint', borderColor: 'accent' },
  });
  const collidingScopeButton = css({ gridTemplateColumns: 'minmax(0, 1fr)' });
  const skillButton = css({ pl: '36px' });
  const toggleButton = css({
    border: '1px solid transparent',
    borderRadius: 'sm',
    bg: 'transparent',
    color: 'muted',
    cursor: 'pointer',
    _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
  });
  const label = css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
  const scopeLabel = css({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: '1px 8px', minW: 0 });
  const scopeName = css({
    display: 'block',
    minW: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    gridColumn: '1 / -1',
  });
  const scopePath = css({
    minW: 0,
    color: 'muted',
    fontSize: '11px',
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  });
  const skillLabel = css({ minW: 0, lineClamp: 2, overflowWrap: 'break-word', lineHeight: 1.3 });
  const count = css({ color: 'muted', fontSize: '11px', fontWeight: 650 });
  const attention = css({ color: 'status.warn', fontSize: '11px', fontWeight: 700 });
  const emptyFold = css({ display: 'grid', gap: '6px' });
  const emptySummary = css({
    color: 'muted',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 650,
    listStyle: 'none',
    _marker: { display: 'none' },
  });
  const filterInfo = css({ color: 'muted', fontSize: '12px', lineHeight: 1.5 });
</script>

<aside aria-label={ariaLabel} class={cx(panel, treePanel)}>
  <div class={panelHeader}>
    <h2 class={panelTitle}>Skills</h2>
    <p class={panelSub}>Global and project scopes</p>
  </div>
  <input
    aria-label="Filter scopes and skills"
    class={searchInput}
    oninput={(event) => onFilterChange(event.currentTarget.value)}
    placeholder="Filter scopes or skills..."
    value={filterQuery}
  >
  <div class={treeStack}>
    {#if visibleScopes.length + emptyScopes.length === 0}
      <p class={filterInfo}>No scopes or skills match this filter.</p>
    {:else}
      {#each visibleScopes as scope (scope.key)}
        {@const listId = `${idPrefix}-scope-${scope.key.replaceAll(/[^a-zA-Z0-9_-]/g, '-')}`}
        {@const expanded =
          normalizedQuery.length > 0 ||
          (!collapsedKeys.has(scope.key) && (expandedKeys.has(scope.key) || activeScopeKey === scope.key))}
        <section class={scopeGroup}>
          <div class={scopeRow}>
            {#if expanded}
              <button
                aria-controls={listId}
                aria-expanded="true"
                aria-label={`Collapse ${scope.label}`}
                class={toggleButton}
                onclick={() => onScopeToggle(scope.key, expanded)}
                type="button"
              >
                ▾
              </button>
            {:else}
              <button
                aria-controls={listId}
                aria-expanded="false"
                aria-label={`Expand ${scope.label}`}
                class={toggleButton}
                onclick={() => onScopeToggle(scope.key, expanded)}
                type="button"
              >
                ▸
              </button>
            {/if}
            <SelectionLink
              class={cx(treeButton, scope.shortPath ? collidingScopeButton : undefined)}
              {knownProjects}
              selected={activeKey === scope.key}
              selection={scope.selection}
              title={scope.path}
            >
              <span class={scopeLabel}>
                <span class={cx(strongCell, scopeName)} data-skill-scope-name title={scope.label}>{scope.label}</span>
                {#if scope.shortPath}
                  <span class={scopePath} data-skill-scope-path>{scope.shortPath}</span>
                  <span class={count}>{scope.skills.length}</span>
                {/if}
              </span>
              {#if !scope.shortPath}
                <span class={count}>{scope.skills.length}</span>
              {/if}
            </SelectionLink>
          </div>
          {#if expanded}
            <div id={listId}>
              {#each scope.skills as skill (skill.key)}
                <SelectionLink
                  class={cx(treeButton, skillButton)}
                  {knownProjects}
                  selected={activeKey === skill.key}
                  selection={skill.selection}
                  title={skill.description || skill.name}
                >
                  <span class={skillLabel}>{skill.name}</span>
                  {#if skill.issueCount > 0 || skill.validationStatus === 'invalid'}
                    <span class={attention} title={skill.attentionSummary || undefined}>
                      {skill.validationStatus === 'invalid' ? '!' : skill.issueCount}
                    </span>
                  {/if}
                </SelectionLink>
              {/each}
            </div>
          {/if}
        </section>
      {/each}
      {#if emptyScopes.length > 0}
        <details class={emptyFold}>
          <summary class={emptySummary}>Projects without skills ({emptyScopes.length})</summary>
          {#each emptyScopes as scope (scope.key)}
            <SelectionLink
              class={treeButton}
              {knownProjects}
              selected={activeKey === scope.key}
              selection={scope.selection}
              title={scope.path}
            >
              <span class={cx(label, scopeName)} data-skill-scope-name title={scope.label}>{scope.label}</span
              ><span class={count}>0</span>
            </SelectionLink>
          {/each}
        </details>
      {/if}
    {/if}
  </div>
</aside>
