// apps/web/src/lib/features/sessions/detail/drawer-detail-item.svelte
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const detailLabelRow = css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '6px',
  });
  const detailInfoButton = css({
    display: 'inline-grid',
    placeItems: 'center',
    w: '24px',
    h: '24px',
    p: 0,
    border: '1px solid token(colors.line)',
    borderRadius: 'full',
    bg: 'surfaceMuted',
    color: 'muted',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
    _hover: { borderColor: 'lineStrong', color: 'ink' },
    _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
  });
  const detailHintContent = css({
    maxW: '320px',
    color: 'ink',
    fontSize: '13px',
    lineHeight: 1.5,
  });
  const detailItem = css({ display: 'grid', gap: '5px', minW: 0 });
  const detailLabel = css({ textStyle: 'label', color: 'muted' });
  const detailValue = css({
    textStyle: 'numeric',
    fontSize: '13px',
    fontWeight: 500,
    overflowWrap: 'anywhere',
  });
  const popoverContent = css({
    zIndex: 50,
    display: 'grid',
    gap: '10px',
    w: 'min(560px, calc(100vw - 32px))',
    p: '12px',
    border: '1px solid token(colors.line)',
    borderRadius: 'md',
    bg: 'surface',
    boxShadow: 'overlay',
  });
</script>

<script lang="ts">
  import Popover from '@ai-usage/design-system/svelte/popover';

  let { hint, label, value }: { hint?: string; label: string; value: string } = $props();
</script>

<div class={detailItem} data-detail-item={label}>
  <div class={detailLabelRow}>
    <div class={detailLabel}>{label}</div>
    {#if hint}
      <Popover
        contentClass={popoverContent}
        triggerAriaLabel={`About ${label}`}
        triggerClass={detailInfoButton}
        triggerTitle={`About ${label}`}
      >
        {#snippet trigger()}
          <span aria-hidden="true">i</span>
        {/snippet}
        <div class={detailHintContent}>{hint}</div>
      </Popover>
    {/if}
  </div>
  <div class={detailValue}>{value}</div>
</div>

// apps/web/src/drawer-detail-item.tsx
import { Popover } from '@ai-usage/design-system';
import { css } from '@ai-usage/design-system/css';
import { detailItem, detailLabel, detailValue, popoverContent } from '@ai-usage/design-system/report';
import { Show } from 'solid-js';

const detailLabelRow = css({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: '6px',
});

const detailInfoButton = css({
  display: 'inline-grid',
  placeItems: 'center',
  w: '24px',
  h: '24px',
  p: 0,
  border: '1px solid token(colors.line)',
  borderRadius: 'full',
  bg: 'surfaceMuted',
  color: 'muted',
  fontSize: '12px',
  fontWeight: 700,
  cursor: 'pointer',
  _hover: { borderColor: 'lineStrong', color: 'ink' },
  _focusVisible: {
    outline: '2px solid token(colors.accent)',
    outlineOffset: '2px',
  },
});

const detailHintContent = css({
  maxW: '320px',
  color: 'ink',
  fontSize: '13px',
  lineHeight: 1.5,
});

export const DrawerDetailItem = (props: { hint?: string; label: string; value: string }) => (
  <div class={detailItem} data-detail-item={props.label}>
    <div class={detailLabelRow}>
      <div class={detailLabel}>{props.label}</div>
      <Show when={props.hint}>
        {(hint) => (
          <Popover
            contentClass={popoverContent}
            trigger={<span aria-hidden="true">i</span>}
            triggerAriaLabel={`About ${props.label}`}
            triggerClass={detailInfoButton}
          >
            <div class={detailHintContent}>{hint()}</div>
          </Popover>
        )}
      </Show>
    </div>
    <div class={detailValue}>{props.value}</div>
  </div>
);
