// apps/web/src/lib/features/sessions/detail/session-analysis.svelte
<!-- biome-ignore-all lint/a11y/useValidAriaValues: Svelte emits closed boolean ARIA values asserted by SSR -->
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const panel = css({ display: 'grid', gap: '20px', minW: 0, w: 'full' });
  const header = css({ display: 'grid', gap: '5px' });
  const heading = css({ color: 'ink', fontSize: '18px', fontWeight: 700, lineHeight: 1.25, m: 0 });
  const sectionHeading = css({ color: 'ink', fontSize: '14px', fontWeight: 700, lineHeight: 1.3, m: 0 });
  const muted = css({ color: 'muted', fontSize: '12px', lineHeight: 1.5 });
  const numeric = css({ fontFamily: 'mono', fontVariantNumeric: 'tabular-nums' });
  const section = css({ display: 'grid', gap: '12px', minW: 0 });
  const sectionHeader = css({ display: 'grid', gap: '3px' });
  const durationCaption = css({ display: 'flex', flexWrap: 'wrap', gap: '4px 8px', color: 'muted', fontSize: '11px' });
  const durationCaptionPart = css({ whiteSpace: 'nowrap' });
  const notice = css({
    display: 'grid',
    gap: '4px',
    p: '10px 12px',
    border: '1px solid token(colors.line)',
    borderRadius: 'sm',
    bg: 'accentTint',
    color: 'ink',
    fontSize: '12px',
    lineHeight: 1.5,
  });
  const warningNotice = css({ bg: 'status.warnSoft', borderColor: 'status.warn', color: 'ink' });
  const timelineShell = css({
    display: 'grid',
    gap: '8px',
    minW: 0,
    p: { base: '10px', md: '12px' },
    border: '1px solid token(colors.line)',
    borderRadius: 'md',
    bg: 'surfaceMuted',
  });
  const timelineAxis = css({
    display: 'grid',
    gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'minmax(220px, 0.42fr) minmax(0, 1fr) minmax(72px, 0.16fr)' },
    gap: '12px',
    alignItems: 'end',
  });
  const axisLabels = css({
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
    color: 'faint',
    fontFamily: 'mono',
    fontSize: '10px',
  });
  const axisTrack = css({ position: 'relative', minW: 0 });
  const scaleBreakClass = css({
    position: 'absolute',
    top: '-2px',
    color: 'ink',
    fontSize: '14px',
    fontWeight: 700,
    transform: 'translateX(-50%)',
  });
  const timelineList = css({ display: 'grid', gap: '7px', listStyle: 'none', m: 0, p: 0 });
  const timelineRow = css({
    display: 'grid',
    gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'minmax(220px, 0.42fr) minmax(0, 1fr) minmax(72px, 0.16fr)' },
    gap: { base: '5px', md: '12px' },
    alignItems: 'center',
    minW: 0,
  });
  const timelineMeta = css({ color: 'muted', fontSize: '10px', lineHeight: 1.4, overflowWrap: 'anywhere' });
  const timelineTrack = css({
    position: 'relative',
    h: '20px',
    minW: 0,
    overflow: 'hidden',
    border: '1px solid token(colors.line)',
    borderRadius: 'sm',
    bg: 'track',
  });
  const wallClockTrack = css({
    backgroundImage:
      'linear-gradient(to right, transparent 24.8%, token(colors.line) 25%, transparent 25.2%, transparent 49.8%, token(colors.line) 50%, transparent 50.2%, transparent 74.8%, token(colors.line) 75%, transparent 75.2%)',
  });
  const timelineBar = css({ position: 'absolute', top: '3px', bottom: '3px', borderRadius: '4px' });
  const turnBar = css({ bg: 'accent', boxShadow: '0 0 0 1px token(colors.focusRing)' });
  const pointMarker = css({
    position: 'absolute',
    top: '5px',
    w: '8px',
    h: '8px',
    bg: 'accent',
    border: '1px solid token(colors.focusRing)',
    transform: 'translateX(-50%) rotate(45deg)',
  });
  const phaseDot = css({ display: 'inline-block', flex: '0 0 auto', w: '8px', h: '8px', borderRadius: 'full' });
  const phaseToneClasses = [
    css({ bg: 'chart.c1' }),
    css({ bg: 'chart.c2' }),
    css({ bg: 'chart.c3' }),
    css({ bg: 'chart.c4' }),
    css({ bg: 'chart.c5' }),
    css({ bg: 'chart.c6' }),
  ] as const;
  const empty = css({
    p: '14px',
    border: '1px dashed token(colors.lineStrong)',
    borderRadius: 'md',
    color: 'muted',
    fontSize: '12px',
    textAlign: 'center',
  });
  const promptDisclosure = css({
    overflow: 'hidden',
    border: '1px solid token(colors.line)',
    borderRadius: 'md',
    bg: 'surfaceMuted',
  });
  const promptSummary = css({
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: '9px',
    alignItems: 'center',
    p: '10px 12px',
    color: 'ink',
    cursor: 'pointer',
    fontSize: '12px',
  });
  const promptBody = css({
    display: 'grid',
    gap: '10px',
    p: '12px',
    borderTop: '1px solid token(colors.line)',
    bg: 'surface',
    color: 'ink',
    fontFamily: 'mono',
    fontSize: '11px',
    lineHeight: 1.6,
    overflowWrap: 'anywhere',
    whiteSpace: 'pre-wrap',
  });
  const pill = css({
    px: '7px',
    py: '2px',
    borderRadius: 'full',
    bg: 'status.warnSoft',
    color: 'status.warn',
    fontSize: '10px',
    fontWeight: 700,
  });
  const tokenCell = css({ display: { base: 'none', md: 'flex' }, gap: '7px', alignItems: 'center', minW: 0 });
  const tokenTrack = css({ flex: '1 1 auto', h: '6px', overflow: 'hidden', borderRadius: 'sm', bg: 'track' });
  const tokenBar = css({ display: 'block', h: 'full', bg: 'accent' });
  const tokenValue = css({ color: 'ink', fontFamily: 'mono', fontSize: '10px', fontVariantNumeric: 'tabular-nums' });
  const phaseLegend = css({ display: 'flex', flexWrap: 'wrap', gap: '6px', alignItems: 'center' });
  const scaleButton = css({
    justifySelf: 'start',
    px: '8px',
    py: '5px',
    border: '1px solid token(colors.lineStrong)',
    borderRadius: 'sm',
    bg: 'surface',
    color: 'ink',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 650,
  });
  const statePanel = css({
    display: 'grid',
    placeItems: 'center',
    gap: '10px',
    minH: '220px',
    p: '24px',
    border: '1px solid token(colors.line)',
    borderRadius: 'md',
    bg: 'surfaceMuted',
    color: 'muted',
    textAlign: 'center',
  });
  const stateTitle = css({ color: 'ink', fontSize: '15px', fontWeight: 700 });
  const visuallyHidden = css({ srOnly: true });
  const retryButton = css({
    px: '12px',
    py: '7px',
    border: '1px solid token(colors.lineStrong)',
    borderRadius: 'sm',
    bg: 'surface',
    color: 'ink',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 650,
  });
</script>

<script lang="ts">
  import { cx } from '@ai-usage/design-system/css';
  import type { SessionDetailPhase, SessionDetailResponse } from '@ai-usage/report-core/session-detail';
  import type { SessionAnalysisError } from '../../../../session-analysis-error';
  import {
    buildSessionTimelineRows,
    buildTimelineScale,
    countActivityBursts,
    countLabel,
    formatSessionDuration,
    phaseTokenShare,
    positionOnScale,
    type SessionTimelineRow,
    sessionDurationCaption,
    sessionDurationSemantics,
    type TimelineScaleMode,
    timelineHasCompressibleGaps,
  } from '../../../../session-analysis-model';
  import { buildSessionAnalysisPresentation } from '../../../../session-analysis-presentation';
  import type { SessionAnalysisTarget } from '../../../../session-analysis-target';

  let {
    error: analysisError = null,
    harnessKey,
    loading,
    onRetry,
    response,
    target,
  }: {
    error?: SessionAnalysisError | null;
    harnessKey: string;
    loading: boolean;
    onRetry?: () => void;
    response: SessionDetailResponse | null;
    target: SessionAnalysisTarget;
  } = $props();

  const dateTimeFormatter = new Intl.DateTimeFormat('en', {
    day: '2-digit',
    hour: '2-digit',
    hourCycle: 'h23',
    minute: '2-digit',
    month: 'short',
  });
  const compactNumberFormatter = new Intl.NumberFormat('en', { maximumFractionDigits: 1, notation: 'compact' });
  const moneyFormatter = new Intl.NumberFormat('en-US', {
    currency: 'USD',
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
    style: 'currency',
  });
  const subDollarFormatter = new Intl.NumberFormat('en-US', {
    currency: 'USD',
    maximumFractionDigits: 4,
    minimumFractionDigits: 4,
    style: 'currency',
  });
  const fmtDateTime = (value: string): string => dateTimeFormatter.format(new Date(value));
  const fmtTokens = (value: number): string => compactNumberFormatter.format(value);
  const fmtEffort = (phase: Pick<SessionDetailPhase, 'effort' | 'effortKind'>): string =>
    phase.effort ?? (phase.effortKind === 'default' ? 'default effort' : 'effort not recorded');
  const formatCost = (phase: SessionDetailPhase): string => {
    if (phase.cost === null) {
      return 'price unknown';
    }
    const value = (phase.cost >= 1 ? moneyFormatter : subDollarFormatter).format(phase.cost);
    return phase.costKind === 'approximate' ? `≈ ${value}` : `${value} reported`;
  };
  const phaseKey = (phase: SessionDetailPhase): string => `${phase.model}\0${phase.effortKind}\0${phase.effort ?? ''}`;
  const phaseToneIndex = (phase: SessionDetailPhase, phases: readonly SessionDetailPhase[]): number =>
    Math.max(0, [...new Set(phases.map(phaseKey))].indexOf(phaseKey(phase))) % phaseToneClasses.length;
  const phaseTone = (phase: SessionDetailPhase, phases: readonly SessionDetailPhase[]): string =>
    phaseToneClasses[phaseToneIndex(phase, phases)] ?? phaseToneClasses[0];
  const preview = (text: string): string => {
    const normalized = text.replace(/\s+/g, ' ').trim();
    return normalized.length > 120 ? `${normalized.slice(0, 120).trimEnd()}…` : normalized;
  };
  const unavailableTitles = {
    'history-unavailable': 'Local history unavailable',
    'not-found': 'Local session history not found',
    'not-local': 'Local history required',
    'report-provenance-unavailable': 'Session provenance unavailable',
    'report-row-not-found': 'Session not found in report',
    'revision-expired': 'Report revision expired',
    unsupported: 'Analysis not supported',
  } as const;
  const available = $derived(response?.status === 'available' ? response : null);
  const unavailable = $derived(response?.status === 'unavailable' ? response : null);
  const liveAnnouncementFor = (): string => {
    if (analysisError) {
      return '';
    }
    if (loading) {
      return 'Loading session analysis';
    }
    if (unavailable) {
      return `${unavailableTitles[unavailable.reason]}. ${unavailable.message}`;
    }
    return available ? 'Session analysis loaded' : '';
  };
  const liveAnnouncement = $derived(liveAnnouncementFor());
  let scaleMode = $state<TimelineScaleMode>('compressed');
  const detail = $derived(available?.detail ?? null);
  const chronologicalPhases = $derived(
    detail ? [...detail.phases].sort((left, right) => Date.parse(left.startAt) - Date.parse(right.startAt)) : [],
  );
  const timelineRows = $derived(detail ? buildSessionTimelineRows(detail) : []);
  const durationSemantics = $derived(sessionDurationSemantics(harnessKey, target.kind === 'campaign-root'));
  const burstCount = $derived(detail ? countActivityBursts(detail.turns) : 0);
  const durationParts = $derived(detail ? sessionDurationCaption(detail, durationSemantics, burstCount) : []);
  const presentationItems = $derived(
    available
      ? buildSessionAnalysisPresentation({
          consistency: available.consistency,
          durationPartialBody: durationSemantics.partialBody,
          durationStatus: available.detail.durationStatus,
          promptDataTruncated:
            available.detail.promptsTruncated || available.detail.prompts.some((prompt) => prompt.truncated),
          target,
          turnsStatus: available.detail.turnsStatus,
        })
      : [],
  );
  const items = (kind: (typeof presentationItems)[number]['kind']) =>
    presentationItems.filter((item) => item.kind === kind);
  const scale = $derived(detail ? buildTimelineScale(detail, scaleMode) : null);
  const hasCompressibleGaps = $derived(detail ? timelineHasCompressibleGaps(detail) : false);
  const rowLabel = (row: Extract<SessionTimelineRow, { kind: 'task' }>): string =>
    preview(row.prompts[0]?.text ?? '') || `${durationSemantics.rowNoun} ${row.index + 1}`;
  const rowDuration = (row: Extract<SessionTimelineRow, { kind: 'task' }>): string =>
    row.durationMs === null ? 'Recorded duration unavailable' : formatSessionDuration(row.durationMs);
  const taskTone = (row: Extract<SessionTimelineRow, { kind: 'task' }>): number | undefined => {
    if (chronologicalPhases.length < 2) {
      return;
    }
    const timestamp = Date.parse(row.intervals[0]?.startAt ?? row.startAt);
    const phase = chronologicalPhases.find(
      (candidate) => timestamp >= Date.parse(candidate.startAt) && timestamp <= Date.parse(candidate.endAt),
    );
    return phase ? phaseToneIndex(phase, chronologicalPhases) : undefined;
  };
  const boundPrefix = (bound: 'lower' | 'upper' | null): string => {
    if (bound === 'lower') {
      return '≥ ';
    }
    return bound === 'upper' ? '≤ ' : '';
  };
  const stateTitleFor = (): string => {
    if (analysisError) {
      return analysisError.kind === 'transient' ? 'Analysis failed' : 'Analysis unavailable';
    }
    return unavailable ? unavailableTitles[unavailable.reason] : 'No analysis loaded';
  };
  const stateTitle = $derived(stateTitleFor());
  const stateMessage = $derived(
    analysisError?.message ?? unavailable?.message ?? 'Select a locally recorded session to inspect its timeline.',
  );
  const canRetry = $derived(
    Boolean(onRetry && (analysisError?.kind === 'transient' || unavailable?.reason === 'history-unavailable')),
  );
</script>

<section aria-label="Session analysis" class={panel}>
  <div aria-atomic="true" aria-live="polite" class={visuallyHidden} data-session-analysis-live-status role="status">
    {liveAnnouncement}
  </div>
  {#if analysisError}
    <div role="alert">
      <div class={statePanel}>
        <div class={stateTitle}>{stateTitle}</div>
        <div>{stateMessage}</div>
        {#if canRetry}
          <button class={retryButton} onclick={() => onRetry?.()} type="button">Retry</button>
        {/if}
      </div>
    </div>
  {:else if loading}
    <div aria-busy="true" class={statePanel}>
      <div class={stateTitle}>Loading session analysis</div>
      <div>Reading the bounded local session trace…</div>
    </div>
  {:else if unavailable}
    <div class={statePanel}>
      <div class={stateTitle}>{stateTitle}</div>
      <div>{stateMessage}</div>
      {#if canRetry}
        <button class={retryButton} onclick={() => onRetry?.()} type="button">Retry</button>
      {/if}
    </div>
  {:else if available && detail && scale}
    <div class={panel}>
      <header class={header}>
        <h2 class={heading}>Session analysis</h2>
        <div class={muted}>
          <time datetime={detail.startedAt}>{fmtDateTime(detail.startedAt)}</time>
          →
          <time datetime={detail.endedAt}>{fmtDateTime(detail.endedAt)}</time>
          · session
          <span class={numeric}>{detail.sourceSessionId}</span>
        </div>
        {#each items('consistency-meta') as item (item.text)}
          <div class={muted} data-session-analysis-item={item.kind} data-tone={item.tone}>{item.text}</div>
        {/each}
        {#each items('scope') as item (item.text)}
          <div class={muted} data-session-analysis-item={item.kind} data-tone={item.tone}>{item.text}</div>
        {/each}
        {#each items('consistency-warning') as item (item.text)}
          <div
            class={cx(notice, warningNotice)}
            data-session-analysis-item={item.kind}
            data-tone={item.tone}
            role="status"
          >
            {item.text}
          </div>
        {/each}
      </header>

      <section aria-labelledby="session-timeline" class={section}>
        <div class={sectionHeader}>
          <h3 class={sectionHeading} id="session-timeline">{durationSemantics.timelineHeading}</h3>
          <div class={durationCaption}>
            {#each durationParts as part, index (part.key)}
              <span class={durationCaptionPart} data-session-analysis-metric={part.key} title={part.hint}>
                {#if index > 0}
                  ·
                {/if}
                {part.label}
                {#if part.bound}
                  <span class={visuallyHidden}>{part.bound === 'lower' ? 'At least ' : 'At most '}</span>
                  <span aria-hidden="true">{boundPrefix(part.bound)}</span>
                {/if}
                {part.value}
              </span>
            {/each}
          </div>
          {#each ['partial-duration', 'partial-turns', 'privacy', 'prompt-truncation'] as kind}
            {#each items(kind as (typeof presentationItems)[number]['kind']) as item (item.text)}
              {#if item.tone === 'warning'}
                <div
                  class={cx(notice, warningNotice)}
                  data-session-analysis-item={item.kind}
                  data-tone={item.tone}
                  role="status"
                >
                  {item.text}
                </div>
              {:else}
                <div class={muted} data-session-analysis-item={item.kind} data-tone={item.tone}>
                  {item.text}
                </div>
              {/if}
            {/each}
          {/each}
          <div class={muted}>{durationSemantics.timelineDescription}</div>
          {#if hasCompressibleGaps}
            <button
              aria-label="Show real gaps"
              aria-pressed={scaleMode === 'wall-clock' ? 'true' : 'false'}
              class={scaleButton}
              onclick={() => { scaleMode = scaleMode === 'compressed' ? 'wall-clock' : 'compressed'; }}
              type="button"
            >
              {scaleMode === 'compressed' ? 'Show real gaps' : 'Compress gaps'}
            </button>
          {/if}
        </div>

        {#if timelineRows.length === 0}
          <div class={empty}>
            No turn intervals were available in local history. No prompt text was available in local history.
          </div>
        {:else}
          <div class={timelineShell} data-session-analysis-scale={scaleMode}>
            <div class={timelineAxis}>
              <span aria-hidden="true"></span>
              <div class={axisTrack}>
                <div class={axisLabels}>
                  <time datetime={detail.startedAt}>{fmtDateTime(detail.startedAt)}</time>
                  <span aria-hidden="true">{scaleMode === 'compressed' ? 'Compressed gaps' : 'Wall-clock time'}</span>
                  <time datetime={detail.endedAt}>{fmtDateTime(detail.endedAt)}</time>
                </div>
                {#each scale.breaks as scaleBreak (scaleBreak.atPercent)}
                  <span
                    aria-hidden="true"
                    class={scaleBreakClass}
                    title={formatSessionDuration(scaleBreak.gapMs)}
                    style:left={`${scaleBreak.atPercent}%`}
                    >⫽</span
                  >
                {/each}
              </div>
              <span>Tokens</span>
            </div>
            <ol aria-label="Chronological session tasks and prompts" class={timelineList}>
              {#each timelineRows as row (`${row.kind}:${row.kind === 'task' ? row.index : row.prompt.id}`)}
                {#if row.kind === 'task'}
                  {@const tone = taskTone(row)}
                  {@const label = rowLabel(row)}
                  <li class={timelineRow} data-session-analysis-row="task">
                    <details class={promptDisclosure}>
                      <summary class={promptSummary}>
                        <span aria-hidden="true">▶</span>
                        <span>
                          <span>{row.prompts[0] ? `Prompt: ${label}` : label}</span>
                          <span class={muted} title={durationSemantics.metricHint}> {rowDuration(row)}</span>
                          <span class={timelineMeta}>
                            {#if chronologicalPhases.length > 1}
                              {row.model}
                              · {fmtEffort(row)} ·
                            {/if}
                            {fmtTokens(row.tokens.total)} {row.tokens.total === 1 ? 'token' : 'tokens'} ·
                            {countLabel(row.tools, 'tool')}
                            · {countLabel(row.prompts.length, 'prompt')}
                          </span>
                        </span>
                      </summary>
                      <div class={promptBody}>
                        {#if row.prompts.length === 0}
                          <span class={muted}>No prompt text was available in local history.</span>
                        {/if}
                        {#each row.prompts as prompt (prompt.id)}
                          <div>
                            <time class={muted} datetime={prompt.timestamp}>{fmtDateTime(prompt.timestamp)}</time>
                            {#if prompt.truncated}
                              <span class={pill}>Truncated</span>
                            {/if}
                            <div>{prompt.text}</div>
                          </div>
                        {/each}
                      </div>
                    </details>
                    <div
                      aria-label={`${label}, ${row.model}, ${fmtEffort(row)}, ${rowDuration(row)} across ${countLabel(row.intervals.length, 'segment')}, ${countLabel(row.tokens.total, 'token')}, ${countLabel(row.tools, 'tool')} and ${countLabel(row.prompts.length, 'prompt')}`}
                      class={cx(timelineTrack, scaleMode === 'wall-clock' && wallClockTrack)}
                      role="img"
                    >
                      {#each row.intervals as interval (`${interval.startAt}:${interval.endAt}`)}
                        {@const position = positionOnScale(scale, interval.startAt, interval.endAt)}
                        <span
                          aria-hidden="true"
                          class={cx(timelineBar, tone === undefined ? turnBar : phaseToneClasses[tone])}
                          data-session-analysis-phase-tone={tone}
                          style:left={`${position.leftPercent}%`}
                          style:width={`${position.widthPercent}%`}
                        ></span>
                      {/each}
                      {#if row.intervals.length === 0}
                        {@const position = positionOnScale(scale, row.startAt, row.startAt)}
                        <span
                          aria-hidden="true"
                          class={pointMarker}
                          data-session-analysis-point
                          style:left={`${position.leftPercent}%`}
                        ></span>
                      {/if}
                    </div>
                    <div class={tokenCell}>
                      <span aria-hidden="true" class={tokenTrack}
                        ><span class={tokenBar} style:width={`${row.tokenShareOfMax * 100}%`}></span></span
                      ><span class={tokenValue}>{fmtTokens(row.tokens.total)}</span>
                    </div>
                  </li>
                {:else}
                  {@const label = preview(row.prompt.text) || 'Prompt'}
                  {@const position = positionOnScale(scale, row.prompt.timestamp, row.prompt.timestamp)}
                  <li class={timelineRow} data-session-analysis-row="orphan-prompt">
                    <details class={promptDisclosure}>
                      <summary class={promptSummary}>
                        <span aria-hidden="true">▶</span
                        ><span
                          >Prompt: {label}<span class={timelineMeta}> · prompt without task attribution</span></span
                        >
                      </summary>
                      <div class={promptBody}>{row.prompt.text}</div>
                    </details>
                    <div
                      aria-label={`${label}, orphan prompt, 0s ${durationSemantics.turnSpanNoun}, tokens unavailable, 0 tools, point event with no task attribution`}
                      class={timelineTrack}
                      role="img"
                    >
                      <span
                        aria-hidden="true"
                        class={pointMarker}
                        data-session-analysis-point
                        style:left={`${position.leftPercent}%`}
                      ></span>
                    </div>
                    <span class={tokenCell}><span class={tokenValue}>—</span></span>
                  </li>
                {/if}
              {/each}
            </ol>
          </div>
        {/if}
      </section>

      {#if chronologicalPhases.length > 1}
        <section aria-labelledby="session-model-phases" class={section}>
          <h3 class={sectionHeading} id="session-model-phases">Model and effort phases</h3>
          <div class={timelineShell}>
            <ol aria-label="Chronological model and effort phases" class={timelineList}>
              {#each chronologicalPhases as phase (phaseKey(phase))}
                {@const position = positionOnScale(scale, phase.startAt, phase.endAt)}
                <li class={timelineRow}>
                  <div>
                    <span aria-hidden="true" class={cx(phaseDot, phaseTone(phase, chronologicalPhases))}></span>
                    {phase.model}
                    <div class={timelineMeta}>
                      {fmtEffort(phase)}
                      · {phaseTokenShare(phase, chronologicalPhases).toFixed(1)}% tokens · {formatCost(phase)}
                    </div>
                  </div>
                  <div
                    aria-label={`${phase.model}, ${fmtEffort(phase)}, ${formatCost(phase)}`}
                    class={timelineTrack}
                    role="img"
                  >
                    <span
                      aria-hidden="true"
                      class={cx(timelineBar, phaseTone(phase, chronologicalPhases))}
                      style:left={`${position.leftPercent}%`}
                      style:width={`${position.widthPercent}%`}
                    ></span>
                  </div>
                  <span></span>
                </li>
              {/each}
            </ol>
          </div>
        </section>
      {:else if chronologicalPhases[0]}
        <div class={cx(muted, phaseLegend)}>
          <span aria-hidden="true" class={cx(phaseDot, phaseTone(chronologicalPhases[0], chronologicalPhases))}></span>
          <span
            >{chronologicalPhases[0].model}
            · {fmtEffort(chronologicalPhases[0])} · 100% tokens · {formatCost(chronologicalPhases[0])}</span
          >
        </div>
      {/if}
      <div class={muted}>
        Detail observed <time datetime={detail.observedAt}>{fmtDateTime(detail.observedAt)}</time> from local history.
      </div>
    </div>
  {:else}
    <div class={statePanel}>
      <div class={stateTitle}>No analysis loaded</div>
      <div>{stateMessage}</div>
    </div>
  {/if}
</section>

// apps/web/src/session-analysis.tsx
import { css, cx } from '@ai-usage/design-system/css';
import type {
  SessionDetail,
  SessionDetailConsistency,
  SessionDetailPhase,
  SessionDetailResponse,
  SessionDetailTurn,
} from '@ai-usage/report-core/session-detail';
import { createMemo, For, Match, Show, Switch } from 'solid-js';
import type { SessionAnalysisError } from './session-analysis-error';
import {
  countActivityBursts,
  formatSessionDuration,
  phaseTokenShare,
  positionOnTimeline,
  type SessionDurationSemantics,
  sessionDurationSemantics,
} from './session-analysis-model';
import {
  buildSessionAnalysisPresentation,
  type SessionAnalysisPresentationItem,
} from './session-analysis-presentation';
import type { SessionAnalysisTarget } from './session-analysis-target';

export interface SessionAnalysisProps {
  error?: SessionAnalysisError | null;
  harnessKey: string;
  loading: boolean;
  onRetry?: () => void;
  response: SessionDetailResponse | null;
  target: SessionAnalysisTarget;
}

type SessionMetricBound = 'lower' | 'upper' | null;

interface SessionMetricItem {
  bound: SessionMetricBound;
  hint: string;
  label: string;
  value: string;
}

const dateTimeFormatter = new Intl.DateTimeFormat('en', {
  day: '2-digit',
  hour: '2-digit',
  hourCycle: 'h23',
  minute: '2-digit',
  month: 'short',
});
const compactNumberFormatter = new Intl.NumberFormat('en', {
  maximumFractionDigits: 1,
  notation: 'compact',
});
const moneyFormatter = new Intl.NumberFormat('en-US', {
  currency: 'USD',
  maximumFractionDigits: 4,
  minimumFractionDigits: 2,
  style: 'currency',
});
const COLLAPSE_WHITESPACE = /\s+/g;
const PROMPT_PREVIEW_LENGTH = 120;

const panel = css({ display: 'grid', gap: '20px', minW: 0, w: 'full' });
const header = css({ display: 'grid', gap: '5px' });
const heading = css({ color: 'ink', fontSize: '18px', fontWeight: 700, lineHeight: 1.25, m: 0 });
const sectionHeading = css({ color: 'ink', fontSize: '14px', fontWeight: 700, lineHeight: 1.3, m: 0 });
const muted = css({ color: 'muted', fontSize: '12px', lineHeight: 1.5 });
const numeric = css({ fontFamily: 'mono', fontVariantNumeric: 'tabular-nums' });
const section = css({ display: 'grid', gap: '12px', minW: 0 });
const sectionHeader = css({ display: 'grid', gap: '3px' });
const metrics = css({
  display: 'grid',
  gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' },
  gap: '8px',
  m: 0,
});
const metric = css({
  display: 'grid',
  gap: '5px',
  minW: 0,
  p: '12px',
  border: '1px solid token(colors.line)',
  borderRadius: 'md',
  bg: 'surfaceMuted',
});
const metricLabel = css({ color: 'muted', fontSize: '11px', fontWeight: 650, textTransform: 'uppercase' });
const metricValue = css({
  color: 'ink',
  fontFamily: 'mono',
  fontSize: { base: '17px', md: '20px' },
  fontVariantNumeric: 'tabular-nums',
  fontWeight: 700,
  lineHeight: 1.1,
  m: 0,
});
const notice = css({
  display: 'grid',
  gap: '4px',
  p: '10px 12px',
  border: '1px solid token(colors.line)',
  borderRadius: 'sm',
  bg: 'accentTint',
  color: 'ink',
  fontSize: '12px',
  lineHeight: 1.5,
});
const warningNotice = css({ bg: 'status.warnSoft', borderColor: 'status.warn', color: 'ink' });
const timelineShell = css({
  display: 'grid',
  gap: '8px',
  minW: 0,
  p: { base: '10px', md: '12px' },
  border: '1px solid token(colors.line)',
  borderRadius: 'md',
  bg: 'surfaceMuted',
});
const timelineAxis = css({
  display: 'grid',
  gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'minmax(152px, 0.36fr) minmax(0, 1fr)' },
  gap: '12px',
  alignItems: 'end',
});
const timelineAxisSpacer = css({ display: { base: 'none', md: 'block' } });
const axisLabels = css({
  display: 'flex',
  justifyContent: 'space-between',
  gap: '10px',
  color: 'faint',
  fontFamily: 'mono',
  fontSize: '10px',
  fontVariantNumeric: 'tabular-nums',
});
const timelineList = css({ display: 'grid', gap: '7px', listStyle: 'none', m: 0, p: 0 });
const timelineRow = css({
  display: 'grid',
  gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'minmax(152px, 0.36fr) minmax(0, 1fr)' },
  gap: { base: '5px', md: '12px' },
  alignItems: 'center',
  minW: 0,
});
const timelineLabel = css({ display: 'grid', gap: '2px', minW: 0 });
const timelineLabelTop = css({
  display: 'flex',
  gap: '6px',
  alignItems: 'center',
  minW: 0,
  color: 'ink',
  fontSize: '12px',
  fontWeight: 650,
});
const timelineLabelText = css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
const timelineMeta = css({ color: 'muted', fontSize: '10px', lineHeight: 1.4, overflowWrap: 'anywhere' });
const timelineTrack = css({
  position: 'relative',
  h: '20px',
  minW: 0,
  overflow: 'hidden',
  border: '1px solid token(colors.line)',
  borderRadius: 'sm',
  bg: 'track',
  backgroundImage:
    'linear-gradient(to right, transparent 24.8%, token(colors.line) 25%, transparent 25.2%, transparent 49.8%, token(colors.line) 50%, transparent 50.2%, transparent 74.8%, token(colors.line) 75%, transparent 75.2%)',
});
const timelineBar = css({
  position: 'absolute',
  top: '3px',
  bottom: '3px',
  minW: '4px',
  borderRadius: '4px',
});
const turnBar = css({ bg: 'accent', boxShadow: '0 0 0 1px token(colors.focusRing)' });
const phaseDot = css({ flex: '0 0 auto', w: '8px', h: '8px', borderRadius: 'full' });
const phaseToneClasses = [
  css({ bg: 'chart.c1' }),
  css({ bg: 'chart.c2' }),
  css({ bg: 'chart.c3' }),
  css({ bg: 'chart.c4' }),
  css({ bg: 'chart.c5' }),
  css({ bg: 'chart.c6' }),
] as const;
const empty = css({
  p: '14px',
  border: '1px dashed token(colors.lineStrong)',
  borderRadius: 'md',
  color: 'muted',
  fontSize: '12px',
  textAlign: 'center',
});
const promptList = css({ display: 'grid', gap: '8px' });
const promptDisclosure = css({
  overflow: 'hidden',
  border: '1px solid token(colors.line)',
  borderRadius: 'md',
  bg: 'surfaceMuted',
});
const promptSummary = css({
  display: 'grid',
  gridTemplateColumns: 'auto minmax(0, 1fr) auto',
  gap: '9px',
  alignItems: 'center',
  p: '10px 12px',
  color: 'ink',
  cursor: 'pointer',
  listStyle: 'none',
  fontSize: '12px',
  '&::-webkit-details-marker': { display: 'none' },
  _hover: { bg: 'accentTint' },
  _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '-2px' },
});
const promptChevron = css({ color: 'accent', fontSize: '11px', '[open] &': { transform: 'rotate(90deg)' } });
const promptPreview = css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' });
const promptSummaryMeta = css({ display: 'flex', gap: '7px', alignItems: 'center', whiteSpace: 'nowrap' });
const pill = css({
  px: '7px',
  py: '2px',
  borderRadius: 'full',
  bg: 'status.warnSoft',
  color: 'status.warn',
  fontSize: '10px',
  fontWeight: 700,
  whiteSpace: 'nowrap',
});
const promptBody = css({
  p: '12px',
  borderTop: '1px solid token(colors.line)',
  bg: 'surface',
  color: 'ink',
  fontFamily: 'mono',
  fontSize: '11px',
  lineHeight: 1.6,
  overflowWrap: 'anywhere',
  whiteSpace: 'pre-wrap',
});
const statePanel = css({
  display: 'grid',
  placeItems: 'center',
  gap: '10px',
  minH: '220px',
  p: '24px',
  border: '1px solid token(colors.line)',
  borderRadius: 'md',
  bg: 'surfaceMuted',
  color: 'muted',
  textAlign: 'center',
});
const stateTitle = css({ color: 'ink', fontSize: '15px', fontWeight: 700 });
const visuallyHidden = css({ srOnly: true });
const retryButton = css({
  px: '12px',
  py: '7px',
  border: '1px solid token(colors.lineStrong)',
  borderRadius: 'sm',
  bg: 'surface',
  color: 'ink',
  cursor: 'pointer',
  fontSize: '12px',
  fontWeight: 650,
  _hover: { borderColor: 'accent', color: 'accent' },
  _focusVisible: { outline: '2px solid token(colors.accent)', outlineOffset: '2px' },
});

const fmtDateTime = (value: string): string => dateTimeFormatter.format(new Date(value));
const fmtTokens = (tokens: number): string => compactNumberFormatter.format(tokens);
const fmtShare = (share: number): string => `${share >= 10 ? share.toFixed(0) : share.toFixed(1)}%`;
const fmtEffort = (effort: string | null, effortKind: SessionDetailPhase['effortKind']): string => {
  if (effort !== null) {
    return effort;
  }
  return effortKind === 'default' ? 'default effort' : 'effort not recorded';
};
const phaseKey = (phase: SessionDetailPhase): string =>
  `${phase.model}\u0000${phase.effortKind}\u0000${phase.effort ?? ''}`;
const phaseTone = (phase: SessionDetailPhase, phases: readonly SessionDetailPhase[]): string => {
  const uniqueKeys = [...new Set(phases.map(phaseKey))];
  const index = Math.max(0, uniqueKeys.indexOf(phaseKey(phase)));
  return phaseToneClasses[index % phaseToneClasses.length] ?? phaseToneClasses[0];
};
const promptPreviewText = (text: string): string => {
  const normalized = text.replace(COLLAPSE_WHITESPACE, ' ').trim();
  return normalized.length > PROMPT_PREVIEW_LENGTH
    ? `${normalized.slice(0, PROMPT_PREVIEW_LENGTH).trimEnd()}…`
    : normalized;
};

const TimelineAxis = (props: { endedAt: string; startedAt: string }) => (
  <div class={timelineAxis}>
    <span aria-hidden="true" class={timelineAxisSpacer} />
    <div class={axisLabels}>
      <time dateTime={props.startedAt}>{fmtDateTime(props.startedAt)}</time>
      <span aria-hidden="true">Wall-clock time</span>
      <time dateTime={props.endedAt}>{fmtDateTime(props.endedAt)}</time>
    </div>
  </div>
);

const PhaseRow = (props: { detail: SessionDetail; phase: SessionDetailPhase }) => {
  const position = createMemo(() =>
    positionOnTimeline(props.phase.startAt, props.phase.endAt, props.detail.startedAt, props.detail.endedAt),
  );
  const share = createMemo(() => phaseTokenShare(props.phase, props.detail.phases));
  const effort = () => fmtEffort(props.phase.effort, props.phase.effortKind);
  const cost = () => {
    if (props.phase.cost === null) {
      return 'price unknown';
    }
    const formatted = moneyFormatter.format(props.phase.cost);
    return props.phase.costKind === 'approximate' ? `≈ ${formatted}` : `${formatted} reported`;
  };
  const accessibleLabel = () =>
    `${props.phase.model}, ${effort()}, ${fmtShare(share())} of tokens, ${cost()}, from ${fmtDateTime(props.phase.startAt)} to ${fmtDateTime(props.phase.endAt)}`;

  return (
    <li class={timelineRow}>
      <div class={timelineLabel}>
        <div class={timelineLabelTop}>
          <span aria-hidden="true" class={cx(phaseDot, phaseTone(props.phase, props.detail.phases))} />
          <span class={timelineLabelText} title={props.phase.model}>
            {props.phase.model}
          </span>
        </div>
        <div class={timelineMeta}>
          {effort()} · {fmtShare(share())} tokens · {cost()}
        </div>
      </div>
      <div aria-label={accessibleLabel()} class={timelineTrack} role="img">
        <span
          aria-hidden="true"
          class={cx(timelineBar, phaseTone(props.phase, props.detail.phases))}
          style={{ left: `${position().leftPercent}%`, width: `${position().widthPercent}%` }}
        />
      </div>
    </li>
  );
};

const TurnRow = (props: {
  detail: SessionDetail;
  durationSemantics: SessionDurationSemantics;
  turn: SessionDetailTurn;
}) => {
  const positions = createMemo(() =>
    props.turn.intervals.map((interval) =>
      positionOnTimeline(interval.startAt, interval.endAt, props.detail.startedAt, props.detail.endedAt),
    ),
  );
  const effort = () => fmtEffort(props.turn.effort, props.turn.effortKind);
  const accessibleLabel = () =>
    `Turn ${props.turn.index + 1}, ${props.turn.model}, ${effort()}, ${formatSessionDuration(props.turn.durationMs)} ${props.durationSemantics.turnSpanNoun} across ${props.turn.intervals.length} segments, ${fmtTokens(props.turn.tokens.total)} tokens, ${props.turn.tools} tools and ${props.turn.promptIds.length} prompts, from ${fmtDateTime(props.turn.startAt)} to ${fmtDateTime(props.turn.endAt)}`;

  return (
    <li class={timelineRow}>
      <div class={timelineLabel}>
        <div class={timelineLabelTop}>
          <span class={timelineLabelText}>Turn {props.turn.index + 1}</span>
          <span class={muted} title={props.durationSemantics.metricHint}>
            {formatSessionDuration(props.turn.durationMs)}
          </span>
        </div>
        <div class={timelineMeta} title={`${props.turn.model} · ${effort()}`}>
          {props.turn.model} · {effort()} · {fmtTokens(props.turn.tokens.total)} tokens · {props.turn.tools} tools ·{' '}
          {props.turn.promptIds.length} prompts
        </div>
      </div>
      <div aria-label={accessibleLabel()} class={timelineTrack} role="img">
        <For each={positions()}>
          {(position) => (
            <span
              aria-hidden="true"
              class={cx(timelineBar, turnBar)}
              style={{ left: `${position.leftPercent}%`, width: `${position.widthPercent}%` }}
            />
          )}
        </For>
      </div>
    </li>
  );
};

const EmptyTimeline = (props: { children: string }) => <div class={empty}>{props.children}</div>;

const MetricValue = (props: { bound: SessionMetricBound; value: string }) => (
  <dd class={metricValue}>
    <Show when={props.bound !== null}>
      <span class={visuallyHidden}>{props.bound === 'lower' ? 'At least ' : 'At most '}</span>
      <span aria-hidden="true">{props.bound === 'lower' ? '≥ ' : '≤ '}</span>
    </Show>
    {props.value}
  </dd>
);

const PresentationItem = (props: { item: SessionAnalysisPresentationItem }) => (
  <div
    class={props.item.tone === 'warning' ? cx(notice, warningNotice) : muted}
    data-session-analysis-item={props.item.kind}
    data-tone={props.item.tone}
    role={props.item.tone === 'warning' ? 'status' : undefined}
  >
    <span>{props.item.text}</span>
  </div>
);

const AvailableSessionAnalysis = (props: {
  consistency: SessionDetailConsistency;
  detail: SessionDetail;
  harnessKey: string;
  target: SessionAnalysisTarget;
}) => {
  const chronologicalPhases = createMemo(() =>
    [...props.detail.phases].sort((left, right) => Date.parse(left.startAt) - Date.parse(right.startAt)),
  );
  const chronologicalTurns = createMemo(() =>
    [...props.detail.turns].sort(
      (left, right) => Date.parse(left.startAt) - Date.parse(right.startAt) || left.index - right.index,
    ),
  );
  const chronologicalPrompts = createMemo(() =>
    [...props.detail.prompts].sort((left, right) => Date.parse(left.timestamp) - Date.parse(right.timestamp)),
  );
  const burstCount = createMemo(() => countActivityBursts(props.detail.turns));
  const promptDataTruncated = createMemo(
    () => props.detail.promptsTruncated || props.detail.prompts.some(({ truncated }) => truncated),
  );
  const durationSemantics = createMemo(() =>
    sessionDurationSemantics(props.harnessKey, props.target.kind === 'campaign-root'),
  );
  const presentationItems = createMemo(() =>
    buildSessionAnalysisPresentation({
      consistency: props.consistency,
      durationPartialBody: durationSemantics().partialBody,
      durationStatus: props.detail.durationStatus,
      promptDataTruncated: promptDataTruncated(),
      target: props.target,
      turnsStatus: props.detail.turnsStatus,
    }),
  );
  const itemsOfKind = (kind: SessionAnalysisPresentationItem['kind']) =>
    presentationItems().filter((item) => item.kind === kind);

  const metricItems = (): SessionMetricItem[] => [
    {
      bound: props.detail.durationStatus === 'partial' ? 'lower' : null,
      hint: durationSemantics().metricHint,
      label: durationSemantics().metricLabel,
      value: formatSessionDuration(props.detail.activeDurationMs),
    },
    {
      bound: null,
      hint: durationSemantics().elapsedHint,
      label: durationSemantics().elapsedLabel,
      value: formatSessionDuration(props.detail.elapsedDurationMs),
    },
    {
      bound: props.detail.durationStatus === 'partial' ? 'upper' : null,
      hint: durationSemantics().gapHint,
      label: durationSemantics().gapLabel,
      value: formatSessionDuration(props.detail.idleDurationMs),
    },
    {
      bound: null,
      hint: durationSemantics().burstHint,
      label: durationSemantics().burstLabel,
      value: String(burstCount()),
    },
  ];

  return (
    <div class={panel}>
      <header class={header}>
        <h2 class={heading}>Session analysis</h2>
        <div class={muted}>
          <time dateTime={props.detail.startedAt}>{fmtDateTime(props.detail.startedAt)}</time>
          {' → '}
          <time dateTime={props.detail.endedAt}>{fmtDateTime(props.detail.endedAt)}</time>
          {' · '}session <span class={numeric}>{props.detail.sourceSessionId}</span>
        </div>
        <For each={itemsOfKind('consistency-meta')}>{(item) => <PresentationItem item={item} />}</For>
        <For each={itemsOfKind('scope')}>{(item) => <PresentationItem item={item} />}</For>
      </header>

      <For each={itemsOfKind('consistency-warning')}>{(item) => <PresentationItem item={item} />}</For>

      <div class={section}>
        <dl class={metrics}>
          <For each={metricItems()}>
            {(item) => (
              <div class={metric} title={item.hint}>
                <dt class={metricLabel}>{item.label}</dt>
                <MetricValue bound={item.bound} value={item.value} />
              </div>
            )}
          </For>
        </dl>
        <For each={itemsOfKind('partial-duration')}>{(item) => <PresentationItem item={item} />}</For>
      </div>

      <section aria-labelledby="session-model-phases" class={section}>
        <div class={sectionHeader}>
          <h3 class={sectionHeading} id="session-model-phases">
            Model and effort phases
          </h3>
          <div class={muted}>Band position follows wall-clock time; percentages show each phase's token share.</div>
        </div>
        <Show
          fallback={<EmptyTimeline>No model or effort changes were recorded for this session.</EmptyTimeline>}
          when={chronologicalPhases().length > 0}
        >
          <div class={timelineShell}>
            <TimelineAxis endedAt={props.detail.endedAt} startedAt={props.detail.startedAt} />
            <ol aria-label="Chronological model and effort phases" class={timelineList}>
              <For each={chronologicalPhases()}>{(phase) => <PhaseRow detail={props.detail} phase={phase} />}</For>
            </ol>
          </div>
        </Show>
      </section>

      <section aria-labelledby="session-turn-timeline" class={section}>
        <div class={sectionHeader}>
          <h3 class={sectionHeading} id="session-turn-timeline">
            {durationSemantics().timelineHeading}
          </h3>
          <div class={muted}>{durationSemantics().timelineDescription}</div>
        </div>
        <Show
          fallback={<EmptyTimeline>No turn intervals were available in local history.</EmptyTimeline>}
          when={chronologicalTurns().length > 0}
        >
          <div class={timelineShell}>
            <TimelineAxis endedAt={props.detail.endedAt} startedAt={props.detail.startedAt} />
            <ol aria-label="Chronological session turns" class={timelineList}>
              <For each={chronologicalTurns()}>
                {(turn) => <TurnRow detail={props.detail} durationSemantics={durationSemantics()} turn={turn} />}
              </For>
            </ol>
          </div>
        </Show>
      </section>

      <section aria-labelledby="session-prompts" class={section}>
        <div class={sectionHeader}>
          <h3 class={sectionHeading} id="session-prompts">
            Prompts ({chronologicalPrompts().length})
          </h3>
          <div class={muted}>Prompt bodies are collapsed by default.</div>
          <For each={itemsOfKind('partial-turns')}>{(item) => <PresentationItem item={item} />}</For>
          <For each={itemsOfKind('privacy')}>{(item) => <PresentationItem item={item} />}</For>
        </div>
        <For each={itemsOfKind('prompt-truncation')}>{(item) => <PresentationItem item={item} />}</For>
        <Show
          fallback={<EmptyTimeline>No prompt text was available in local history.</EmptyTimeline>}
          when={chronologicalPrompts().length > 0}
        >
          <div class={promptList}>
            <For each={chronologicalPrompts()}>
              {(prompt) => (
                <details class={promptDisclosure}>
                  <summary class={promptSummary}>
                    <span aria-hidden="true" class={promptChevron}>
                      ▶
                    </span>
                    <span class={promptPreview}>{promptPreviewText(prompt.text)}</span>
                    <span class={promptSummaryMeta}>
                      <time class={muted} dateTime={prompt.timestamp}>
                        {fmtDateTime(prompt.timestamp)}
                      </time>
                      <Show when={prompt.truncated}>
                        <span class={pill}>Truncated</span>
                      </Show>
                    </span>
                  </summary>
                  <div class={promptBody}>
                    <div class={muted}>
                      <time dateTime={prompt.timestamp}>{fmtDateTime(prompt.timestamp)}</time>
                    </div>
                    {prompt.text}
                  </div>
                </details>
              )}
            </For>
          </div>
        </Show>
        <div class={muted}>
          Detail observed <time dateTime={props.detail.observedAt}>{fmtDateTime(props.detail.observedAt)}</time> from
          local history.
        </div>
      </section>
    </div>
  );
};

const StatePanel = (props: {
  actionLabel?: string | undefined;
  busy?: boolean;
  message: string;
  onAction?: (() => void) | undefined;
  title: string;
}) => (
  <div aria-busy={props.busy} class={statePanel}>
    <div class={stateTitle}>{props.title}</div>
    <div>{props.message}</div>
    <Show when={props.actionLabel && props.onAction}>
      <button class={retryButton} onClick={() => props.onAction?.()} type="button">
        {props.actionLabel}
      </button>
    </Show>
  </div>
);

type UnavailableResponse = Extract<SessionDetailResponse, { status: 'unavailable' }>;

const unavailablePresentation = {
  'history-unavailable': { retryable: true, title: 'Local history unavailable' },
  'not-found': { retryable: false, title: 'Local session history not found' },
  'not-local': { retryable: false, title: 'Local history required' },
  'report-provenance-unavailable': { retryable: false, title: 'Session provenance unavailable' },
  'report-row-not-found': { retryable: false, title: 'Session not found in report' },
  'revision-expired': { retryable: false, title: 'Report revision expired' },
  unsupported: { retryable: false, title: 'Analysis not supported' },
} as const satisfies Record<UnavailableResponse['reason'], { retryable: boolean; title: string }>;

export const SessionAnalysis = (props: SessionAnalysisProps) => {
  const unavailable = createMemo(() => {
    const response = props.response;
    if (response?.status !== 'unavailable') {
      return null;
    }
    return { ...response, ...unavailablePresentation[response.reason] };
  });
  const available = createMemo(() => (props.response?.status === 'available' ? props.response : null));
  const liveAnnouncement = createMemo(() => {
    if (props.error) {
      return '';
    }
    if (props.loading) {
      return 'Loading session analysis';
    }
    const unavailableState = unavailable();
    if (unavailableState) {
      return `${unavailableState.title}. ${unavailableState.message}`;
    }
    if (available()) {
      return 'Session analysis loaded';
    }
    return '';
  });

  return (
    <section aria-label="Session analysis" class={panel}>
      <div aria-atomic="true" aria-live="polite" class={visuallyHidden} data-session-analysis-live-status role="status">
        {liveAnnouncement()}
      </div>
      <Switch>
        <Match when={props.error}>
          {(error) => (
            <div role="alert">
              <StatePanel
                actionLabel={error().kind === 'transient' && props.onRetry ? 'Retry' : undefined}
                message={error().message}
                onAction={error().kind === 'transient' ? props.onRetry : undefined}
                title={error().kind === 'transient' ? 'Analysis failed' : 'Analysis unavailable'}
              />
            </div>
          )}
        </Match>
        <Match when={props.loading}>
          <StatePanel busy message="Reading the bounded local session trace…" title="Loading session analysis" />
        </Match>
        <Match when={unavailable()}>
          {(state) => (
            <StatePanel
              actionLabel={state().retryable && props.onRetry ? 'Retry' : undefined}
              message={state().message}
              onAction={state().retryable ? props.onRetry : undefined}
              title={state().title}
            />
          )}
        </Match>
        <Match when={available()}>
          {(response) => (
            <AvailableSessionAnalysis
              consistency={response().consistency}
              detail={response().detail}
              harnessKey={props.harnessKey}
              target={props.target}
            />
          )}
        </Match>
        <Match when={true}>
          <StatePanel message="Select a locally recorded session to inspect its timeline." title="No analysis loaded" />
        </Match>
      </Switch>
    </section>
  );
};
