// apps/web/src/lib/features/sessions/detail/session-drawer.svelte
<!-- biome-ignore-all lint/a11y/useValidAriaValues: Svelte emits closed boolean ARIA values for the controlled Drawer -->
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const analysisDrawer = css({ w: { base: '100vw', md: 'min(960px, 94vw)' } });
  const tokenSegmentClasses = {
    cacheRead: css({ bg: 'accent', opacity: 0.22 }),
    cacheWrite: css({ bg: 'accent', opacity: 0.42 }),
    input: css({ bg: 'accent', opacity: 0.68 }),
    output: css({ bg: 'accent' }),
  } as const;
</script>

<script lang="ts">
  import { cx } from '@ai-usage/design-system/css';
  import {
    type BarSegment,
    Drawer,
    drawer,
    drawerActions,
    drawerBody,
    drawerClose,
    drawerCompare,
    drawerGrid,
    drawerLegend,
    drawerLegendItem,
    drawerLegendSwatch,
    drawerLegendValue,
    drawerNav,
    drawerPosition,
    drawerTitle,
    drawerTop,
    ghostButton,
    HarnessBadge,
    muted,
    SegmentBar,
  } from '@ai-usage/design-system/svelte';
  import { provenanceForUsageRow } from '@ai-usage/report-core/provenance';

  import type { SessionPresentationRow } from '@ai-usage/report-core/session-query';
  import type { Snippet } from 'svelte';
  import { MediaQuery } from 'svelte/reactivity';
  import { lineDeltaLabel, rtkSavedLabel, rtkSavedTitle } from '../../../../dashboard-sort';
  import { sessionDurationSemantics } from '../../../../session-analysis-model';
  import { fmtCompact, fmtDate, fmtDuration, fmtMoney, fmtNum } from '../../../foundation/presentation/format';
  import { apiValuePresentation } from '../../../foundation/presentation/report-value';
  import DrawerDetailItem from './drawer-detail-item.svelte';
  import SessionAnalysis from './session-analysis.svelte';
  import SessionVcsSummary from './session-vcs-summary.svelte';
  import type { SessionDetailController, SessionDetailControllerSnapshot } from './types';

  let {
    campaignSlot,
    controller,
    onFieldFilter = () => undefined,
    rows,
    snapshot,
  }: {
    campaignSlot?: Snippet;
    controller: SessionDetailController;
    onFieldFilter?: (key: 'model' | 'project', value: string) => void;
    rows: readonly SessionPresentationRow[];
    snapshot: SessionDetailControllerSnapshot;
  } = $props();

  let closeButton = $state<HTMLButtonElement>();
  let analysisPanel = $state<HTMLDivElement>();
  const desktopViewport = new MediaQuery('(min-width: 48rem)', false);
  const mobileDrawer = $derived(!desktopViewport.current);
  let previousFocus = $state<Element | null>(typeof document === 'undefined' ? null : document.activeElement);
  let presentedRow = $state<SessionPresentationRow | null>(null);
  let presentedTarget = $state<SessionDetailControllerSnapshot['target']>(null);
  let drawerWasOpen = false;
  const drawerOpen = $derived(snapshot.row !== null && snapshot.target !== null);
  const row = $derived(snapshot.row ?? presentedRow);
  const target = $derived(snapshot.target ?? presentedTarget);
  const position = $derived(row ? rows.findIndex((candidate) => candidate.rowId === row.rowId) : -1);
  const median = (values: readonly number[]): number => {
    const sorted = [...values].sort((left, right) => left - right);
    if (sorted.length === 0) {
      return 0;
    }
    const middle = Math.floor(sorted.length / 2);
    return sorted.length % 2 === 0 ? ((sorted[middle - 1] ?? 0) + (sorted[middle] ?? 0)) / 2 : (sorted[middle] ?? 0);
  };
  const medianCost = $derived(
    median(rows.filter((item) => item.costKnown && item.costApprox > 0).map((item) => item.costApprox)),
  );
  const medianDuration = $derived(median(rows.map((item) => item.durationMs ?? 0).filter((duration) => duration > 0)));
  const costRatio = $derived(
    row?.costKnown && row.costApprox > 0 && medianCost > 0 ? row.costApprox / medianCost : null,
  );
  const durationRatio = $derived(
    row && (row.durationMs ?? 0) > 0 && medianDuration > 0 ? (row.durationMs ?? 0) / medianDuration : null,
  );
  const fmtRatio = (ratio: number): string => (ratio >= 10 ? `${Math.round(ratio)}×` : `${ratio.toFixed(1)}×`);
  const analysisButtonLabel = (): string => {
    if (snapshot.analysisOpen) {
      return 'Hide analysis';
    }
    return target?.kind === 'session' ? 'Analyze' : 'Analyze root';
  };
  const analysisButtonAriaLabel = (): string => {
    if (snapshot.analysisOpen) {
      return 'Hide session chronology';
    }
    return target?.kind === 'session' ? 'Analyze session chronology' : 'Analyze root session chronology';
  };
  const positionLabel = (): string => {
    if (snapshot.navigation) {
      return `${fmtNum(snapshot.navigation.total)} matching sessions`;
    }
    return position >= 0 ? `${fmtNum(position + 1)} / ${fmtNum(rows.length)}` : 'Outside filters';
  };
  const previousAvailable = $derived(snapshot.navigation ? snapshot.navigation.previous !== null : position > 0);
  const nextAvailable = $derived(
    snapshot.navigation ? snapshot.navigation.next !== null : position >= 0 && position < rows.length - 1,
  );
  const segments = $derived.by((): BarSegment[] =>
    row
      ? [
          { label: 'Cache read', value: row.tokCr, class: tokenSegmentClasses.cacheRead },
          { label: 'Cache write', value: row.tokCw, class: tokenSegmentClasses.cacheWrite },
          { label: 'Input', value: row.tokIn, class: tokenSegmentClasses.input },
          { label: 'Output', value: row.tokOut, class: tokenSegmentClasses.output },
        ]
      : [],
  );
  const partialHint = $derived(
    row
      ? (provenanceForUsageRow(row).find((fact) => fact.kind === 'partial-session')?.description ??
          'Local history did not cover the whole session.')
      : '',
  );

  $effect.pre(() => {
    const currentOpen = drawerOpen;
    if (currentOpen && !drawerWasOpen) {
      previousFocus = typeof document === 'undefined' ? null : document.activeElement;
    }
    drawerWasOpen = currentOpen;
  });

  $effect(() => {
    if (snapshot.row && snapshot.target) {
      presentedRow = snapshot.row;
      presentedTarget = snapshot.target;
    }
  });

  const visibleSessionTrigger = (): HTMLElement | null => {
    if (typeof document === 'undefined' || !row) {
      return null;
    }

    const candidates = document.querySelectorAll<HTMLElement>('[data-session-row-id]');
    for (const candidate of candidates) {
      if (candidate.dataset.sessionRowId !== row.rowId || candidate.getClientRects().length === 0) {
        continue;
      }

      if (candidate.matches('[data-session-index]')) {
        return candidate;
      }

      const mobileTrigger = candidate.querySelector<HTMLElement>('[data-session-index]');
      if (mobileTrigger && mobileTrigger.getClientRects().length > 0) {
        return mobileTrigger;
      }
    }

    return null;
  };

  const previousFocusElement = (): HTMLElement | null => {
    if (
      previousFocus instanceof HTMLElement &&
      previousFocus.isConnected &&
      previousFocus.getClientRects().length > 0
    ) {
      return previousFocus;
    }
    return visibleSessionTrigger();
  };

  const closeDrawer = (): void => {
    controller.close();
  };

  const toggleAnalysis = async (): Promise<void> => {
    await controller.toggleAnalysis();
    if (controller.current().analysisOpen) {
      analysisPanel?.scrollIntoView({ block: 'nearest' });
    }
  };
</script>

<Drawer
  closeOnInteractOutside={mobileDrawer}
  contentAriaLabel="Session details"
  contentClass={snapshot.analysisOpen ? cx(drawer, analysisDrawer) : drawer}
  finalFocusEl={previousFocusElement}
  initialFocusEl={() => (mobileDrawer ? (closeButton ?? null) : previousFocusElement())}
  modal={mobileDrawer}
  onOpenChange={(open) => {
    if (!open) {
      closeDrawer();
    }
  }}
  open={drawerOpen}
  preventScroll={mobileDrawer}
  trapFocus={mobileDrawer}
>
  {#if row && target}
    <div class={drawerTop} data-session-drawer-header>
      <HarnessBadge name={row.harness} />
      <nav aria-label={`Session navigation, ${positionLabel()}`} class={drawerNav} data-session-drawer-navigation>
        <span class={drawerPosition}>
          {positionLabel()}
        </span>
        <button
          aria-label="Previous session (k)"
          class={drawerClose}
          disabled={snapshot.navigation?.loading || !previousAvailable}
          onclick={() => controller.navigate(-1)}
          title="Previous session (k)"
          type="button"
        >
          ↑
        </button>
        <button
          aria-label="Next session (j)"
          class={drawerClose}
          disabled={snapshot.navigation?.loading || !nextAvailable}
          onclick={() => controller.navigate(1)}
          title="Next session (j)"
          type="button"
        >
          ↓
        </button>
        {#if snapshot.revision}
          <button
            aria-controls="session-analysis-panel"
            aria-expanded={snapshot.analysisOpen ? 'true' : 'false'}
            aria-label={analysisButtonAriaLabel()}
            class={ghostButton}
            onclick={toggleAnalysis}
            type="button"
          >
            {analysisButtonLabel()}
          </button>
        {/if}
        <button
          aria-label="Close session details"
          class={drawerClose}
          onclick={closeDrawer}
          type="button"
          bind:this={closeButton}
        >
          ✕
        </button>
      </nav>
    </div>
    <div class={drawerBody} data-session-drawer-body>
      <div>
        <div class={drawerTitle}>{row.sessionLabel}</div>
        <div class={muted}>{row.providerDisplay} · {row.modelLabel}</div>
      </div>
      <div>
        <SegmentBar ariaLabel="Token anatomy" {segments} />
        <div class={drawerLegend} style="margin-top: 8px">
          {#each segments as segment (segment.label)}
            <div class={drawerLegendItem} title={`${segment.label}: ${fmtNum(segment.value)} tokens`}>
              <span class={cx(drawerLegendSwatch, segment.class)}></span>
              <span>{segment.label}</span><span class={drawerLegendValue}>{fmtCompact(segment.value)}</span>
            </div>
          {/each}
        </div>
      </div>
      {#if costRatio !== null || durationRatio !== null}
        <div class={drawerCompare} title="Compared with the median session in the current view">
          {#if costRatio !== null}
            ≈ {fmtRatio(costRatio)} median cost
          {/if}
          {#if costRatio !== null && durationRatio !== null}
            ·
          {/if}
          {#if durationRatio !== null}
            {fmtRatio(durationRatio)}
            median duration
          {/if}
        </div>
      {/if}
      {#if campaignSlot}
        {@render campaignSlot()}
      {/if}
      <div class={drawerGrid}>
        <DrawerDetailItem label="Started" value={fmtDate(row.date)} />
        <DrawerDetailItem label="Ended" value={fmtDate(row.endDate)} />
        <DrawerDetailItem
          hint={`Exact token count: ${fmtNum(row.tokenTotal)}`}
          label="Total tokens"
          value={fmtCompact(row.tokenTotal)}
        />
        <DrawerDetailItem hint={rtkSavedTitle(row)} label="RTK savings" value={rtkSavedLabel(row)} />
        <DrawerDetailItem
          hint={apiValuePresentation(row).title}
          label="API value"
          value={apiValuePresentation(row).label}
        />
        <DrawerDetailItem
          hint="Out-of-pocket spend — $0.00 means covered by a subscription"
          label="Actual cost"
          value={fmtMoney(row.costActual)}
        />
        <DrawerDetailItem
          hint="Cursor export value covered by the subscription quota"
          label="Sub value"
          value={fmtMoney(row.costQuota)}
        />
        <DrawerDetailItem label="Calls" value={fmtNum(row.calls)} />
        <DrawerDetailItem label="Turns" value={row.usageUnavailable ? 'Unavailable' : fmtNum(row.turns)} />
        <DrawerDetailItem label="Tools" value={fmtNum(row.tools)} />
        <DrawerDetailItem
          hint={sessionDurationSemantics(row.source?.harnessKey, target.kind === 'campaign-root').metricHint}
          label={sessionDurationSemantics(row.source?.harnessKey, target.kind === 'campaign-root').metricLabel}
          value={fmtDuration(row.durationMs)}
        />
        <DrawerDetailItem label="Lines" value={lineDeltaLabel(row)} />
        <DrawerDetailItem label="Subagent" value={row.subagent ? 'Yes' : 'No'} />
        {#if row.partial}
          <DrawerDetailItem hint={partialHint} label="Partial" value="Yes" />
        {/if}
        {#if row.usageUnavailable}
          <DrawerDetailItem
            hint="Session came from prompt history, but detailed local token counters are missing"
            label="Usage data"
            value="Unavailable"
          />
        {/if}
        {#if row.ambiguous}
          <DrawerDetailItem
            hint="Multiple local Cursor sessions matched the same export cluster; totals are best-effort"
            label="Reconciliation"
            value="Ambiguous"
          />
        {/if}
      </div>
      {#if row.source?.vcs}
        <SessionVcsSummary
          context={row.source.vcs}
          onResolve={() => controller.resolveVcs()}
          resolution={snapshot.vcsResolution}
          resolving={snapshot.vcsResolving}
        />
      {/if}
      <div class={drawerActions}>
        <button class={ghostButton} onclick={() => onFieldFilter('project', row.projectKey)} type="button">
          Filter project: {row.projectLabel}
        </button>
        <button class={ghostButton} onclick={() => onFieldFilter('model', row.modelKey)} type="button">
          Filter model: {row.modelKey}
        </button>
      </div>
      {#if snapshot.analysisOpen}
        <div id="session-analysis-panel" bind:this={analysisPanel}>
          <SessionAnalysis
            error={snapshot.analysisError}
            harnessKey={row.source?.harnessKey ?? ''}
            loading={snapshot.analysisLoading}
            onRetry={() => controller.retryAnalysis()}
            response={snapshot.analysisResponse}
            {target}
          />
        </div>
      {/if}
    </div>
  {/if}
</Drawer>

// apps/web/src/session-drawer.tsx
import { Drawer } from '@ai-usage/design-system';
import { css, cx } from '@ai-usage/design-system/css';
import {
  drawer,
  drawerActions,
  drawerBody,
  drawerClose,
  drawerCompare,
  drawerGrid,
  drawerLegend,
  drawerLegendItem,
  drawerLegendSwatch,
  drawerLegendValue,
  drawerNav,
  drawerPosition,
  drawerTitle,
  drawerTop,
  ghostButton,
  muted,
} from '@ai-usage/design-system/report';
import { provenanceForUsageRow } from '@ai-usage/report-core/provenance';
import type { SessionDetailResponse } from '@ai-usage/report-core/session-detail';
import type { SessionVcsResolveResponse } from '@ai-usage/report-core/session-vcs';
import { createEffect, createMemo, createSignal, For, onCleanup, Show } from 'solid-js';
import type { CampaignTotals, CampaignView } from './dashboard-model';
import type { FieldFilterKey } from './dashboard-search';
import { lineDeltaLabel, rtkSavedLabel, rtkSavedTitle } from './dashboard-sort';
import { DrawerDetailItem as DetailItem } from './drawer-detail-item';
import { SessionAnalysis } from './session-analysis';
import { classifySessionAnalysisError, type SessionAnalysisError } from './session-analysis-error';
import { sessionDurationSemantics } from './session-analysis-model';
import type { SessionAnalysisTarget } from './session-analysis-target';
import { canAnalyzeSession, loadSessionDetail } from './session-detail-client';
import { loadSessionVcsResolution } from './session-vcs-client';
import { SessionVcsSummary } from './session-vcs-summary';
import {
  apiValuePresentation,
  type DashboardRow,
  fmtCompact,
  fmtDate,
  fmtDuration,
  fmtMoney,
  fmtNum,
  HarnessBadge,
  median,
  rowKey,
  SegmentBar,
  tokenSegmentClasses,
} from './shared';

const analysisDrawer = css({ w: { base: '100vw', md: 'min(960px, 94vw)' } });
const SESSION_ANALYSIS_PANEL_ID = 'session-analysis-panel';

const fmtRatio = (ratio: number) => (ratio >= 10 ? `${Math.round(ratio)}×` : `${ratio.toFixed(1)}×`);

const fmtCampaignTotals = (totals: CampaignTotals) => {
  const apiValue = apiValuePresentation({ costApprox: totals.totalCost, costKnown: totals.costKnown });
  return [
    `${apiValue.label} API`,
    `${fmtCompact(totals.freshTokens)} fresh tokens`,
    `${fmtNum(totals.turns)} turns`,
    `${fmtNum(totals.tools)} tools`,
  ].join(' · ');
};

const campaignSessionSummary = (row: DashboardRow) => {
  const apiValue = apiValuePresentation(row);
  return [
    `${apiValue.label} API`,
    `${fmtCompact(row.freshTokens)} fresh`,
    `${fmtNum(row.turns)} turns`,
    `${fmtNum(row.tools)} tools`,
  ].join(' · ');
};

export const SessionDrawer = (props: {
  onClose: () => void;
  onClearFilters: () => void;
  onFieldFilter: (key: FieldFilterKey, value: string) => void;
  onNavigate: (delta: number) => void;
  onSelectSession: (row: DashboardRow) => void;
  navigation?: {
    loading: boolean;
    next: DashboardRow | null;
    previous: DashboardRow | null;
    total: number;
  };
  revision: string | null;
  row: DashboardRow;
  rows: DashboardRow[];
  selectedCampaign?: CampaignView | null;
  target: SessionAnalysisTarget;
}) => {
  let closeButton: HTMLButtonElement | undefined;
  const previousFocus = typeof document === 'undefined' ? null : document.activeElement;
  const [showAllCampaignSessions, setShowAllCampaignSessions] = createSignal(false);
  const [analysisOpen, setAnalysisOpen] = createSignal(false);
  const [analysisLoading, setAnalysisLoading] = createSignal(false);
  const [analysisResponse, setAnalysisResponse] = createSignal<SessionDetailResponse | null>(null);
  const [analysisError, setAnalysisError] = createSignal<SessionAnalysisError | null>(null);
  const [vcsResolution, setVcsResolution] = createSignal<SessionVcsResolveResponse | null>(null);
  const [vcsResolving, setVcsResolving] = createSignal(false);
  let analysisPanel: HTMLDivElement | undefined;
  let analysisSequence = 0;
  let vcsSequence = 0;

  createEffect(() => {
    rowKey(props.row);
    analysisSequence += 1;
    setAnalysisOpen(false);
    setAnalysisLoading(false);
    setAnalysisResponse(null);
    setAnalysisError(null);
    vcsSequence += 1;
    setVcsResolution(null);
    setVcsResolving(false);
  });

  onCleanup(() => {
    analysisSequence += 1;
    vcsSequence += 1;
  });

  const resolveVcs = async (): Promise<void> => {
    const sequence = ++vcsSequence;
    setVcsResolving(true);
    setVcsResolution(null);
    try {
      const revision = props.revision;
      if (!revision) {
        throw new Error('A served report revision is required for VCS resolution.');
      }
      const resolution = await loadSessionVcsResolution({ revision, rowId: props.target.reportRowId });
      if (sequence === vcsSequence) {
        setVcsResolution(resolution);
      }
    } catch {
      if (sequence === vcsSequence) {
        setVcsResolution({ reason: 'resolver-unavailable', status: 'unavailable' });
      }
    } finally {
      if (sequence === vcsSequence) {
        setVcsResolving(false);
      }
    }
  };

  const loadAnalysis = async (): Promise<void> => {
    const sequence = ++analysisSequence;
    setAnalysisLoading(true);
    setAnalysisResponse(null);
    setAnalysisError(null);
    try {
      const revision = props.revision;
      if (!revision) {
        throw new Error('A served report revision is required for session analysis.');
      }
      const response = await loadSessionDetail({ revision, rowId: props.target.reportRowId });
      if (sequence === analysisSequence) {
        setAnalysisResponse(response);
      }
    } catch (error) {
      if (sequence === analysisSequence) {
        setAnalysisError(classifySessionAnalysisError(error));
      }
    } finally {
      if (sequence === analysisSequence) {
        setAnalysisLoading(false);
      }
    }
  };

  const toggleAnalysis = async (): Promise<void> => {
    if (analysisOpen()) {
      analysisSequence += 1;
      setAnalysisOpen(false);
      setAnalysisLoading(false);
      setAnalysisResponse(null);
      setAnalysisError(null);
      return;
    }
    setAnalysisOpen(true);
    const requestSequence = analysisSequence + 1;
    await loadAnalysis();
    if (analysisOpen() && requestSequence === analysisSequence) {
      analysisPanel?.scrollIntoView({ block: 'nearest' });
    }
  };

  const analysisButtonLabel = (): string => {
    if (analysisOpen()) {
      return 'Hide analysis';
    }
    return props.target.kind === 'session' ? 'Analyze' : 'Analyze root';
  };

  const analysisButtonAriaLabel = (): string => {
    if (analysisOpen()) {
      return 'Hide session chronology';
    }
    return props.target.kind === 'session' ? 'Analyze session chronology' : 'Analyze root session chronology';
  };

  const position = createMemo(() => props.rows.findIndex((row) => rowKey(row) === rowKey(props.row)));
  const medianCost = createMemo(() =>
    median(props.rows.filter((row) => row.costKnown && row.costApprox > 0).map((row) => row.costApprox)),
  );
  const medianDuration = createMemo(() =>
    median(props.rows.map((row) => row.durationMs ?? 0).filter((duration) => duration > 0)),
  );
  const costRatio = () =>
    props.row.costKnown && props.row.costApprox > 0 && medianCost() > 0 ? props.row.costApprox / medianCost() : null;
  const durationRatio = () =>
    (props.row.durationMs ?? 0) > 0 && medianDuration() > 0 ? (props.row.durationMs ?? 0) / medianDuration() : null;
  const apiValue = () => apiValuePresentation(props.row);
  const durationSemantics = () =>
    sessionDurationSemantics(props.row.source?.harnessKey, props.target.kind === 'campaign-root');
  const partialSessionHint = () =>
    provenanceForUsageRow(props.row).find((fact) => fact.kind === 'partial-session')?.description ??
    'Local history did not cover the whole session.';
  const isInNavigation = () => position() >= 0;
  const previousAvailable = () =>
    props.navigation ? props.navigation.previous !== null : isInNavigation() && position() > 0;
  const nextAvailable = () =>
    props.navigation ? props.navigation.next !== null : isInNavigation() && position() < props.rows.length - 1;

  const anatomySegments = () => [
    { label: 'Cache read', value: props.row.tokCr, class: tokenSegmentClasses.cacheRead },
    { label: 'Cache write', value: props.row.tokCw, class: tokenSegmentClasses.cacheWrite },
    { label: 'Input', value: props.row.tokIn, class: tokenSegmentClasses.input },
    { label: 'Output', value: props.row.tokOut, class: tokenSegmentClasses.output },
  ];
  const campaignVisibleKeys = createMemo(
    () => new Set((props.selectedCampaign?.visibleRows ?? []).map((row) => rowKey(row))),
  );
  const hiddenCampaignRows = createMemo(
    () => props.selectedCampaign?.allRows.filter((row) => !campaignVisibleKeys().has(rowKey(row))) ?? [],
  );
  const campaignRowsToShow = createMemo(() => {
    const campaign = props.selectedCampaign;
    if (!campaign) {
      return [];
    }
    return showAllCampaignSessions() ? [...campaign.visibleRows, ...hiddenCampaignRows()] : campaign.visibleRows;
  });

  return (
    <Drawer
      closeOnInteractOutside
      contentAriaLabel="Session details"
      contentClass={analysisOpen() ? cx(drawer, analysisDrawer) : drawer}
      finalFocusEl={() => (previousFocus instanceof HTMLElement && previousFocus.isConnected ? previousFocus : null)}
      initialFocusEl={() => closeButton ?? null}
      modal={false}
      onOpenChange={(open) => {
        if (!open) {
          props.onClose();
        }
      }}
      open
      trapFocus={false}
    >
      <div class={drawerTop}>
        <HarnessBadge name={props.row.harness} />
        <div class={drawerNav}>
          <span class={drawerPosition}>
            <Show fallback="Outside filters" when={props.navigation || isInNavigation()}>
              {props.navigation
                ? `${fmtNum(props.navigation.total)} matching sessions`
                : `${fmtNum(position() + 1)} / ${fmtNum(props.rows.length)}`}
            </Show>
          </span>
          <button
            aria-label="Previous session (k)"
            class={drawerClose}
            disabled={props.navigation?.loading || !previousAvailable()}
            onClick={() => props.onNavigate(-1)}
            title="Previous session (k)"
            type="button"
          >
            ↑
          </button>
          <button
            aria-label="Next session (j)"
            class={drawerClose}
            disabled={props.navigation?.loading || !nextAvailable()}
            onClick={() => props.onNavigate(1)}
            title="Next session (j)"
            type="button"
          >
            ↓
          </button>
          <Show when={canAnalyzeSession({ revision: props.revision, rowId: props.target.reportRowId })}>
            <button
              aria-controls={SESSION_ANALYSIS_PANEL_ID}
              aria-expanded={analysisOpen()}
              aria-label={analysisButtonAriaLabel()}
              class={ghostButton}
              onClick={() => toggleAnalysis()}
              type="button"
            >
              {analysisButtonLabel()}
            </button>
          </Show>
          <button
            aria-label="Close session details"
            class={drawerClose}
            onClick={() => props.onClose()}
            ref={(element) => {
              closeButton = element;
            }}
            type="button"
          >
            ✕
          </button>
        </div>
      </div>
      <div class={drawerBody}>
        <div>
          <div class={drawerTitle}>{props.row.sessionLabel}</div>
          <div class={muted}>
            {props.row.providerDisplay} · {props.row.modelLabel}
          </div>
        </div>
        <div>
          <SegmentBar ariaLabel="Token anatomy" segments={anatomySegments()} />
          <div class={drawerLegend} style={{ 'margin-top': '8px' }}>
            <For each={anatomySegments()}>
              {(segment) => (
                <div class={drawerLegendItem} title={`${segment.label}: ${fmtNum(segment.value)} tokens`}>
                  <span class={cx(drawerLegendSwatch, segment.class)} />
                  <span>{segment.label}</span>
                  <span class={drawerLegendValue}>{fmtCompact(segment.value)}</span>
                </div>
              )}
            </For>
          </div>
        </div>
        <Show when={costRatio() != null || durationRatio() != null}>
          <div class={drawerCompare} title="Compared with the median session in the current view">
            <Show when={costRatio() != null}>≈ {fmtRatio(costRatio() ?? 0)} median cost</Show>
            <Show when={costRatio() != null && durationRatio() != null}> · </Show>
            <Show when={durationRatio() != null}>{fmtRatio(durationRatio() ?? 0)} median duration</Show>
          </div>
        </Show>
        <Show when={props.selectedCampaign}>
          {(campaign) => (
            <div class={drawerCompare}>
              <div class={drawerTitle}>Campaign</div>
              <div style={{ 'margin-top': '6px' }}>{fmtCampaignTotals(campaign().visibleTotals)}</div>
              <div class={muted} style={{ 'margin-top': '4px' }}>
                {fmtNum(campaign().visibleCount)} / {fmtNum(campaign().totalCount)} sessions shown
                <Show when={campaign().visibleCount < campaign().totalCount}>
                  {' · '}current filters hide part of this campaign
                </Show>
              </div>
              <div style={{ display: 'grid', gap: '8px', 'margin-top': '10px' }}>
                <For each={campaignRowsToShow()}>
                  {(session) => {
                    const hidden = () => !campaignVisibleKeys().has(rowKey(session));
                    return (
                      <button
                        class={ghostButton}
                        onClick={() => props.onSelectSession(session)}
                        style={{
                          display: 'block',
                          'text-align': 'left',
                          opacity: hidden() ? 0.58 : 1,
                        }}
                        title={hidden() ? 'Select session hidden by current filters' : 'Select campaign session'}
                        type="button"
                      >
                        <div>{session.sessionLabel}</div>
                        <div class={muted}>
                          {campaignSessionSummary(session)}
                          <Show when={hidden()}>{' · '}hidden by current filters</Show>
                        </div>
                      </button>
                    );
                  }}
                </For>
              </div>
              <Show when={hiddenCampaignRows().length > 0}>
                <div class={drawerActions} style={{ 'margin-top': '10px' }}>
                  <button
                    class={ghostButton}
                    onClick={() => setShowAllCampaignSessions((current) => !current)}
                    type="button"
                  >
                    {showAllCampaignSessions() ? 'Show filtered campaign sessions' : 'Show all campaign sessions'}
                  </button>
                  <button class={ghostButton} onClick={() => props.onClearFilters()} type="button">
                    Clear filters
                  </button>
                </div>
              </Show>
            </div>
          )}
        </Show>
        <div class={drawerGrid}>
          <DetailItem label="Started" value={fmtDate(props.row.date)} />
          <DetailItem label="Ended" value={fmtDate(props.row.endDate)} />
          <DetailItem
            hint={`Exact token count: ${fmtNum(props.row.tokenTotal)}`}
            label="Total tokens"
            value={fmtCompact(props.row.tokenTotal)}
          />
          <DetailItem hint={rtkSavedTitle(props.row)} label="RTK savings" value={rtkSavedLabel(props.row)} />
          <DetailItem hint={apiValue().title} label="API value" value={apiValue().label} />
          <DetailItem
            hint="Out-of-pocket spend — $0.00 means covered by a subscription"
            label="Actual cost"
            value={fmtMoney(props.row.costActual)}
          />
          <DetailItem
            hint="Cursor export value covered by the subscription quota"
            label="Sub value"
            value={fmtMoney(props.row.costQuota)}
          />
          <DetailItem label="Calls" value={fmtNum(props.row.calls)} />
          <DetailItem label="Turns" value={fmtNum(props.row.turns)} />
          <DetailItem label="Tools" value={fmtNum(props.row.tools)} />
          <DetailItem
            hint={durationSemantics().metricHint}
            label={durationSemantics().metricLabel}
            value={fmtDuration(props.row.durationMs)}
          />
          <DetailItem label="Lines" value={lineDeltaLabel(props.row)} />
          <DetailItem label="Subagent" value={props.row.subagent ? 'Yes' : 'No'} />
          <Show when={props.row.partial}>
            <DetailItem hint={partialSessionHint()} label="Partial" value="Yes" />
          </Show>
          <Show when={props.row.usageUnavailable}>
            <DetailItem
              hint="Session came from prompt history, but detailed local token counters are missing"
              label="Usage data"
              value="Unavailable"
            />
          </Show>
          <Show when={props.row.ambiguous}>
            <DetailItem
              hint="Multiple local Cursor sessions matched the same export cluster; totals are best-effort"
              label="Reconciliation"
              value="Ambiguous"
            />
          </Show>
        </div>
        <Show when={props.row.source?.vcs}>
          {(vcs) => (
            <SessionVcsSummary
              context={vcs()}
              onResolve={resolveVcs}
              resolution={vcsResolution()}
              resolving={vcsResolving()}
            />
          )}
        </Show>
        <div class={drawerActions}>
          <button
            class={ghostButton}
            onClick={() => props.onFieldFilter('project', props.row.projectKey)}
            type="button"
          >
            Filter project: {props.row.projectLabel}
          </button>
          <button class={ghostButton} onClick={() => props.onFieldFilter('model', props.row.modelKey)} type="button">
            Filter model: {props.row.modelKey}
          </button>
        </div>
        <Show when={analysisOpen()}>
          <div
            id={SESSION_ANALYSIS_PANEL_ID}
            ref={(element) => {
              analysisPanel = element;
            }}
          >
            <SessionAnalysis
              error={analysisError()}
              harnessKey={props.row.source?.harnessKey ?? ''}
              loading={analysisLoading()}
              onRetry={loadAnalysis}
              response={analysisResponse()}
              target={props.target}
            />
          </div>
        </Show>
      </div>
    </Drawer>
  );
};
