// apps/web/src/lib/features/sessions/detail/highlighted-text.svelte
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const highlightMark = css({ bg: 'accentSoft', color: 'inherit', borderRadius: '2px' });
</script>

<script lang="ts">
  import { boundedSessionListLabel, caseInsensitiveLiteralMatches } from '../../../../session-list-label';

  let { query, text }: { query: string; text: string } = $props();
  const bounded = $derived(boundedSessionListLabel(text, query));
  const segments = $derived.by(() => {
    const normalizedQuery = query.trim();
    if (!normalizedQuery) {
      return [{ match: false, text: bounded }];
    }
    const matches = caseInsensitiveLiteralMatches(bounded, normalizedQuery);
    if (matches.length === 0) {
      return [{ match: false, text: bounded }];
    }
    const parts: { readonly match: boolean; readonly text: string }[] = [];
    let index = 0;
    for (const match of matches) {
      if (match.start > index) {
        parts.push({ match: false, text: bounded.slice(index, match.start) });
      }
      parts.push({ match: true, text: bounded.slice(match.start, match.end) });
      index = match.end;
    }
    if (index < bounded.length) {
      parts.push({ match: false, text: bounded.slice(index) });
    }
    return parts;
  });
</script>

{#each segments as segment, index (`${index}:${segment.match}:${segment.text}`)}
  {#if segment.match}
    <mark class={highlightMark}>{segment.text}</mark>
  {:else}
    {segment.text}
  {/if}
{/each}

// apps/report/src/highlighted-text.tsx
import { highlightMark } from '@ai-usage/design-system';
import { createMemo, For, Show } from 'solid-js';

// Marks the filter query inside session titles so a match explains itself.
export const HighlightedText = (props: { text: string; query: string }) => {
  const segments = createMemo(() => {
    const query = props.query.trim().toLowerCase();
    if (!query) return null;
    const lower = props.text.toLowerCase();
    if (!lower.includes(query)) return null;
    const parts: { match: boolean; text: string }[] = [];
    let index = 0;
    while (index < props.text.length) {
      const found = lower.indexOf(query, index);
      if (found === -1) {
        parts.push({ match: false, text: props.text.slice(index) });
        break;
      }
      if (found > index) parts.push({ match: false, text: props.text.slice(index, found) });
      parts.push({ match: true, text: props.text.slice(found, found + query.length) });
      index = found + query.length;
    }
    return parts;
  });

  return (
    <Show when={segments()} fallback={props.text}>
      {(parts) => (
        <For each={parts()}>{(part) => (part.match ? <mark class={highlightMark}>{part.text}</mark> : part.text)}</For>
      )}
    </Show>
  );
};
