// apps/web/src/lib/features/sessions/detail/session-drawer.svelte
<!-- biome-ignore-all lint/a11y/useValidAriaValues: Svelte emits closed boolean ARIA values for the controlled Drawer -->
<script lang="ts" module>
  import { css } from '@ai-usage/design-system/css';

  const analysisDrawer = css({ w: { base: '100vw', md: 'min(960px, 94vw)' } });
  const tokenSegmentClasses = {
    cacheRead: css({ bg: 'accent', opacity: 0.22 }),
    cacheWrite: css({ bg: 'accent', opacity: 0.42 }),
    input: css({ bg: 'accent', opacity: 0.68 }),
    output: css({ bg: 'accent' }),
  } as const;
</script>

<script lang="ts">
  import { cx } from '@ai-usage/design-system/css';
  import {
    type BarSegment,
    Drawer,
    drawer,
    drawerActions,
    drawerBody,
    drawerClose,
    drawerCompare,
    drawerGrid,
    drawerLegend,
    drawerLegendItem,
    drawerLegendSwatch,
    drawerLegendValue,
    drawerNav,
    drawerPosition,
    drawerTitle,
    drawerTop,
    ghostButton,
    HarnessBadge,
    muted,
    SegmentBar,
  } from '@ai-usage/design-system/svelte';
  import { provenanceForUsageRow } from '@ai-usage/report-core/provenance';

  import type { SessionPresentationRow } from '@ai-usage/report-core/session-query';
  import type { Snippet } from 'svelte';
  import { MediaQuery } from 'svelte/reactivity';
  import { lineDeltaLabel, rtkSavedLabel, rtkSavedTitle } from '../../../../dashboard-sort';
  import { sessionDurationSemantics } from '../../../../session-analysis-model';
  import { fmtCompact, fmtDate, fmtDuration, fmtMoney, fmtNum } from '../../../foundation/presentation/format';
  import { apiValuePresentation } from '../../../foundation/presentation/report-value';
  import DrawerDetailItem from './drawer-detail-item.svelte';
  import SessionAnalysis from './session-analysis.svelte';
  import SessionVcsSummary from './session-vcs-summary.svelte';
  import type { SessionDetailController, SessionDetailControllerSnapshot } from './types';

  let {
    campaignSlot,
    controller,
    onFieldFilter = () => undefined,
    rows,
    snapshot,
  }: {
    campaignSlot?: Snippet;
    controller: SessionDetailController;
    onFieldFilter?: (key: 'model' | 'project', value: string) => void;
    rows: readonly SessionPresentationRow[];
    snapshot: SessionDetailControllerSnapshot;
  } = $props();

  let closeButton = $state<HTMLButtonElement>();
  let analysisPanel = $state<HTMLDivElement>();
  const desktopViewport = new MediaQuery('(min-width: 48rem)', false);
  const mobileDrawer = $derived(!desktopViewport.current);
  let previousFocus = $state<Element | null>(typeof document === 'undefined' ? null : document.activeElement);
  let presentedRow = $state<SessionPresentationRow | null>(null);
  let presentedTarget = $state<SessionDetailControllerSnapshot['target']>(null);
  let drawerWasOpen = false;
  const drawerOpen = $derived(snapshot.row !== null && snapshot.target !== null);
  const row = $derived(snapshot.row ?? presentedRow);
  const target = $derived(snapshot.target ?? presentedTarget);
  const position = $derived(row ? rows.findIndex((candidate) => candidate.rowId === row.rowId) : -1);
  const median = (values: readonly number[]): number => {
    const sorted = [...values].sort((left, right) => left - right);
    if (sorted.length === 0) {
      return 0;
    }
    const middle = Math.floor(sorted.length / 2);
    return sorted.length % 2 === 0 ? ((sorted[middle - 1] ?? 0) + (sorted[middle] ?? 0)) / 2 : (sorted[middle] ?? 0);
  };
  const medianCost = $derived(
    median(rows.filter((item) => item.costKnown && item.costApprox > 0).map((item) => item.costApprox)),
  );
  const medianDuration = $derived(median(rows.map((item) => item.durationMs ?? 0).filter((duration) => duration > 0)));
  const costRatio = $derived(
    row?.costKnown && row.costApprox > 0 && medianCost > 0 ? row.costApprox / medianCost : null,
  );
  const durationRatio = $derived(
    row && (row.durationMs ?? 0) > 0 && medianDuration > 0 ? (row.durationMs ?? 0) / medianDuration : null,
  );
  const fmtRatio = (ratio: number): string => (ratio >= 10 ? `${Math.round(ratio)}×` : `${ratio.toFixed(1)}×`);
  const analysisButtonLabel = (): string => {
    if (snapshot.analysisOpen) {
      return 'Hide analysis';
    }
    return target?.kind === 'session' ? 'Analyze' : 'Analyze root';
  };
  const analysisButtonAriaLabel = (): string => {
    if (snapshot.analysisOpen) {
      return 'Hide session chronology';
    }
    return target?.kind === 'session' ? 'Analyze session chronology' : 'Analyze root session chronology';
  };
  const positionLabel = (): string => {
    if (snapshot.navigation) {
      return `${fmtNum(snapshot.navigation.total)} matching sessions`;
    }
    return position >= 0 ? `${fmtNum(position + 1)} / ${fmtNum(rows.length)}` : 'Outside filters';
  };
  const previousAvailable = $derived(snapshot.navigation ? snapshot.navigation.previous !== null : position > 0);
  const nextAvailable = $derived(
    snapshot.navigation ? snapshot.navigation.next !== null : position >= 0 && position < rows.length - 1,
  );
  const segments = $derived.by((): BarSegment[] =>
    row
      ? [
          { label: 'Cache read', value: row.tokCr, class: tokenSegmentClasses.cacheRead },
          { label: 'Cache write', value: row.tokCw, class: tokenSegmentClasses.cacheWrite },
          { label: 'Input', value: row.tokIn, class: tokenSegmentClasses.input },
          { label: 'Output', value: row.tokOut, class: tokenSegmentClasses.output },
        ]
      : [],
  );
  const partialHint = $derived(
    row
      ? (provenanceForUsageRow(row).find((fact) => fact.kind === 'partial-session')?.description ??
          'Local history did not cover the whole session.')
      : '',
  );

  $effect.pre(() => {
    const currentOpen = drawerOpen;
    if (currentOpen && !drawerWasOpen) {
      previousFocus = typeof document === 'undefined' ? null : document.activeElement;
    }
    drawerWasOpen = currentOpen;
  });

  $effect(() => {
    if (snapshot.row && snapshot.target) {
      presentedRow = snapshot.row;
      presentedTarget = snapshot.target;
    }
  });

  const visibleSessionTrigger = (): HTMLElement | null => {
    if (typeof document === 'undefined' || !row) {
      return null;
    }

    const candidates = document.querySelectorAll<HTMLElement>('[data-session-row-id]');
    for (const candidate of candidates) {
      if (candidate.dataset.sessionRowId !== row.rowId || candidate.getClientRects().length === 0) {
        continue;
      }

      if (candidate.matches('[data-session-index]')) {
        return candidate;
      }

      const mobileTrigger = candidate.querySelector<HTMLElement>('[data-session-index]');
      if (mobileTrigger && mobileTrigger.getClientRects().length > 0) {
        return mobileTrigger;
      }
    }

    return null;
  };

  const previousFocusElement = (): HTMLElement | null => {
    if (
      previousFocus instanceof HTMLElement &&
      previousFocus.isConnected &&
      previousFocus.getClientRects().length > 0
    ) {
      return previousFocus;
    }
    return visibleSessionTrigger();
  };

  const closeDrawer = (): void => {
    controller.close();
  };

  const toggleAnalysis = async (): Promise<void> => {
    await controller.toggleAnalysis();
    if (controller.current().analysisOpen) {
      analysisPanel?.scrollIntoView({ block: 'nearest' });
    }
  };
</script>

<Drawer
  closeOnInteractOutside={mobileDrawer}
  contentAriaLabel="Session details"
  contentClass={snapshot.analysisOpen ? cx(drawer, analysisDrawer) : drawer}
  finalFocusEl={previousFocusElement}
  initialFocusEl={() => (mobileDrawer ? (closeButton ?? null) : previousFocusElement())}
  modal={mobileDrawer}
  onOpenChange={(open) => {
    if (!open) {
      closeDrawer();
    }
  }}
  open={drawerOpen}
  preventScroll={mobileDrawer}
  trapFocus={mobileDrawer}
>
  {#if row && target}
    <div class={drawerTop} data-session-drawer-header>
      <HarnessBadge name={row.harness} />
      <nav aria-label={`Session navigation, ${positionLabel()}`} class={drawerNav} data-session-drawer-navigation>
        <span class={drawerPosition}>
          {positionLabel()}
        </span>
        <button
          aria-label="Previous session (k)"
          class={drawerClose}
          disabled={snapshot.navigation?.loading || !previousAvailable}
          onclick={() => controller.navigate(-1)}
          title="Previous session (k)"
          type="button"
        >
          ↑
        </button>
        <button
          aria-label="Next session (j)"
          class={drawerClose}
          disabled={snapshot.navigation?.loading || !nextAvailable}
          onclick={() => controller.navigate(1)}
          title="Next session (j)"
          type="button"
        >
          ↓
        </button>
        {#if snapshot.revision}
          <button
            aria-controls="session-analysis-panel"
            aria-expanded={snapshot.analysisOpen ? 'true' : 'false'}
            aria-label={analysisButtonAriaLabel()}
            class={ghostButton}
            onclick={toggleAnalysis}
            type="button"
          >
            {analysisButtonLabel()}
          </button>
        {/if}
        <button
          aria-label="Close session details"
          class={drawerClose}
          onclick={closeDrawer}
          type="button"
          bind:this={closeButton}
        >
          ✕
        </button>
      </nav>
    </div>
    <div class={drawerBody} data-session-drawer-body>
      <div>
        <div class={drawerTitle}>{row.sessionLabel}</div>
        <div class={muted}>{row.providerDisplay} · {row.modelLabel}</div>
      </div>
      <div>
        <SegmentBar ariaLabel="Token anatomy" {segments} />
        <div class={drawerLegend} style="margin-top: 8px">
          {#each segments as segment (segment.label)}
            <div class={drawerLegendItem} title={`${segment.label}: ${fmtNum(segment.value)} tokens`}>
              <span class={cx(drawerLegendSwatch, segment.class)}></span>
              <span>{segment.label}</span><span class={drawerLegendValue}>{fmtCompact(segment.value)}</span>
            </div>
          {/each}
        </div>
      </div>
      {#if costRatio !== null || durationRatio !== null}
        <div class={drawerCompare} title="Compared with the median session in the current view">
          {#if costRatio !== null}
            ≈ {fmtRatio(costRatio)} median cost
          {/if}
          {#if costRatio !== null && durationRatio !== null}
            ·
          {/if}
          {#if durationRatio !== null}
            {fmtRatio(durationRatio)}
            median duration
          {/if}
        </div>
      {/if}
      {#if campaignSlot}
        {@render campaignSlot()}
      {/if}
      <div class={drawerGrid}>
        <DrawerDetailItem label="Started" value={fmtDate(row.date)} />
        <DrawerDetailItem label="Ended" value={fmtDate(row.endDate)} />
        <DrawerDetailItem
          hint={`Exact token count: ${fmtNum(row.tokenTotal)}`}
          label="Total tokens"
          value={fmtCompact(row.tokenTotal)}
        />
        <DrawerDetailItem hint={rtkSavedTitle(row)} label="RTK savings" value={rtkSavedLabel(row)} />
        <DrawerDetailItem
          hint={apiValuePresentation(row).title}
          label="API value"
          value={apiValuePresentation(row).label}
        />
        <DrawerDetailItem
          hint="Out-of-pocket spend — $0.00 means covered by a subscription"
          label="Actual cost"
          value={fmtMoney(row.costActual)}
        />
        <DrawerDetailItem
          hint="Cursor export value covered by the subscription quota"
          label="Sub value"
          value={fmtMoney(row.costQuota)}
        />
        <DrawerDetailItem label="Calls" value={fmtNum(row.calls)} />
        <DrawerDetailItem label="Turns" value={row.usageUnavailable ? 'Unavailable' : fmtNum(row.turns)} />
        <DrawerDetailItem label="Tools" value={fmtNum(row.tools)} />
        <DrawerDetailItem
          hint={sessionDurationSemantics(row.source?.harnessKey, target.kind === 'campaign-root').metricHint}
          label={sessionDurationSemantics(row.source?.harnessKey, target.kind === 'campaign-root').metricLabel}
          value={fmtDuration(row.durationMs)}
        />
        <DrawerDetailItem label="Lines" value={lineDeltaLabel(row)} />
        <DrawerDetailItem label="Subagent" value={row.subagent ? 'Yes' : 'No'} />
        {#if row.partial}
          <DrawerDetailItem hint={partialHint} label="Partial" value="Yes" />
        {/if}
        {#if row.usageUnavailable}
          <DrawerDetailItem
            hint="Session came from prompt history, but detailed local token counters are missing"
            label="Usage data"
            value="Unavailable"
          />
        {/if}
        {#if row.ambiguous}
          <DrawerDetailItem
            hint="Multiple local Cursor sessions matched the same export cluster; totals are best-effort"
            label="Reconciliation"
            value="Ambiguous"
          />
        {/if}
      </div>
      {#if row.source?.vcs}
        <SessionVcsSummary
          context={row.source.vcs}
          onResolve={() => controller.resolveVcs()}
          resolution={snapshot.vcsResolution}
          resolving={snapshot.vcsResolving}
        />
      {/if}
      <div class={drawerActions}>
        <button class={ghostButton} onclick={() => onFieldFilter('project', row.projectKey)} type="button">
          Filter project: {row.projectLabel}
        </button>
        <button class={ghostButton} onclick={() => onFieldFilter('model', row.modelKey)} type="button">
          Filter model: {row.modelKey}
        </button>
      </div>
      {#if snapshot.analysisOpen}
        <div id="session-analysis-panel" bind:this={analysisPanel}>
          <SessionAnalysis
            error={snapshot.analysisError}
            harnessKey={row.source?.harnessKey ?? ''}
            loading={snapshot.analysisLoading}
            onRetry={() => controller.retryAnalysis()}
            response={snapshot.analysisResponse}
            {target}
          />
        </div>
      {/if}
    </div>
  {/if}
</Drawer>

// apps/report/src/session-drawer.tsx
import { cx } from '@ai-usage/design-system/css';
import {
  detailItem,
  detailLabel,
  detailValue,
  drawer,
  drawerActions,
  drawerBody,
  drawerClose,
  drawerCompare,
  drawerGrid,
  drawerLegend,
  drawerLegendItem,
  drawerLegendSwatch,
  drawerLegendValue,
  drawerNav,
  drawerPosition,
  drawerTitle,
  drawerTop,
  ghostButton,
  muted,
} from '@ai-usage/design-system/report';
import { createMemo, For, onCleanup, onMount, Show } from 'solid-js';
import type { FieldFilterKey } from './dashboard-search';
import { lineDeltaLabel, rtkSavedLabel, rtkSavedTitle } from './dashboard-sort';
import {
  type DashboardRow,
  fmtCompact,
  fmtDate,
  fmtDuration,
  fmtMoney,
  fmtNum,
  HarnessBadge,
  median,
  rowKey,
  SegmentBar,
  tokenSegmentClasses,
  UNKNOWN_PRICE_HINT,
} from './shared';

const DetailItem = (props: { label: string; value: string; hint?: string }) => (
  <div class={detailItem} title={props.hint}>
    <div class={detailLabel}>{props.label}</div>
    <div class={detailValue}>{props.value}</div>
  </div>
);

const fmtRatio = (ratio: number) => (ratio >= 10 ? `${Math.round(ratio)}×` : `${ratio.toFixed(1)}×`);

export const SessionDrawer = (props: {
  row: DashboardRow;
  rows: DashboardRow[];
  onClose: () => void;
  onNavigate: (delta: number) => void;
  onFieldFilter: (key: FieldFilterKey, value: string) => void;
}) => {
  let closeButton: HTMLButtonElement | undefined;
  // Move focus in on open and hand it back on close, so keyboard users are
  // not stranded; the inspector itself stays non-modal.
  onMount(() => {
    const previous = document.activeElement;
    closeButton?.focus();
    onCleanup(() => {
      if (previous instanceof HTMLElement && previous.isConnected) previous.focus();
    });
  });

  const position = createMemo(() => props.rows.findIndex((row) => rowKey(row) === rowKey(props.row)));
  const medianCost = createMemo(() =>
    median(props.rows.filter((row) => row.costKnown && row.costApprox > 0).map((row) => row.costApprox)),
  );
  const medianDuration = createMemo(() =>
    median(props.rows.map((row) => row.durationMs ?? 0).filter((duration) => duration > 0)),
  );
  const costRatio = () =>
    props.row.costKnown && props.row.costApprox > 0 && medianCost() > 0 ? props.row.costApprox / medianCost() : null;
  const durationRatio = () =>
    (props.row.durationMs ?? 0) > 0 && medianDuration() > 0 ? (props.row.durationMs ?? 0) / medianDuration() : null;

  const anatomySegments = () => [
    { label: 'Cache read', value: props.row.tokCr, class: tokenSegmentClasses.cacheRead },
    { label: 'Cache write', value: props.row.tokCw, class: tokenSegmentClasses.cacheWrite },
    { label: 'Input', value: props.row.tokIn, class: tokenSegmentClasses.input },
    { label: 'Output', value: props.row.tokOut, class: tokenSegmentClasses.output },
  ];

  return (
    <aside class={drawer} role="dialog" aria-label="Session details">
      <div class={drawerTop}>
        <HarnessBadge name={props.row.harness} />
        <div class={drawerNav}>
          <span class={drawerPosition}>
            {fmtNum(position() + 1)} / {fmtNum(props.rows.length)}
          </span>
          <button
            class={drawerClose}
            type="button"
            aria-label="Previous session (k)"
            title="Previous session (k)"
            disabled={position() <= 0}
            onClick={() => props.onNavigate(-1)}
          >
            ↑
          </button>
          <button
            class={drawerClose}
            type="button"
            aria-label="Next session (j)"
            title="Next session (j)"
            disabled={position() >= props.rows.length - 1}
            onClick={() => props.onNavigate(1)}
          >
            ↓
          </button>
          <button
            ref={closeButton}
            class={drawerClose}
            type="button"
            aria-label="Close session details"
            onClick={() => props.onClose()}
          >
            ✕
          </button>
        </div>
      </div>
      <div class={drawerBody}>
        <div>
          <div class={drawerTitle}>{props.row.sessionLabel}</div>
          <div class={muted}>
            {props.row.providerDisplay} · {props.row.modelLabel}
          </div>
        </div>
        <div>
          <SegmentBar segments={anatomySegments()} ariaLabel="Token anatomy" />
          <div class={drawerLegend} style={{ 'margin-top': '8px' }}>
            <For each={anatomySegments()}>
              {(segment) => (
                <div class={drawerLegendItem} title={`${segment.label}: ${fmtNum(segment.value)} tokens`}>
                  <span class={cx(drawerLegendSwatch, segment.class)} />
                  <span>{segment.label}</span>
                  <span class={drawerLegendValue}>{fmtCompact(segment.value)}</span>
                </div>
              )}
            </For>
          </div>
        </div>
        <Show when={costRatio() != null || durationRatio() != null}>
          <div class={drawerCompare} title="Compared with the median session in the current view">
            <Show when={costRatio() != null}>≈ {fmtRatio(costRatio() ?? 0)} median cost</Show>
            <Show when={costRatio() != null && durationRatio() != null}> · </Show>
            <Show when={durationRatio() != null}>{fmtRatio(durationRatio() ?? 0)} median duration</Show>
          </div>
        </Show>
        <div class={drawerGrid}>
          <DetailItem label="Started" value={fmtDate(props.row.date)} />
          <DetailItem label="Ended" value={fmtDate(props.row.endDate)} />
          <DetailItem label="Total tokens" value={fmtNum(props.row.tokenTotal)} />
          <DetailItem label="RTK savings" value={rtkSavedLabel(props.row)} hint={rtkSavedTitle(props.row)} />
          <DetailItem
            label="API value"
            value={props.row.costKnown ? fmtMoney(props.row.costApprox) : '—'}
            hint={props.row.costKnown ? 'Estimated cost at standard API prices' : UNKNOWN_PRICE_HINT}
          />
          <DetailItem
            label="Actual cost"
            value={fmtMoney(props.row.costActual)}
            hint="Out-of-pocket spend — $0.00 means covered by a subscription"
          />
          <DetailItem
            label="Sub value"
            value={fmtMoney(props.row.costQuota)}
            hint="Cursor export value covered by the subscription quota"
          />
          <DetailItem label="Calls" value={fmtNum(props.row.calls)} />
          <DetailItem label="Turns" value={fmtNum(props.row.turns)} />
          <DetailItem label="Tools" value={fmtNum(props.row.tools)} />
          <DetailItem label="Duration" value={fmtDuration(props.row.durationMs)} />
          <DetailItem label="Lines" value={lineDeltaLabel(props.row)} />
          <DetailItem label="Subagent" value={props.row.subagent ? 'Yes' : 'No'} />
          <Show when={props.row.partial}>
            <DetailItem label="Partial" value="Yes" hint="Local history did not cover the whole session" />
          </Show>
          <Show when={props.row.usageUnavailable}>
            <DetailItem
              label="Usage data"
              value="Unavailable"
              hint="Session came from prompt history, but detailed local token counters are missing"
            />
          </Show>
          <Show when={props.row.ambiguous}>
            <DetailItem
              label="Reconciliation"
              value="Ambiguous"
              hint="Multiple local Cursor sessions matched the same export cluster; totals are best-effort"
            />
          </Show>
        </div>
        <div class={drawerActions}>
          <button
            class={ghostButton}
            type="button"
            onClick={() => props.onFieldFilter('project', props.row.projectKey)}
          >
            Filter project: {props.row.projectKey}
          </button>
          <button class={ghostButton} type="button" onClick={() => props.onFieldFilter('model', props.row.modelKey)}>
            Filter model: {props.row.modelKey}
          </button>
        </div>
      </div>
    </aside>
  );
};
