// apps/web/src/session-table.tsx
import { Checkbox, Popover } from '@ai-usage/design-system';
import { cx } from '@ai-usage/design-system/css';
import {
  desktopTableSurface,
  empty,
  emptyActions,
  ghostButton,
  mobileSummarySurface,
  popoverContent,
  popoverGrid,
  popoverHeader,
  presetButton,
  presetGroup,
  sessionDesktopControl,
  sessionPagingLoadMore,
  sessionSummaryCard,
  sessionSummaryDate,
  sessionSummaryFilter,
  sessionSummaryFilters,
  sessionSummaryFooter,
  sessionSummaryHeader,
  sessionSummaryLoadMore,
  sessionSummaryMobileSort,
  sessionSummaryMobileSortField,
  sessionSummaryMobileSortSelect,
  sessionSummaryOpen,
  sessionSummaryRow,
  sessionSummaryStats,
  sessionSummaryTitle,
  sessionSummaryValue,
  sessionSummaryViewport,
  sessionsTable,
  sortArrow,
  sortButton,
  table,
  tableControls,
  tableWrap,
} from '@ai-usage/design-system/report';
import type { Column, ExpandedState, OnChangeFn, Row, SortingState, VisibilityState } from '@tanstack/solid-table';
import { createSolidTable, flexRender, getCoreRowModel, getExpandedRowModel } from '@tanstack/solid-table';
import { createEffect, createMemo, createSignal, For, onCleanup, onMount, Show } from 'solid-js';
import { measureClientPerf } from './client-perf';
import type { FieldFilterKey } from './dashboard-search';
import { HighlightedText } from './highlighted-text';
import {
  defaultColumnVisibility,
  isSessionColumnVisible,
  type SessionColumnDef,
  sessionColumnHeader,
  sessionColumnLabel,
  sessionColumns,
  visibleSessionColumns,
} from './session-columns';
import {
  browserSessionSurfaceModeEnvironment,
  createSessionSurfaceModeController,
  type SessionSurfaceMode,
} from './session-surface-mode';
import {
  columnVisibilityForSessionPreset,
  sessionColumnPresetForVisibility,
  sessionColumnPresets,
} from './session-table-schema';
import {
  type DashboardRow,
  fmtCompact,
  fmtDate,
  fmtDuration,
  fmtMoney,
  HarnessBadge,
  rowKey,
  UNKNOWN_PRICE_HINT,
} from './shared';

const track = (..._values: unknown[]) => _values.length;
const DESKTOP_ROW_HEIGHT = 43;
const DESKTOP_OVERSCAN_ROWS = 8;
const DESKTOP_PAGE_PREFETCH_ROWS = 12;
const MIN_SESSION_TABLE_WIDTH = 720;

const MobileSessionSummary = (props: {
  onFieldFilter: (key: FieldFilterKey, value: string) => void;
  onHarnessFilter: (value: string) => void;
  onSelect: (row: DashboardRow) => void;
  position: number;
  searchQuery: string;
  selected: boolean;
  tableRow: Row<DashboardRow>;
  total: number;
}) => {
  const row = () => props.tableRow.original;
  const apiValue = () => {
    if (row().usageUnavailable || !row().costKnown) {
      return '—';
    }
    return fmtMoney(row().costApprox);
  };

  return (
    <li aria-posinset={props.position} aria-setsize={props.total} class={sessionSummaryRow}>
      <article class={sessionSummaryCard} data-depth={props.tableRow.depth} data-selected={String(props.selected)}>
        <header class={sessionSummaryHeader}>
          <span class={sessionSummaryDate}>{fmtDate(row().activeDate)}</span>
          <HarnessBadge name={row().harness} onClick={() => props.onHarnessFilter(row().harness)} />
        </header>
        <button
          aria-label={`Inspect session: ${row().sessionLabel}`}
          class={sessionSummaryOpen}
          onClick={() => props.onSelect(row())}
          type="button"
        >
          <span class={sessionSummaryTitle}>
            <HighlightedText query={props.searchQuery} text={row().sessionLabel} />
          </span>
          <span class={sessionSummaryValue} title={row().costKnown ? 'Estimated API value' : UNKNOWN_PRICE_HINT}>
            {apiValue()}
          </span>
        </button>
        <footer class={sessionSummaryFooter}>
          <div class={sessionSummaryFilters}>
            <button
              class={sessionSummaryFilter}
              onClick={() => props.onFieldFilter('project', row().projectKey)}
              title={`Filter by project ${row().projectKey}`}
              type="button"
            >
              {row().projectLabel === '(unknown)' ? 'No project' : row().projectLabel}
            </button>
            <button
              class={sessionSummaryFilter}
              onClick={() => props.onFieldFilter('model', row().modelKey)}
              title={`Filter by model ${row().modelKey}`}
              type="button"
            >
              {row().modelLabel}
            </button>
            <Show when={props.tableRow.getCanExpand()}>
              <button
                class={sessionSummaryFilter}
                onClick={() => props.tableRow.toggleExpanded()}
                title={props.tableRow.getIsExpanded() ? 'Collapse campaign' : 'Expand campaign'}
                type="button"
              >
                {props.tableRow.getIsExpanded() ? 'Hide children' : 'Show children'}
              </button>
            </Show>
          </div>
          <span class={sessionSummaryStats}>
            {fmtCompact(row().freshTokens)} fresh · {fmtCompact(row().tokCr)} cache · {fmtDuration(row().durationMs)}
          </span>
        </footer>
      </article>
    </li>
  );
};

const SortHeader = (props: { column: Column<DashboardRow, unknown>; label: string }) => {
  const meta = () => props.column.columnDef.meta;
  const sortDirection = () => props.column.getIsSorted();

  return (
    <Show fallback={<span class={meta()?.headerClass}>{props.label}</span>} when={props.column.getCanSort()}>
      <button
        class={cx(sortButton, meta()?.headerClass)}
        onClick={(event) => props.column.getToggleSortingHandler()?.(event)}
        title={meta()?.title}
        type="button"
      >
        <span>{props.label}</span>
        <Show when={sortDirection()}>
          {(direction) => (
            <span aria-hidden="true" class={sortArrow}>
              {direction() === 'asc' ? '↑' : '↓'}
            </span>
          )}
        </Show>
      </button>
    </Show>
  );
};

// Folded into a disclosure: column tuning is an occasional task, so it should
// not permanently cost two rows of prime space above the table.
const ColumnVisibilityControl = (props: {
  columnVisibility: VisibilityState;
  hiddenColumnIds?: string[];
  onColumnVisibilityChange: OnChangeFn<VisibilityState>;
}) => {
  const hideableColumns = () =>
    sessionColumns.filter((column) => column.enableHiding !== false && !props.hiddenColumnIds?.includes(column.id));
  const visibleCount = () =>
    visibleSessionColumns(props.columnVisibility).filter((column) => !props.hiddenColumnIds?.includes(column.id))
      .length;
  const setColumnVisible = (id: string, visible: boolean) =>
    props.onColumnVisibilityChange((current) => ({ ...current, [id]: visible }));

  return (
    <Popover
      contentClass={popoverContent}
      trigger={<span>Advanced columns · {visibleCount()} ▾</span>}
      triggerClass={ghostButton}
    >
      <div class={popoverHeader}>
        <span>
          {visibleCount()} of {sessionColumns.length} columns shown
        </span>
        <button
          class={ghostButton}
          onClick={() => props.onColumnVisibilityChange(defaultColumnVisibility)}
          type="button"
        >
          Reset
        </button>
      </div>
      <div class={popoverGrid}>
        <For each={hideableColumns()}>
          {(column) => (
            <Checkbox
              checked={isSessionColumnVisible(props.columnVisibility, column.id)}
              onCheckedChange={(checked) => setColumnVisible(column.id, checked)}
            >
              {sessionColumnLabel(column)}
            </Checkbox>
          )}
        </For>
      </div>
    </Popover>
  );
};

const SessionColumnControls = (props: {
  columnVisibility: VisibilityState;
  hiddenColumnIds?: string[];
  onColumnVisibilityChange: OnChangeFn<VisibilityState>;
}) => {
  const activePreset = () => sessionColumnPresetForVisibility(props.columnVisibility);

  return (
    <fieldset aria-label="Session column presets" class={presetGroup}>
      <For each={sessionColumnPresets}>
        {(preset) => {
          const active = () => activePreset() === preset.id;
          return (
            <button
              aria-pressed={active()}
              class={presetButton}
              data-active={String(active())}
              onClick={() => props.onColumnVisibilityChange(columnVisibilityForSessionPreset(preset.id))}
              type="button"
            >
              {preset.label}
            </button>
          );
        }}
      </For>
      <ColumnVisibilityControl
        columnVisibility={props.columnVisibility}
        onColumnVisibilityChange={props.onColumnVisibilityChange}
        {...(props.hiddenColumnIds ? { hiddenColumnIds: props.hiddenColumnIds } : {})}
      />
    </fieldset>
  );
};

export const SessionTable = (props: {
  campaignChildren?: ReadonlyMap<string, { loading: boolean; nextCursor: string | null }>;
  columnVisibility: VisibilityState;
  groupCampaigns: boolean;
  hasMoreRows?: boolean;
  loading?: boolean;
  loadingMoreRows?: boolean;
  onColumnVisibilityChange: OnChangeFn<VisibilityState>;
  onClearFilters: () => void;
  onFieldFilter: (key: FieldFilterKey, value: string) => void;
  onGroupCampaignsChange: (enabled: boolean) => void;
  onHarnessFilter: (value: string) => void;
  onLoadCampaignChildren?: (campaignKey: string) => void;
  onLoadMoreRows?: () => void;
  onSelect: (row: DashboardRow) => void;
  onSortingChange: OnChangeFn<SortingState>;
  rows: DashboardRow[];
  searchQuery: string;
  selectedKey: string | null;
  sorting: SortingState;
  totalRows?: number;
}) => {
  // A column whose every visible row reads "—" is dead weight; RTK savings
  // only earns its slot when the filtered set actually carries RTK data.
  // Folding this into the visibility state keeps headers and cells in sync.
  const [expanded, setExpanded] = createSignal<ExpandedState>({});
  const [surfaceMode, setSurfaceMode] = createSignal<SessionSurfaceMode>('pending');
  const tableData = createMemo(() => props.rows);
  const hasRtkData = createMemo(() => tableData().some((row) => row.rtkSavedTokens));
  const effectiveVisibility = createMemo(() =>
    hasRtkData() ? props.columnVisibility : { ...props.columnVisibility, rtkSaved: false },
  );
  const dataHiddenColumnIds = () => (hasRtkData() ? [] : ['rtkSaved']);
  const sessionTable = createSolidTable<DashboardRow>({
    get data() {
      return tableData();
    },
    columns: sessionColumns,
    get state() {
      return {
        sorting: props.sorting,
        columnVisibility: effectiveVisibility(),
        expanded: expanded(),
      };
    },
    enableMultiSort: false,
    enableSortingRemoval: false,
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    getSubRows: (row) => row.children ?? [],
    getRowCanExpand: (row) =>
      Boolean(
        row.original.children?.length ||
          (props.groupCampaigns && row.original.campaignKey && props.onLoadCampaignChildren),
      ),
    getRowId: (row) => rowKey(row),
    meta: {
      onFieldFilter: props.onFieldFilter,
      onHarnessFilter: props.onHarnessFilter,
      get searchQuery() {
        return props.searchQuery;
      },
    },
    onColumnVisibilityChange: props.onColumnVisibilityChange,
    onExpandedChange: (updater) =>
      setExpanded((current) => {
        const next = typeof updater === 'function' ? updater(current) : updater;
        if (typeof next !== 'object') {
          return next;
        }
        const currentRecord = typeof current === 'object' ? current : {};
        for (const [rowId, isExpanded] of Object.entries(next)) {
          if (!(isExpanded && !currentRecord[rowId])) {
            continue;
          }
          const campaignKey = props.rows.find((row) => rowKey(row) === rowId)?.campaignKey;
          if (campaignKey) {
            props.onLoadCampaignChildren?.(campaignKey);
          }
        }
        return next;
      }),
    onSortingChange: props.onSortingChange,
  });
  const visibleColumns = createMemo(() =>
    visibleSessionColumns(effectiveVisibility())
      .map((columnDef) => ({ columnDef, tableColumn: sessionTable.getColumn(columnDef.id) }))
      .filter((column): column is { columnDef: SessionColumnDef; tableColumn: Column<DashboardRow, unknown> } =>
        Boolean(column.tableColumn),
      ),
  );
  const tableMinWidth = () =>
    Math.max(
      MIN_SESSION_TABLE_WIDTH,
      visibleColumns().reduce((sum, { columnDef }) => sum + (columnDef.meta?.widthPx ?? 140), 0),
    );
  const [desktopViewportEl, setDesktopViewportEl] = createSignal<HTMLDivElement>();
  const [tableViewport, setTableViewport] = createSignal({ height: 520, scrollTop: 0 });
  const updateTableViewport = (): void => {
    const element = desktopViewportEl();
    const next = {
      height: element?.clientHeight || 520,
      scrollTop: element?.scrollTop ?? 0,
    };
    setTableViewport((current) =>
      current.height === next.height && current.scrollTop === next.scrollTop ? current : next,
    );
  };
  const rowModelRows = createMemo(() => {
    track(tableData(), props.sorting);
    return measureClientPerf(
      'aiUsage.web.client.compute.sessionTableRowModel',
      () => sessionTable.getRowModel().rows,
      (rows) => ({ rows: rows.length }),
    );
  });
  const mobileRows = createMemo(() => (surfaceMode() === 'mobile' ? rowModelRows() : []));
  const visibleColumnCount = () => visibleColumns().length;
  const virtualRows = createMemo(() => {
    const rows = rowModelRows();
    if (surfaceMode() !== 'desktop') {
      return {
        bottomHeight: 0,
        lastIndex: -1,
        rows: [],
        topHeight: 0,
      };
    }
    const viewport = tableViewport();
    const start = Math.max(0, Math.floor(viewport.scrollTop / DESKTOP_ROW_HEIGHT) - DESKTOP_OVERSCAN_ROWS);
    const end = Math.min(
      rows.length,
      start + Math.ceil(viewport.height / DESKTOP_ROW_HEIGHT) + DESKTOP_OVERSCAN_ROWS * 2,
    );
    return measureClientPerf(
      'aiUsage.web.client.compute.sessionTableVirtualRows',
      () => ({
        bottomHeight: Math.max(0, rows.length - end) * DESKTOP_ROW_HEIGHT,
        lastIndex: end - 1,
        rows: rows.slice(start, end).map((row, index) => ({ index: start + index, row })),
        topHeight: start * DESKTOP_ROW_HEIGHT,
      }),
      (result) => ({ rows: result.rows.length }),
    );
  });
  const shouldLoadNextDesktopPage = createMemo(() => {
    if (surfaceMode() !== 'desktop' || !props.hasMoreRows || props.loadingMoreRows || !props.onLoadMoreRows) {
      return false;
    }
    return virtualRows().lastIndex >= rowModelRows().length - DESKTOP_PAGE_PREFETCH_ROWS;
  });
  const [mobilePagingEl, setMobilePagingEl] = createSignal<HTMLDivElement>();
  const [mobilePagingActivated, setMobilePagingActivated] = createSignal(false);
  const [mobileViewportRevision, setMobileViewportRevision] = createSignal(0);
  const mobilePagingNearViewport = createMemo(() => {
    track(mobileViewportRevision(), rowModelRows().length);
    const element = mobilePagingEl();
    return (
      surfaceMode() === 'mobile' &&
      element !== undefined &&
      element.getBoundingClientRect().top <= window.innerHeight + 240
    );
  });

  onMount(() => {
    const controller = createSessionSurfaceModeController(browserSessionSurfaceModeEnvironment());
    onCleanup(controller.start(setSurfaceMode));
  });

  createEffect(() => {
    const element = mobilePagingEl();
    if (!(element && surfaceMode() === 'mobile')) {
      return;
    }
    const updateMobileViewport = (): void => {
      setMobileViewportRevision((revision) => revision + 1);
    };
    window.addEventListener('resize', updateMobileViewport);
    window.addEventListener('scroll', updateMobileViewport, { passive: true });
    updateMobileViewport();
    onCleanup(() => {
      window.removeEventListener('resize', updateMobileViewport);
      window.removeEventListener('scroll', updateMobileViewport);
    });
  });

  createEffect(() => {
    if (mobilePagingNearViewport()) {
      setMobilePagingActivated(true);
    }
  });

  createEffect(() => {
    if (surfaceMode() === 'mobile' && mobilePagingActivated() && props.hasMoreRows && !props.loadingMoreRows) {
      props.onLoadMoreRows?.();
    }
  });

  createEffect(() => {
    if (shouldLoadNextDesktopPage()) {
      props.onLoadMoreRows?.();
    }
  });

  createEffect(() => {
    const element = desktopViewportEl();
    if (!(surfaceMode() === 'desktop' && element)) {
      return;
    }
    updateTableViewport();
    const observer = new ResizeObserver(updateTableViewport);
    observer.observe(element);
    onCleanup(() => observer.disconnect());
  });

  let previousRowKeys: string[] = [];
  createEffect(() => {
    track(props.sorting);
    const nextRowKeys = tableData().map(rowKey);
    const existingRowsUnchanged =
      previousRowKeys.length > 0 &&
      previousRowKeys.length <= nextRowKeys.length &&
      previousRowKeys.every((key, index) => nextRowKeys[index] === key);
    previousRowKeys = nextRowKeys;
    if (existingRowsUnchanged) {
      return;
    }
    setMobilePagingActivated(false);
    if (surfaceMode() === 'desktop') {
      desktopViewportEl()?.scrollTo({ top: 0 });
      updateTableViewport();
    }
  });

  const expandedCampaignLoads = createMemo(() => {
    const expansion = expanded();
    if (typeof expansion !== 'object') {
      return [];
    }
    return props.rows.flatMap((row) => {
      const campaignKey = row.campaignKey;
      if (!(campaignKey && expansion[rowKey(row)])) {
        return [];
      }
      const state = props.campaignChildren?.get(campaignKey);
      return state?.loading || state?.nextCursor
        ? [{ campaignKey, loading: state?.loading === true, sessionLabel: row.sessionLabel }]
        : [];
    });
  });

  createEffect(() => {
    if (!props.groupCampaigns) {
      setExpanded({});
      return;
    }
    const selectedKey = props.selectedKey;
    if (!selectedKey) {
      return;
    }
    const parent = props.rows.find((row) => row.children?.some((child) => rowKey(child) === selectedKey));
    if (!parent) {
      return;
    }
    setExpanded((current) => ({
      ...(typeof current === 'object' ? current : {}),
      [rowKey(parent)]: true,
    }));
  });

  const activeSort = () => props.sorting[0] ?? { desc: true, id: 'date' };

  return (
    <Show
      fallback={
        <Show
          fallback={
            <div class={empty}>
              <div class={emptyActions}>
                <span>No sessions match the current filters</span>
                <button class={ghostButton} onClick={() => props.onClearFilters()} type="button">
                  Clear filters
                </button>
              </div>
            </div>
          }
          when={props.loading}
        >
          <div aria-busy="true" aria-live="polite" class={empty}>
            Loading sessions…
          </div>
        </Show>
      }
      when={props.rows.length}
    >
      <div class={tableControls}>
        <Checkbox
          checked={props.groupCampaigns}
          onCheckedChange={(checked) => {
            props.onGroupCampaignsChange(checked);
            setExpanded({});
          }}
        >
          Group campaigns
        </Checkbox>
        <Show when={surfaceMode() === 'desktop'}>
          <div class={sessionDesktopControl}>
            <SessionColumnControls
              columnVisibility={props.columnVisibility}
              hiddenColumnIds={dataHiddenColumnIds()}
              onColumnVisibilityChange={props.onColumnVisibilityChange}
            />
          </div>
        </Show>
        <Show when={surfaceMode() === 'mobile'}>
          <div class={sessionSummaryMobileSort}>
            <label class={sessionSummaryMobileSortField}>
              <span>Sort by</span>
              <select
                aria-label="Sort mobile session summaries"
                class={sessionSummaryMobileSortSelect}
                onChange={(event) =>
                  props.onSortingChange([{ desc: activeSort().desc, id: event.currentTarget.value }])
                }
                value={activeSort().id}
              >
                <For each={sessionColumns}>
                  {(column) => <option value={column.id}>{sessionColumnLabel(column)}</option>}
                </For>
              </select>
            </label>
            <button
              aria-label={activeSort().desc ? 'Sort ascending' : 'Sort descending'}
              class={ghostButton}
              onClick={() => props.onSortingChange([{ desc: !activeSort().desc, id: activeSort().id }])}
              type="button"
            >
              {activeSort().desc ? 'Descending ↓' : 'Ascending ↑'}
            </button>
          </div>
        </Show>
      </div>
      <Show when={surfaceMode() === 'pending'}>
        <div aria-busy="true" class={tableWrap} data-session-surface="pending">
          Preparing sessions…
        </div>
      </Show>
      <Show when={surfaceMode() === 'desktop'}>
        <div
          class={cx(tableWrap, surfaceMode() === 'desktop' ? desktopTableSurface : undefined)}
          data-session-surface={surfaceMode()}
          onScroll={updateTableViewport}
          ref={setDesktopViewportEl}
        >
          <table class={cx(table, sessionsTable)} style={{ 'min-width': `${tableMinWidth()}px` }}>
            <thead>
              <tr>
                <For each={visibleColumns()}>
                  {({ columnDef, tableColumn }) => (
                    <th
                      class={columnDef.meta?.headerClass}
                      style={{ width: `${columnDef.meta?.widthPx ?? 140}px` }}
                      title={columnDef.meta?.title}
                    >
                      <SortHeader column={tableColumn} label={sessionColumnHeader(columnDef)} />
                    </th>
                  )}
                </For>
              </tr>
            </thead>
            <tbody>
              <Show when={virtualRows().topHeight > 0}>
                <tr data-virtual-spacer="top">
                  <td
                    colSpan={visibleColumnCount()}
                    style={{ height: `${virtualRows().topHeight}px`, padding: '0', border: '0' }}
                  />
                </tr>
              </Show>
              <For each={virtualRows().rows}>
                {(virtualRow) => {
                  const tableRow = virtualRow.row;
                  return (
                    <tr
                      data-depth={tableRow.depth}
                      data-index={virtualRow.index}
                      data-selected={String(props.selectedKey === tableRow.id)}
                      onClick={() => props.onSelect(tableRow.original)}
                      onKeyDown={(event) => {
                        if (event.target !== event.currentTarget) {
                          return;
                        }
                        if (event.key !== 'Enter' && event.key !== ' ') {
                          return;
                        }
                        event.preventDefault();
                        props.onSelect(tableRow.original);
                      }}
                      tabIndex={0}
                    >
                      <For each={tableRow.getVisibleCells()}>
                        {(cell) => (
                          <td class={cell.column.columnDef.meta?.cellClass}>
                            {flexRender(cell.column.columnDef.cell, cell.getContext())}
                          </td>
                        )}
                      </For>
                    </tr>
                  );
                }}
              </For>
              <Show when={virtualRows().bottomHeight > 0}>
                <tr data-virtual-spacer="bottom">
                  <td
                    colSpan={visibleColumnCount()}
                    style={{ height: `${virtualRows().bottomHeight}px`, padding: '0', border: '0' }}
                  />
                </tr>
              </Show>
            </tbody>
          </table>
        </div>
      </Show>
      <Show when={surfaceMode() === 'mobile'}>
        <ul
          aria-label="Session summaries"
          class={cx(mobileSummarySurface, sessionSummaryViewport)}
          data-session-surface="mobile"
        >
          <For each={mobileRows()}>
            {(tableRow, index) => (
              <MobileSessionSummary
                onFieldFilter={props.onFieldFilter}
                onHarnessFilter={props.onHarnessFilter}
                onSelect={props.onSelect}
                position={index() + 1}
                searchQuery={props.searchQuery}
                selected={props.selectedKey === tableRow.id}
                tableRow={tableRow}
                total={props.totalRows ?? rowModelRows().length}
              />
            )}
          </For>
        </ul>
        <div
          aria-hidden="true"
          class={sessionSummaryLoadMore}
          data-session-paging-sentinel="mobile"
          ref={setMobilePagingEl}
        />
      </Show>
      <For each={expandedCampaignLoads()}>
        {(campaign) => (
          <div class={sessionPagingLoadMore}>
            <button
              aria-label={`Load more sessions in campaign ${campaign.sessionLabel}`}
              class={ghostButton}
              disabled={campaign.loading}
              onClick={() => props.onLoadCampaignChildren?.(campaign.campaignKey)}
              type="button"
            >
              {campaign.loading ? 'Loading campaign sessions…' : `Load more sessions in ${campaign.sessionLabel}`}
            </button>
          </div>
        )}
      </For>
      <Show when={props.loadingMoreRows}>
        <div aria-live="polite" class={sessionPagingLoadMore}>
          Loading more sessions…
        </div>
      </Show>
    </Show>
  );
};

// apps/web/src/lib/features/sessions/table/session-table.svelte
<!-- biome-ignore-all lint/a11y/noNoninteractiveTabindex lint/a11y/useValidAriaValues: virtualized rows preserve the legacy keyboard surface; Svelte emits the closed dynamic WAI-ARIA values asserted by SSR tests -->
<script lang="ts">
  import { cx } from '@ai-usage/design-system/css';
  import Checkbox from '@ai-usage/design-system/svelte/checkbox';
  import HarnessBadge from '@ai-usage/design-system/svelte/harness-badge';
  import {
    dateCell,
    desktopTableSurface,
    empty,
    emptyActions,
    ghostButton,
    highlightMark,
    mobileSummarySurface,
    modelCell,
    numCell,
    presetButton,
    presetGroup,
    right,
    sessionCell,
    sessionPagingLoadMore,
    sessionSummaryCard,
    sessionSummaryDate,
    sessionSummaryFilter,
    sessionSummaryFilters,
    sessionSummaryFooter,
    sessionSummaryHeader,
    sessionSummaryMobileSort,
    sessionSummaryMobileSortField,
    sessionSummaryMobileSortSelect,
    sessionSummaryOpen,
    sessionSummaryRow,
    sessionSummaryStats,
    sessionSummaryTitle,
    sessionSummaryValue,
    sessionSummaryViewport,
    sessionsTable,
    sessionViewportSurface,
    sortArrow,
    sortButton,
    table as tableClass,
    tableControls,
    tableWrap,
  } from '@ai-usage/design-system/svelte/passive';
  import Popover from '@ai-usage/design-system/svelte/popover';
  import type { SessionPresentationRow } from '@ai-usage/report-core/session-query';
  import type { ExpandedState } from '@tanstack/table-core';
  import { onMount, untrack } from 'svelte';
  import { calculateSessionViewportHeight } from '../../../../session-row-window';
  import {
    browserSessionSurfaceModeEnvironment,
    createSessionSurfaceModeController,
    type SessionSurfaceMode,
  } from '../../../../session-surface-mode';
  import {
    columnVisibilityForSessionPreset,
    defaultColumnVisibility,
    isSessionColumnVisible,
    type SessionColumnId,
    sessionColumnPresetForVisibility,
    sessionColumnPresets,
    sessionColumnSchema,
  } from '../../../../session-table-schema';
  import { fmtDate } from '../../../foundation/presentation/format';
  import type { StateChangeHandler, TableSortingState, TableVisibilityState } from '../../../foundation/table/state';
  import type { SessionCampaignPage } from '../../../query/options/session-window';
  import SessionCell from './session-cell.svelte';
  import {
    projectSessionCell,
    sessionSortDescendingByDefault,
    sessionSortForColumnChange,
    shouldSelectSessionRowForKey,
  } from './session-cell-projection';
  import { sessionTableColumns, visibleSessionTableColumns } from './session-columns';
  import { createSessionTableModel, toggleSessionRowExpanded } from './session-table-model';
  import { popoverGrid, popoverHeader } from './session-table-styles';
  import {
    isSessionPagePrefetchRequired,
    projectSessionVirtualRows,
    sessionVirtualBudgets,
  } from './session-virtualization';

  const SESSION_VIEWPORT_BOTTOM_INSET = 24;
  const SESSION_VIEWPORT_FALLBACK_HEIGHT = 520;
  const MIN_SESSION_TABLE_WIDTH = 720;
  const DESKTOP_MINIMUM_VIEWPORT_HEIGHT = sessionVirtualBudgets.desktop.rowHeight * 3;
  const MOBILE_MINIMUM_VIEWPORT_HEIGHT = sessionVirtualBudgets.mobile.rowHeight;

  interface Props {
    campaignChildren?: ReadonlyMap<string, SessionCampaignPage>;
    columnVisibility: TableVisibilityState;
    hasMoreRows?: boolean;
    initialExpanded?: ExpandedState;
    initialSurfaceMode?: Exclude<SessionSurfaceMode, 'pending'>;
    initialWindowAnchor: boolean;
    loading?: boolean;
    loadingMoreRows?: boolean;
    onClearFilters: () => void;
    onColumnVisibilityChange: StateChangeHandler<TableVisibilityState>;
    onFieldFilter: (key: 'campaign' | 'model' | 'project' | 'provider', value: string) => void;
    onHarnessFilter: (value: string) => void;
    onInitialWindowAnchor: () => void;
    onLoadCampaignChildren?: (campaignKey: string) => void;
    onLoadMoreRows?: () => void;
    onSelect: (row: SessionPresentationRow) => void;
    onSortingChange: StateChangeHandler<TableSortingState>;
    queryResetKey: string;
    rows: SessionPresentationRow[];
    searchQuery?: string;
    selectedRowId: string | null;
    sorting: TableSortingState;
    totalRows?: number;
  }

  let {
    campaignChildren = new Map(),
    columnVisibility,
    hasMoreRows = false,
    initialExpanded = {},
    initialWindowAnchor,
    loading = false,
    loadingMoreRows = false,
    onClearFilters,
    onColumnVisibilityChange,
    onFieldFilter,
    onHarnessFilter,
    onInitialWindowAnchor,
    onLoadCampaignChildren,
    onLoadMoreRows,
    onSelect,
    onSortingChange,
    queryResetKey,
    rows,
    searchQuery = '',
    selectedRowId,
    sorting,
    initialSurfaceMode = 'desktop',
    totalRows,
  }: Props = $props();

  let expanded = $state<ExpandedState>(untrack(() => initialExpanded));
  let mode = $state<SessionSurfaceMode>(untrack(() => initialSurfaceMode));
  let scrollTop = $state(0);
  let viewportHeight = $state(520);
  let surfaceElement = $state<HTMLElement>();
  let sessionRegionStartElement = $state<HTMLElement>();
  let initializedSurfaceElement = $state<HTMLElement>();
  let windowAnchorConsumed = $state(false);
  let previousResetKey = $state('');
  let pagingSignature = $state('');
  let pendingFocusIndex = $state<number>();

  const hasRtkData = $derived(rows.some((row) => Boolean(row.rtkSavedTokens)));
  const effectiveVisibility = $derived(hasRtkData ? columnVisibility : { ...columnVisibility, rtkSaved: false });
  const chooserColumns = $derived(
    sessionTableColumns.filter((entry) => entry.id !== 'session' && (entry.id !== 'rtkSaved' || hasRtkData)),
  );
  const model = $derived(
    createSessionTableModel({
      canLoadCampaignChildren: Boolean(onLoadCampaignChildren),
      expanded,
      rows,
      sorting,
      visibility: effectiveVisibility,
    }),
  );
  const visibleColumns = $derived(visibleSessionTableColumns(effectiveVisibility));
  const activeMode = $derived(mode === 'mobile' ? 'mobile' : 'desktop');
  const virtual = $derived(
    projectSessionVirtualRows({ mode: activeMode, rows: model.rows, scrollTop, viewportHeight }),
  );
  const activeSort = $derived(sorting[0] ?? { desc: true, id: 'date' });
  const activePreset = $derived(sessionColumnPresetForVisibility(columnVisibility));
  const visibleColumnWidthTotal = $derived(visibleColumns.reduce((total, entry) => total + entry.meta.widthPx, 0));
  const tableMinWidth = $derived(
    activePreset ? MIN_SESSION_TABLE_WIDTH : Math.max(MIN_SESSION_TABLE_WIDTH, visibleColumnWidthTotal),
  );
  const columnWidth = (width: number): string =>
    activePreset ? `${(width / visibleColumnWidthTotal) * 100}%` : `${width}px`;
  const cellClass = (id: SessionColumnId, align: 'left' | 'right'): string =>
    cx(
      align === 'right' ? numCell : undefined,
      id === 'date' ? dateCell : undefined,
      id === 'model' ? modelCell : undefined,
      id === 'session' ? sessionCell : undefined,
    );

  const ariaSortFor = (id: SessionColumnId): 'ascending' | 'descending' | 'none' => {
    if (activeSort.id !== id) {
      return 'none';
    }
    return activeSort.desc ? 'descending' : 'ascending';
  };

  const updateViewportFor = (element: HTMLElement, surfaceMode: 'desktop' | 'mobile'): void => {
    if (surfaceElement !== element || activeMode !== surfaceMode) {
      return;
    }
    const minimumHeight = surfaceMode === 'desktop' ? DESKTOP_MINIMUM_VIEWPORT_HEIGHT : MOBILE_MINIMUM_VIEWPORT_HEIGHT;
    const nextHeight = calculateSessionViewportHeight({
      bottomInset: SESSION_VIEWPORT_BOTTOM_INSET,
      minimumHeight,
      viewportHeight: window.innerHeight,
    });
    const cssHeight = `${nextHeight}px`;
    if (element.style.getPropertyValue('--session-surface-height') !== cssHeight) {
      element.style.setProperty('--session-surface-height', cssHeight);
    }
    scrollTop = element.scrollTop;
    viewportHeight = element.clientHeight || SESSION_VIEWPORT_FALLBACK_HEIGHT;
  };

  const updateViewport = (): void => {
    if (surfaceElement) {
      updateViewportFor(surfaceElement, activeMode);
    }
  };

  const setSurfaceElement = (element: HTMLElement): void => {
    surfaceElement = element;
    updateViewport();
  };

  onMount(() => {
    const controller = createSessionSurfaceModeController(browserSessionSurfaceModeEnvironment());
    return controller.start((nextMode) => {
      mode = nextMode;
      scrollTop = 0;
      surfaceElement?.scrollTo({ top: 0 });
      updateViewport();
    });
  });

  $effect(() => {
    const activeSurface = surfaceElement;
    const observedMode = activeMode;
    if (!activeSurface) {
      return;
    }
    const synchronize = (): void => updateViewportFor(activeSurface, observedMode);
    synchronize();
    // No window `scroll` listener: the height no longer depends on where the
    // surface sits, and recomputing it on scroll is what made the document grow
    // under the reader. The surface's own `onscroll` still drives the row window.
    const observer = new ResizeObserver(synchronize);
    observer.observe(activeSurface);
    window.addEventListener('resize', synchronize);
    return () => {
      observer.disconnect();
      window.removeEventListener('resize', synchronize);
    };
  });

  $effect(() => {
    const activeSurface = surfaceElement;
    const regionStart = sessionRegionStartElement;
    const shouldAnchorWindow = initialWindowAnchor && !windowAnchorConsumed;
    if (initializedSurfaceElement === activeSurface || !activeSurface || (shouldAnchorWindow && !regionStart)) {
      return;
    }
    const frame = window.requestAnimationFrame(() => {
      initializedSurfaceElement = activeSurface;
      activeSurface.style.removeProperty('--session-surface-height');
      if (shouldAnchorWindow) {
        windowAnchorConsumed = true;
        regionStart?.scrollIntoView({ block: 'start' });
        onInitialWindowAnchor();
      }
      updateViewportFor(activeSurface, activeMode);
    });
    return () => window.cancelAnimationFrame(frame);
  });

  $effect(() => {
    if (queryResetKey !== previousResetKey) {
      previousResetKey = queryResetKey;
      pagingSignature = '';
      expanded = {};
      scrollTop = 0;
      surfaceElement?.scrollTo({ top: 0 });
    }
  });

  $effect(() => {
    const required = isSessionPagePrefetchRequired({
      endIndex: virtual.endIndex,
      hasMore: hasMoreRows,
      loading: loadingMoreRows,
      mode: activeMode,
      rowCount: model.rows.length,
    });
    const signature = `${queryResetKey}:${activeMode}:${model.rows.length}:${virtual.endIndex}`;
    if (required && signature !== pagingSignature) {
      pagingSignature = signature;
      onLoadMoreRows?.();
    }
  });

  const changeSort = (id: SessionColumnId): void => {
    const current = sorting[0];
    const desc = current?.id === id ? !current.desc : sessionSortDescendingByDefault(id);
    onSortingChange([{ desc, id }]);
  };
  const changeSortColumn = (id: SessionColumnId): void => {
    onSortingChange(sessionSortForColumnChange(sorting, id));
  };

  const setColumnVisible = (id: SessionColumnId, visible: boolean): void => {
    onColumnVisibilityChange((current) => ({ ...current, [id]: visible }));
  };

  const toggleExpanded = (row: SessionPresentationRow): void => {
    const wasExpanded = typeof expanded === 'object' && Boolean(expanded[row.rowId]);
    expanded = toggleSessionRowExpanded(expanded, row.rowId);
    if (!wasExpanded && row.campaignKey && !row.children?.length) {
      onLoadCampaignChildren?.(row.campaignKey);
    }
  };

  const onRowKeydown = (event: KeyboardEvent, row: SessionPresentationRow, index: number, activate = true): void => {
    if (shouldSelectSessionRowForKey(event.key, !activate)) {
      event.preventDefault();
      onSelect(row);
      return;
    }
    if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp') {
      return;
    }
    event.preventDefault();
    const targetIndex = Math.max(0, Math.min(model.rows.length - 1, index + (event.key === 'ArrowDown' ? 1 : -1)));
    const target = surfaceElement?.querySelector<HTMLElement>(`[data-session-index="${targetIndex}"]`);
    if (target) {
      pendingFocusIndex = undefined;
      target.focus();
      return;
    }
    pendingFocusIndex = targetIndex;
    surfaceElement?.scrollTo({ top: targetIndex * (activeMode === 'desktop' ? 43 : 188) });
  };

  $effect(() => {
    if (
      pendingFocusIndex === undefined ||
      typeof window === 'undefined' ||
      pendingFocusIndex < virtual.startIndex ||
      pendingFocusIndex >= virtual.endIndex
    ) {
      return;
    }
    const frame = window.requestAnimationFrame(() => {
      const target = surfaceElement?.querySelector<HTMLElement>(`[data-session-index="${pendingFocusIndex}"]`);
      if (target) {
        pendingFocusIndex = undefined;
        target.focus();
      }
    });
    return () => window.cancelAnimationFrame(frame);
  });
</script>

{#if rows.length === 0}
  <div class={empty} data-session-empty>
    {#if loading}
      <span aria-live="polite">Loading sessions…</span>
    {:else}
      <div class={emptyActions}>
        <span>No sessions match the current filters</span>
        <button class={ghostButton} onclick={onClearFilters} type="button">Clear filters</button>
      </div>
    {/if}
  </div>
{:else}
  <section aria-label="Sessions" data-session-mode={activeMode} data-session-table-owner>
    <div class={tableControls} data-session-region-start bind:this={sessionRegionStartElement}>
      {#if activeMode === 'desktop'}
        <fieldset aria-label="Session column presets" class={presetGroup}>
          {#each sessionColumnPresets as preset (preset.id)}
            {@const active = activePreset === preset.id}
            <button
              aria-pressed={active}
              class={presetButton}
              data-active={String(active)}
              data-default={String(preset.id === 'work')}
              onclick={() => onColumnVisibilityChange(columnVisibilityForSessionPreset(preset.id))}
              type="button"
            >
              {preset.label}
            </button>
          {/each}
          <Popover triggerClass={ghostButton}>
            {#snippet trigger()}
              Advanced columns · {visibleColumns.length} ▾
            {/snippet}
            <div class={popoverHeader}>
              <span>{visibleColumns.length} of {sessionColumnSchema.length} columns shown</span>
              <button
                class={ghostButton}
                onclick={() => onColumnVisibilityChange(defaultColumnVisibility)}
                type="button"
              >
                Reset
              </button>
            </div>
            <div class={popoverGrid}>
              {#each chooserColumns as entry (entry.id)}
                <Checkbox
                  checked={isSessionColumnVisible(columnVisibility, entry.id)}
                  onCheckedChange={(checked) => setColumnVisible(entry.id, checked)}
                >
                  {entry.meta.label}
                </Checkbox>
              {/each}
            </div>
          </Popover>
        </fieldset>
      {:else}
        <div class={sessionSummaryMobileSort}>
          <label class={sessionSummaryMobileSortField}>
            <span>Sort by</span>
            <select
              aria-label="Sort mobile session summaries"
              class={sessionSummaryMobileSortSelect}
              onchange={(event) => changeSortColumn(event.currentTarget.value as SessionColumnId)}
              value={activeSort.id}
            >
              {#each sessionTableColumns as entry (entry.id)}
                <option value={entry.id}>{entry.meta.label}</option>
              {/each}
            </select>
          </label>
          <button
            aria-label={activeSort.desc ? 'Sort ascending' : 'Sort descending'}
            class={ghostButton}
            onclick={() => changeSort(activeSort.id as SessionColumnId)}
            type="button"
          >
            {activeSort.desc ? 'Descending ↓' : 'Ascending ↑'}
          </button>
        </div>
      {/if}
    </div>

    {#if activeMode === 'desktop'}
      <div
        class={cx(tableWrap, sessionViewportSurface, desktopTableSurface)}
        data-session-surface="desktop"
        onscroll={updateViewport}
        bind:this={surfaceElement}
        use:setSurfaceElement
      >
        <table
          aria-rowcount={totalRows ?? model.rows.length}
          class={cx(tableClass, sessionsTable)}
          style:min-width={`${tableMinWidth}px`}
        >
          <thead>
            <tr>
              {#each visibleColumns as entry (entry.id)}
                <th
                  aria-sort={ariaSortFor(entry.id)}
                  class={entry.meta.align === 'right' ? right : undefined}
                  scope="col"
                  title={entry.meta.title}
                  style:width={columnWidth(entry.meta.widthPx)}
                >
                  <button class={sortButton} onclick={() => changeSort(entry.id)} type="button">
                    <span>{typeof entry.header === 'string' ? entry.header : entry.meta.label}</span>
                    {#if activeSort.id === entry.id}
                      <span aria-hidden="true" class={sortArrow}>{activeSort.desc ? '↓' : '↑'}</span>
                    {/if}
                  </button>
                </th>
              {/each}
            </tr>
          </thead>
          <tbody>
            {#if virtual.topHeight > 0}
              <tr aria-hidden="true" data-virtual-spacer="top">
                <td
                  colspan={visibleColumns.length}
                  style:border="0"
                  style:height={`${virtual.topHeight}px`}
                  style:padding="0"
                ></td>
              </tr>
            {/if}
            {#each virtual.rows as virtualRow (virtualRow.row.id)}
              <tr
                data-depth={virtualRow.row.depth}
                data-index={virtualRow.index}
                data-selected={selectedRowId === virtualRow.row.id}
                data-session-index={virtualRow.index}
                data-session-row-id={virtualRow.row.id}
                onclick={() => onSelect(virtualRow.row.original)}
                onkeydown={(event) => onRowKeydown(event, virtualRow.row.original, virtualRow.index)}
                tabindex="0"
              >
                {#each visibleColumns as entry (entry.id)}
                  <td class={cellClass(entry.id, entry.meta.align)}>
                    <SessionCell
                      canExpand={virtualRow.row.getCanExpand()}
                      columnId={entry.id}
                      depth={virtualRow.row.depth}
                      expanded={virtualRow.row.getIsExpanded()}
                      {onFieldFilter}
                      {onHarnessFilter}
                      onToggleExpanded={() => toggleExpanded(virtualRow.row.original)}
                      query={searchQuery}
                      row={virtualRow.row.original}
                    />
                  </td>
                {/each}
              </tr>
            {/each}
            {#if virtual.bottomHeight > 0}
              <tr aria-hidden="true" data-virtual-spacer="bottom">
                <td
                  colspan={visibleColumns.length}
                  style:border="0"
                  style:height={`${virtual.bottomHeight}px`}
                  style:padding="0"
                ></td>
              </tr>
            {/if}
          </tbody>
        </table>
      </div>
    {:else}
      <ul
        aria-label="Session summaries"
        class={cx(mobileSummarySurface, sessionSummaryViewport, sessionViewportSurface)}
        data-session-list-gap="0"
        data-session-list-padding="0"
        data-session-surface="mobile"
        onscroll={updateViewport}
        bind:this={surfaceElement}
        use:setSurfaceElement
      >
        {#if virtual.topHeight > 0}
          <li aria-hidden="true" data-virtual-spacer="top" style:height={`${virtual.topHeight}px`}></li>
        {/if}
        {#each virtual.rows as virtualRow (virtualRow.row.id)}
          {@const mobileSession = projectSessionCell(virtualRow.row.original, 'session', searchQuery)}
          {@const mobileValue = projectSessionCell(virtualRow.row.original, 'cost', searchQuery)}
          {@const mobileFresh = projectSessionCell(virtualRow.row.original, 'fresh', searchQuery)}
          {@const mobileCache = projectSessionCell(virtualRow.row.original, 'cache', searchQuery)}
          {@const mobileDuration = projectSessionCell(virtualRow.row.original, 'duration', searchQuery)}
          <li
            aria-posinset={virtualRow.index + 1}
            aria-setsize={Math.max(totalRows ?? 0, model.rows.length)}
            class={sessionSummaryRow}
            data-depth={virtualRow.row.depth}
            data-index={virtualRow.index}
            data-session-row-height="188"
            data-session-row-id={virtualRow.row.id}
          >
            <article
              class={sessionSummaryCard}
              data-depth={virtualRow.row.depth}
              data-selected={selectedRowId === virtualRow.row.id}
              data-session-card-height="180"
            >
              <header class={sessionSummaryHeader}>
                <span class={sessionSummaryDate}>{fmtDate(virtualRow.row.original.activeDate)}</span>
                <HarnessBadge
                  name={virtualRow.row.original.harness}
                  onClick={() => onHarnessFilter(virtualRow.row.original.harness)}
                />
              </header>
              <button
                aria-label={mobileSession.kind === 'session'
                  ? `Inspect session: ${mobileSession.segments.map(({ text }) => text).join('')}`
                  : undefined}
                class={sessionSummaryOpen}
                data-session-index={virtualRow.index}
                onclick={() => onSelect(virtualRow.row.original)}
                onkeydown={(event) => onRowKeydown(event, virtualRow.row.original, virtualRow.index, false)}
                tabindex="0"
                type="button"
              >
                <span class={sessionSummaryTitle}>
                  {#if mobileSession.kind === 'session'}
                    {#each mobileSession.segments as segment, index (`mobile:${index}:${segment.text}`)}
                      {#if segment.match}
                        <mark class={highlightMark}>{segment.text}</mark>
                      {:else}
                        {segment.text}
                      {/if}
                    {/each}
                  {/if}
                </span>
                {#if mobileValue.kind === 'value'}
                  <span class={sessionSummaryValue} title={mobileValue.title}>{mobileValue.label}</span>
                {/if}
              </button>
              <footer class={sessionSummaryFooter}>
                <div class={sessionSummaryFilters}>
                  <button
                    class={sessionSummaryFilter}
                    onclick={() => onFieldFilter('project', virtualRow.row.original.projectKey)}
                    title={`Filter by project ${virtualRow.row.original.projectLabel}`}
                    type="button"
                  >
                    {virtualRow.row.original.projectLabel === '(unknown)'
                      ? 'No project'
                      : virtualRow.row.original.projectLabel}
                  </button>
                  <button
                    class={sessionSummaryFilter}
                    onclick={() => onFieldFilter('model', virtualRow.row.original.modelKey)}
                    title={`Filter by model ${virtualRow.row.original.modelKey}`}
                    type="button"
                  >
                    {virtualRow.row.original.modelLabel}
                  </button>
                  {#if virtualRow.row.getCanExpand()}
                    <button
                      class={sessionSummaryFilter}
                      onclick={() => toggleExpanded(virtualRow.row.original)}
                      title={virtualRow.row.getIsExpanded() ? 'Collapse campaign' : 'Expand campaign'}
                      type="button"
                    >
                      {virtualRow.row.getIsExpanded() ? 'Hide children' : 'Show children'}
                    </button>
                  {/if}
                </div>
                <span class={sessionSummaryStats}>
                  {#if mobileFresh.kind === 'value' && mobileCache.kind === 'value' && mobileDuration.kind === 'value'}
                    <span title={mobileFresh.title}>{mobileFresh.label} fresh</span>
                    · <span title={mobileCache.title}>{mobileCache.label} cache</span>
                    · <span title={mobileDuration.title}>{mobileDuration.label}</span>
                  {/if}
                </span>
              </footer>
            </article>
          </li>
        {/each}
        {#if virtual.bottomHeight > 0}
          <li aria-hidden="true" data-virtual-spacer="bottom" style:height={`${virtual.bottomHeight}px`}></li>
        {/if}
        <li aria-hidden="true" data-session-paging-sentinel="mobile" style:height="1px"></li>
      </ul>
    {/if}

    {#each rows.filter((row) => row.campaignKey && (typeof expanded === 'object' && expanded[row.rowId])) as row (row.rowId)}
      {@const campaign = row.campaignKey ? campaignChildren.get(row.campaignKey) : undefined}
      {#if row.campaignKey && (campaign?.loading || campaign?.nextCursor)}
        <div class={sessionPagingLoadMore}>
          <button
            class={ghostButton}
            disabled={campaign.loading}
            onclick={() => onLoadCampaignChildren?.(row.campaignKey!)}
            type="button"
          >
            {campaign.loading ? 'Loading campaign sessions…' : `Load more sessions in ${row.sessionLabel}`}
          </button>
        </div>
      {/if}
    {/each}
    {#if loadingMoreRows}
      <div aria-live="polite" class={sessionPagingLoadMore}>Loading more sessions…</div>
    {/if}
  </section>
{/if}
