// packages/design-system/src/svelte/controls/toggle.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export interface ToggleProps {
    ariaLabel: string;
    children: Snippet;
    class?: string;
    disabled?: boolean;
    onClick?: (event: MouseEvent) => void;
    onPressedChange: (pressed: boolean) => void;
    pressed: boolean;
    title?: string;
  }
</script>

<script lang="ts">
  import { Toggle } from '@ark-ui/svelte/toggle';

  let {
    ariaLabel,
    children,
    class: className,
    disabled = false,
    onClick,
    onPressedChange,
    pressed,
    title,
  }: ToggleProps = $props();
</script>

<Toggle.Root aria-label={ariaLabel} class={className} {disabled} onclick={onClick} {onPressedChange} {pressed} {title}>
  {@render children()}
</Toggle.Root>

// packages/design-system/src/components/toggle.tsx
import { Toggle as ArkToggle } from '@ark-ui/solid/toggle';
import type { JSX } from 'solid-js';

export interface ToggleProps {
  ariaLabel: string;
  children: JSX.Element;
  class?: string;
  disabled?: boolean;
  onClick?: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>;
  onPressedChange: (pressed: boolean) => void;
  pressed: boolean;
  title?: string;
}

export const Toggle = (props: ToggleProps) => (
  <ArkToggle.Root
    aria-label={props.ariaLabel}
    class={props.class}
    disabled={props.disabled}
    onClick={props.onClick}
    onPressedChange={props.onPressedChange}
    pressed={props.pressed}
    title={props.title}
  >
    {props.children}
  </ArkToggle.Root>
);
