// packages/design-system/src/components/segmented-control.tsx
import { ToggleGroup } from '@ark-ui/solid/toggle-group';
import { For } from 'solid-js';
import { presetButton } from './button';
import { presetGroup, presetGroupLabel, presetGroupShell } from './time-slider';

export interface SegmentedControlItem {
  label: string;
  value: string;
}

export interface SegmentedControlProps {
  ariaLabel: string;
  defaultValue?: string;
  items: readonly SegmentedControlItem[];
  label?: string;
  onValueChange: (value: string) => void;
  value: string;
}

export const SegmentedControl = (props: SegmentedControlProps) => (
  <div class={presetGroupShell}>
    {props.label ? <span class={presetGroupLabel}>{props.label}</span> : null}
    <ToggleGroup.Root
      aria-label={props.ariaLabel}
      class={presetGroup}
      deselectable={false}
      onValueChange={(details) => {
        const nextValue = details.value[0];
        if (nextValue) {
          props.onValueChange(nextValue);
        }
      }}
      value={[props.value]}
    >
      <For each={props.items}>
        {(item) => (
          <ToggleGroup.Item
            class={presetButton}
            data-default={String(item.value === props.defaultValue)}
            value={item.value}
          >
            {item.label}
          </ToggleGroup.Item>
        )}
      </For>
    </ToggleGroup.Root>
  </div>
);

// packages/design-system/src/svelte/compound/segmented-control.svelte
<script lang="ts" module>
  export interface SegmentedControlItem {
    label: string;
    value: string;
  }

  export interface SegmentedControlProps {
    ariaLabel: string;
    defaultValue?: string;
    items: readonly SegmentedControlItem[];
    label?: string;
    onValueChange: (value: string) => void;
    value: string;
  }
</script>

<script lang="ts">
  import { ToggleGroup } from '@ark-ui/svelte/toggle-group';
  import { presetButton } from '../../components/button';
  import { presetGroup, presetGroupLabel, presetGroupShell } from '../../components/time-slider';
  import { nextSegmentValue } from './segmented-control';

  let { ariaLabel, defaultValue, items, label, onValueChange, value }: SegmentedControlProps = $props();
</script>

<div class={presetGroupShell}>
  {#if label}
    <span class={presetGroupLabel}>{label}</span>
  {/if}
  <ToggleGroup.Root
    aria-label={ariaLabel}
    class={presetGroup}
    deselectable={false}
    onValueChange={(details) => {
      const nextValue = nextSegmentValue(details.value);
      if (nextValue) {
        onValueChange(nextValue);
      }
    }}
    orientation="horizontal"
    rovingFocus
    value={[value]}
  >
    {#each items as item (item.value)}
      <ToggleGroup.Item class={presetButton} data-default={String(item.value === defaultValue)} value={item.value}>
        {item.label}
      </ToggleGroup.Item>
    {/each}
  </ToggleGroup.Root>
</div>
