// packages/design-system/src/components/segment-bar.tsx
import { css, cx } from '@ai-usage/design-system/css';
import { For } from 'solid-js';

export const segmentBarTrack = css({
  display: 'flex',
  h: '10px',
  borderRadius: 'full',
  bg: 'track',
  overflow: 'hidden',
});

export const segmentBarPart = css({
  h: '100%',
  minW: '0',
});

export const barTrack = css({
  h: '6px',
  mt: '8px',
  borderRadius: 'full',
  bg: 'track',
  overflow: 'hidden',
});

export const barFill = css({
  h: '100%',
  borderRadius: 'full',
});

export const accentFill = css({ bg: 'accent' });

export const inkFill = css({ bg: 'ink' });

export const tokenSegmentClasses = {
  cacheRead: cx(accentFill, css({ opacity: 0.22 })),
  cacheWrite: cx(accentFill, css({ opacity: 0.42 })),
  input: cx(accentFill, css({ opacity: 0.68 })),
  output: accentFill,
};

export interface BarSegment {
  class: string;
  label: string;
  title?: string;
  value: number;
}

export const SegmentBar = (props: { segments: BarSegment[]; ariaLabel?: string }) => {
  const total = () => props.segments.reduce((sum, segment) => sum + segment.value, 0);
  const visibleSegments = () => props.segments.filter((segment) => segment.value > 0);
  return (
    <div aria-label={props.ariaLabel} class={segmentBarTrack} role="img">
      <For each={visibleSegments()}>
        {(segment) => (
          <div
            class={cx(segmentBarPart, segment.class)}
            style={{ width: `${(segment.value / Math.max(1, total())) * 100}%` }}
            title={segment.title ?? `${segment.label}: ${segment.value}`}
          />
        )}
      </For>
    </div>
  );
};

// packages/design-system/src/svelte/controls/segment-bar.svelte
<script lang="ts" module>
  import { css, cx } from '@ai-usage/design-system/css';
  import type { BarSegment } from './segment-bar';

  const segmentBarTrack = css({
    display: 'flex',
    h: '10px',
    borderRadius: 'full',
    bg: 'track',
    overflow: 'hidden',
  });

  const segmentBarPart = css({ h: '100%', minW: '0' });

  export interface SegmentBarProps {
    ariaLabel?: string;
    segments: readonly BarSegment[];
  }
</script>

<script lang="ts">
  import { segmentBarWidth, visibleBarSegments } from './segment-bar';

  let { ariaLabel, segments }: SegmentBarProps = $props();
  const visibleSegments = $derived(visibleBarSegments(segments));
</script>

<div aria-label={ariaLabel} class={segmentBarTrack} role="img">
  {#each visibleSegments as segment}
    <div
      class={cx(segmentBarPart, segment.class)}
      title={segment.title ?? `${segment.label}: ${segment.value}`}
      style:width={`${segmentBarWidth(segments, segment.value)}%`}
    ></div>
  {/each}
</div>
