// apps/web/src/report-sharing-actions.tsx
import { css, cx } from '@ai-usage/design-system/css';
import { ghostButton } from '@ai-usage/design-system/report';
import { createSignal, Show } from 'solid-js';

const actions = css({
  display: 'flex',
  flexWrap: 'wrap',
  gap: '8px',
  alignItems: 'center',
  minW: 0,
  ml: { base: '0', md: 'auto' },
  _print: { display: 'none' },
});

const noticeText = css({
  color: 'muted',
  fontSize: '12px',
});

const errorNoticeText = css({
  color: 'status.danger',
});

interface ReportSharingNotice {
  message: string;
  tone: 'error' | 'success';
}

export interface ReportSharingActionsProps {
  createExport: () => Promise<{ csv: string; filename: string }>;
}

export const ReportSharingActions = (props: ReportSharingActionsProps) => {
  const [notice, setNotice] = createSignal<ReportSharingNotice>();
  const copyCurrentLink = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setNotice({ message: 'Link copied', tone: 'success' });
    } catch {
      setNotice({ message: 'Could not copy link', tone: 'error' });
    }
  };
  const exportCurrentBreakdown = async (): Promise<void> => {
    try {
      const exportFile = await props.createExport();
      const { downloadReportCsv } = await import('./report-export');
      downloadReportCsv(exportFile.filename, exportFile.csv);
      setNotice({ message: 'CSV download started', tone: 'success' });
    } catch {
      setNotice({ message: 'Could not export CSV', tone: 'error' });
    }
  };

  return (
    <div class={actions}>
      <button class={ghostButton} onClick={copyCurrentLink} type="button">
        Copy link
      </button>
      <button class={ghostButton} onClick={exportCurrentBreakdown} type="button">
        Export CSV
      </button>
      <Show when={notice()}>
        {(currentNotice) => (
          <span
            aria-live="polite"
            class={cx(noticeText, currentNotice().tone === 'error' ? errorNoticeText : undefined)}
            role={currentNotice().tone === 'error' ? 'alert' : 'status'}
          >
            {currentNotice().message}
          </span>
        )}
      </Show>
    </div>
  );
};

// apps/web/src/lib/features/report/actions/report-sharing-actions.svelte
<script lang="ts">
  import { css, cx } from '@ai-usage/design-system/css';
  import { ghostButton } from '@ai-usage/design-system/svelte';
  import {
    browserSharingEnvironment,
    copyExactBreakdownUrl,
    type ExportFile,
    exportVisibleBreakdown,
    type SharingEnvironment,
    type SharingNotice,
  } from './sharing';

  const actions = css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
    minW: 0,
    ml: { base: '0', md: 'auto' },
    _print: { display: 'none' },
  });
  const noticeText = css({ color: 'muted', fontSize: '12px' });
  const errorNoticeText = css({ color: 'status.danger' });

  let {
    createExport,
    environment = browserSharingEnvironment,
  }: {
    createExport: () => Promise<ExportFile>;
    environment?: () => SharingEnvironment;
  } = $props();

  let notice: SharingNotice | undefined = $state();

  const copyLink = async (): Promise<void> => {
    notice = await copyExactBreakdownUrl(environment());
  };
  const exportCsv = async (): Promise<void> => {
    notice = await exportVisibleBreakdown(createExport, environment());
  };
</script>

<div class={actions} data-report-sharing-actions>
  <button class={ghostButton} onclick={copyLink} type="button">Copy link</button>
  <button class={ghostButton} onclick={exportCsv} type="button">Export CSV</button>
  {#if notice?.tone === 'error'}
    <span aria-live="assertive" class={cx(noticeText, errorNoticeText)} role="alert">{notice.message}</span>
  {:else if notice}
    <span aria-live="polite" class={noticeText} role="status">{notice.message}</span>
  {/if}
</div>
